kovidgoyal/kitty

- kitty/keys.py
Before the enter key on the numpad did not work, now it does.
> add the enter key on the numpad to the key map

- kitty/config.py
- kitty/kitty.conf
- kitty/main.py
I was personally not a fan of the window size caching, so I made it configurable.
Currently it still writes the previous window dimensions to cached.json even when disabled.
> Made window size caching and initial dimensions configurable

- kitty/boss.py
> Fix mouse coordinates off on macOS Retina display

- README.asciidoc
Its, when used possessively, does not use an apostrophe.
> Fix possessive "its"

- setup.py
os.makedirs has from python-3.2 option `exist_ok`
> Remove unneeded try except block

- kitty/screen.c
> correct off-by-one error in initial tabstops so emacs renders properly

- kitty/utils.py
Wrong indent level causes macOS to reference undefined "xdpi". 
File "./__main__.py", line 13, in <module>
File "./kitty/main.py", line 292, in main
File "./kitty/main.py", line 202, in run_app
File "./kitty/main.py", line 156, in initialize_window
File "./kitty/utils.py", line 123, in get_logical_dpi
UnboundLocalError: local variable 'xdpi' referenced before assignment
[glfw error 65537]: The GLFW library is not initialized
> Wrong indent level

- kitty/core_text.m
Improves font appearance on macOS, using same mechanisms as alacritty and iTerm2.
> Enable subpixel quantization and positioning

- README.asciidoc
Hello,
Added link for Arch Linux stable package
***
For building kitty in a clean chroot I had to add 'libxkbcommon' and 'libxkbcommon-x11' as dependency, otherwise it don't :)
> Updated readme

- README.asciidoc
- logo/make.py
Fix macOS build flow.
- Add install 'optipng' description because logo/make.py depends 'optipng'
- Add missing 64 size because doesn't create icon_32x32@2x.png
> Fix iconset build flow for macOS

- setup.py
`package()` method in `setup.py` tries to compile and chmod all files under the directory given by `--prefix PREFIX`.
If `PREFIX` is a directory containing other distributions (like `/usr/local` or `$HOME/.local`), then it would try to compile - using possibly the wrong python version - and chmod files within `PREFIX`.
> Fix packaging trying to modify unrelated files

- kitty/child-monitor.c
- kitty/config.py
- kitty/kitty.conf
- kitty/state.c
- kitty/state.h
This adds the close_on_child_death option to kitty's configuration, with the default being the current behaviour. (close_on_child_death no).
You kindly refactored the code to make this easy as a result of issue #378, and pointed me in the right direction to alter it. I know you're not keen on this addition, but as I've got the code written I thought it would be polite to send a pull request. No offence if you don't want to merge; I'll just maintain the fork in sync.
Thanks again for kitty, and for taking the time to help with this.
> Adds close_on_child_death option for disowned processes.

- kitty/fonts.c
As I was also creating a 32bit package, I got that error.
This fixes the compilation issue.
> Avoid comparison between signed and unsigned compilation error (32bit)

- README.asciidoc
while imagemagick is defined as an optional dependency in the installation section, its presence is indeed mandatory to successfully run `make app` as seen at https://github.com/kovidgoyal/kitty/blob/master/logo/make.py#L27
> update dependencies to run `make app`

- kitty/parser.c
- kitty_tests/parser.py
Various programs send a 0-length title if no title is configured (e.g.,
(n)vim with 'title' unset, or mutt without ts_enabled).  When this
happens, kitty is mis-parsing the data and setting the title to ";".
> Stop setting title to ";" when 0-length OSC 2 is received

- logo/make.py
The existing iconset generation code leads to the following error and the lack of an icon for the OS X app:
> Mar 30 22:58:36 OXY4776M iconutil[63748] <Error>: ImageIO: _CGImageDestinationCreateWithWriter capacity parameter (12) is too large for this file format (max is 10)
`icon_64x64.png` and `icon_64x64@2x.png` is [unnecessary](https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html). This PR prevents them from being created.
> Reduce icon set size to fit iconutil limits

- kitty/parser.c
parse_graphics_code() uses an unsigned long to detect if the id is
"> UINT32_MAX", however sizeof(long) == sizeof(void *) on Linux systems.
So this condition will be impossible on any 32-bit system.
> Use uint64_t to detect out of range graphics command id

- kitty/data-types.c
- kitty/fonts.c
- kitty/glfw.c
- kitty/graphics.c
Debian's [mips] build failed one of the font tests:
FAIL: test_sprite_map (kitty_tests.fonts.Rendering)
----------------------------------------------------------------------
File "/<<PKGBUILDDIR>>/kitty_tests/fonts.py", line 48, in test_sprite_map
self.ae(test_sprite_position_for(0, 1), (0, 1, 1))
self = <kitty_tests.fonts.Rendering testMethod=test_sprite_map>
AssertionError: Tuples differ: (0, 0, 0) != (0, 1, 1)
First differing element 1:
0
1
- (0, 0, 0)
?     ^  ^
+ (0, 1, 1)
?     ^  ^
This was due to test_sprite_position_for() using the "I" code to parse
into an unsigned short.  Since mips is big endian, the "wrong" byte was
stored into extra_glyphs.data.
This commit changes all similar data type mismatches that were found
from auditing calls to …
> Correct types for various PyArg_ParseTuple/Py_BuildValue calls

- kitty/cocoa_window.m
- kitty/config.py
- kitty/glfw.c
- kitty/kitty.conf
- kitty/main.py
- kitty/state.c
- kitty/state.h
Adds option for macOS to hide from tasks list. This is useful if you have kitty configured with a global hotkey and don't need to see it when alt tabbing.
> Add macos_hide_from_tasks option

- glfw/source-info.json
- kitty/child-monitor.c
- kitty/data-types.h
- kitty/glfw-wrapper.c
- kitty/keys.c
- kitty/shaders.c
- kitty/threading.h
This set of patches fixes the build on FreeBSD 11: it fixes errors resulting from the ordering of `#include`s, builds the correct (`null`) joystick driver for `glfw`, and deals with a `pthread` function naming issue.
I checked to make sure that these patches don't break the build in Linux (recent Arch)
> Fix build on FreeBSD 11

- kitty/kitty.conf
As this is copied to other people's computers, it's useful to have this
set so folding always works nicely.
> Set foldmethod in kitty.conf

- kittens/hints/main.py
- kitty/kitty.conf
This is specifically intended for git commit hashes, so it allows for
hashes as short as 7 characters (git's default length for abbreviated
hashes) up to the full 40 characters
>  Add support for sha1 hashes to the hint kitten 

- kitty/glfw.c
Before this change, kitty considered only changes in viewport size to
signal DPI, and on non-macOS platforms, it's the scaling factor, not
the viewport size, that changes when DPI changes.
When combined with the autodpi glfw change, this change will teach kitty to rescan itself automatically on X11.
> DPI change is either scaling or viewport-size change

- kitty/mouse.c
If we've previously reset the selection to EMPTY_SELECTION (say,
because we were marked dirty), the selection ends up being 0/0, so if
we click some random place, we suddenly get a non-empty selection
region and highlight random stuff even though all the user did was
left-click once somewhere.
This change ignores these unwanted region updates while (seemingly?) not breaking any actual selection features.
> Super-hacky avoidance of spurious selection

- docs/conf.py
- docs/conf.rst
- docs/kittens/diff.rst
- config files are placed into `docs/generated/conf/`, using the
expected name, and without any indentation
- `literalinclude::` is used instead of `include::`
- uses `:download:` instead of `:file:` to allow for downloading the
generated files easily
> docs: improve generation of default config files

- kitty/cli.py
Thank you for developing Kitty.
Currently kitty is not available on the list of "alternatives" for a
terminal emulator on Debian GNU/Linux and derivatives. This is because
Debian Policy states that packages that provide a terminal emulator must
provide, inter alia, support the command-line option -T title, which
creates a new terminal window with the specified window title [0].
This PR therefore adds -T as an alias for --title, thus bringing kitty into
compliance and allowing cleaner integration into the Debian desktop.
This issue was originally filed as #900704.
[0] https://www.debian.org/doc/debian-policy/#packages-providing-a-terminal-emulator
[1] https://bugs.debian.org/900704
> Support "-T" as an alias for "--title".

- kitty/session.py
Fixes `new_os_window`:
scancode: 0x39 release: 0 clean_sym: n composed_sym: N mods: ctrl+shift glfw_key: N
File "…/Vcs/kitty/kitty/boss.py", line 431, in dispatch_special_key
return self.dispatch_action(key_action)
File "…/Vcs/kitty/kitty/boss.py", line 487, in dispatch_action
passthrough = f(*key_action.args)
File "…/Vcs/kitty/kitty/boss.py", line 199, in new_os_window
self._new_os_window(args)
File "…/Vcs/kitty/kitty/boss.py", line 195, in _new_os_window
startup_session = create_session(self.opts, special_window=sw, cwd_from=cwd_from)
File "…/Vcs/kitty/kitty/session.py", line 127, in create_session
if args.hold:
AttributeError: 'NoneType' object has no attribute 'hold'
Regressed/added via #667.
> create_session: handle args=None

- kitty/glfw.c
When the `x11_hide_window_decorations` property is true, the `GLFW_DECORATED` window hint should be set to false.
> Fix hiding window decorations under X11/Wayland

- docs/index.rst
- kitty/complete.py
**WIP – Please do not merge yet**
I'm submitting this PR in its early stage to get some preliminar feedbacks and reviews, which are more than welcome.
> WIP Completion for fish

- kitty/freetype.c
Tested with [Terminus (TTF) ](https://files.ax86.net/terminus-ttf/) using the recommended font sizes, seems to fix issues mentioned in #106.
This _doesn't_ add support for bitmap fonts.
> Add support for embedded bitmap glyphs

- kitty/complete.py
It is standard to start complete helpers with underscore to avoid
clobbering the function namespace ; like other shells do.
It is ironic for a completion helper to make completion less agreable...
> bash completion: make complete helper start with _

- kitty/cursor.c
The old code would print "\e[22m" if either bold or dim was unset, which
is the "normal, neither bold nor dim" control sequence.
Print that only if neither are set, and instead print "1" and "2" (bold,
dim) values individually.
> cursor_as_sgr: fix bold/dim

- kitty/config_data.py
- kitty/main.py
First off, I am not a C or Python person so please excuse any obvious or stupid mistakes :).
This is in reference to issue #359 and is an attempt to create a config option for folks to specify a custom ibeam cursor when using macos. Currently the code expects a `beam-cursor.png` file to live in the local kitty config directory. I'm not really sure the best way to handle this as I'm not sure if you want to include a custom set with the distributed app or not.
The feature can be turned on by setting the `custom_cursor` flag in kitty.conf to true/yes.
Thoughts? Suggestions?
> [WIP] add support for custom cursor on mac

- glfw/xkb_glfw.c
When a key is pressed, text is generated from xkb and attached to the
global key_event variable.
If another key is pressed before ibus replies, this text in global
variable would be overwritten before the processed reply comes in and
the wrong character would be input, as shown in logs with
--debug-keyboard:
```
Press scancode: 0x19 clean_sym: w composed_sym: w text: w mods: numlock glfw_key: 87 (W) xkb_key: 119 (w)
↳ to IBUS: keycode: 0x11 keysym: 0x77 (w) mods: numlock
Press scancode: 0x20 clean_sym: o composed_sym: o text: o mods: numlock glfw_key: 79 (O) xkb_key: 111 (o)
↳ to IBUS: keycode: 0x18 keysym: 0x6f (o) mods: numlockIBUS processed scancode: 0x19 release: 0 handled: 0
From IBUS: scancode: 0x19 name: w is_release: 0
↳ to application: glfw_keycode: 0x57 (W) keysym: 0x77 (w) …
```
> glfw/ibus input: use text from ime event instead of global

- docs/index.rst
- kitty/boss.py
- kitty/tabs.py
As discussed in #809.
I'm pretty sure the only two commands with `previous` in them are are `previous_tab` and `previous_window` and there are no others.
Is the change in `docs/index.rst` ok or do you want a different separator, like `,` instead of `or`?
> Add prev_tab and prev_window as aliases for previous_tab and previous_window

- kittens/unicode_input/main.py
> unicode_input: use reverse mode for menu selection

- kitty/config_data.py
- kitty/cursor.c
- kitty/data-types.h
- kitty/history.c
- kitty/line.c
- kitty/screen.c
- kitty/state.c
- kitty/state.h
- kitty/window.py
- kitty_tests/__init__.py
- kitty_tests/bench_scrollback.py
- kitty_tests/datatypes.py
- kitty_tests/screen.py
PR as discussed in #970
This implements a straight circular buffer to dump lines as ansi text when they get ejected from the scrollback buffer
The behaviour can be disabled by setting a 0 size.
A couple of commits also look at `line_as_ansi()` as it is now performance-critical for scrollback, it might be possible to do better still.
There are no bugs/missing part of this that I am aware of but I'd like to test a bit more and probably clean up a bit
> Secondary pager history buffer

- glfw/wl_init.c
The Wayland protocol specification uses a Hz value in the key repeat rate field. The code however uses this value as a millisecond interval. This pull request makes the code calculate the interval from the Hz value.
This should probably be upstreamed to glfw but I'm not entirely sure how to go about that since the code seems to have seen quite a few changes there (but looks like it still does the wrong thing here).
> Fix Wayland key repeat frequency

- setup.py
Since you mentioned in #840 that you don't want to miss actually useful warnings from tic, I implemented a simple filter that ignores all messages that match a very specific regex.
> Filter tic output to remove "older tic versions may treat the description field as an alias"

- glfw/x11_window.c
kitty would have an incorrect position when clicking after changing window
without moving (e.g. change workspace, create new kitty etc)
For new kitty window, initial position would be 0 and selection paste would
not work because of this
FWIW I'll submit this one to glfw as well; I know you don't really care but if they request changes on this I'd like to update this patch to match - in this case I'll either do a subsequent PR, or we can wait for this, I have no clue if they're reactive for simple fixes like this.
> glfw x11: update cursor position on enter event

- glfw/cocoa_window.m
- glfw/glfw3.h
- glfw/internal.h
- glfw/null_window.c
- glfw/win32_window.c
- glfw/window.c
- glfw/wl_window.c
- glfw/x11_window.c
- kitty/cocoa_window.m
- kitty/config_data.py
- kitty/glfw-wrapper.c
- kitty/glfw-wrapper.h
- kitty/glfw.c
As discussed in #1088. The goal is to set the click_interval to the system default if the option is missing or set to system.
The current code will currently most likely break horribly on any platform that is not macOS.
Where should I put the platform specific code that gets the value from the system? glfw? If so, in which file does it fit best?
> [WIP] Respect the default system double-click interval

- kitty/core_text.m
- kitty/fonts.c
- kitty/fonts.h
- kitty/freetype.c
This handles multiple spaces after a PUA glyph (instead of just one).
Before:
After:
It still does not work as in (patched) urxvt, because kitty appears to shrink it to fit its height into the cell.  In urxvt it looks like follows:
Where does the shrinking / fitting to cells happen?  I would rather have it take the full width of the 3 cells, and be cut at the top/bottom.
> [WIP/RFC] Handle multiple spaces after PUA glyphs

- kitty/config_data.py
- kitty/mouse.c
- kitty/state.c
- kitty/state.h
I was testing high resolution scrolling under Wayland and found that scrolling becomes acceptable if I multiply `yoffset` by `10` and awesome if I multiply it by `20`.
Since `wheel_scroll_multiplier` is not used under high resolution scrolling at all, I thought we could put it to good use here, so that responsiveness becomes configurable.
Under Wayland, my `viewport_y_ratio` is `2`. I added it to this patch because it was suggested by @Luflosi in #1112, if you want to keep it, https://github.com/kovidgoyal/kitty/commit/82f9aecacbc0f76ca9e7aec809fc8cf3fd73ff5a probably needs to be reverted.
With this formula, scrolling is acceptable with default settings and I can further improve it if I change `wheel_scroll_multiplier` to `10`.
If we remove `viewport_y_ratio` from the formula, the default …
> Make high resolution scrolling more responsive and configurable

- kitty/boss.py
There is a logic error in `set_background_opacity` which breaks increment/decrement handling.
This commit fixes it.
> Fix set_background_opacity with increment/decrement

- .gitignore
When building kitty with `make asan` on macOS, a new directory `asan-launcher.dSYM` is created, which I think should be ignored.
> Ignore asan-launcher.dSYM directory

- kitty/cell_fragment.glsl
In 074614bc8e940725939aa7a316f0a7086e01e05c you removed the division by `final_color.a` in the case where `TRANSPARENT` is defined but that division is still there in the other case. I think, that `final_color.a` is always 1 in the case where `TRANSPARENT` is not defined. If that's the case, the division should be removed to be consistent with the other case.
> Make final_color computation consistent across cases

- glfw/xkb_glfw.c
`xkb_compose_state_new` [creates](https://github.com/xkbcommon/libxkbcommon/blob/110d17c6bee504569f68a105b2d4d06fe5e7e0b0/src/compose/state.c#L57) its own reference to a table, so this one is no more needed and causes the [leak](https://github.com/kovidgoyal/kitty/issues/1165).
> Fix memory leak on compose table creation

- glfw/x11_window.c
This prevents kitty to hang forever if a bad client does not give selection
(I know you don't care, but I did not submit this to upstream glfw - this part of the code is too different)
> glfw/x11_window/selection: timeout if no answer for two seconds

- kitty/lineops.h
This is a trivial change that doesn't conflict with the selection rework stuff that needs removing cobwebs by now :/
While I'm rebasing stuff, might as well push what I've got that's easy to merge
> selection: hilight 2nd half of wide characters last in line

- kitty/history.c
bufsize was bigger than the actual allocated memory
Fixes: b9e6557f729f ("Allow arbitrary sized lines in the secondary scrollback buffer")
> pager history: fix bufsize calculation

- kitty/config_data.py
- kitty/tab_bar.py
I didn't see any tests for tabs / the tab_bar, and I'm not sure how to setup such a test. I'm happy to add tests with some guidance on how to setup a tab_bar test.
As the PR is now, there is no space after the tab index and the title:
```
1:~ ┇2:vi ┇3:less
```
Related to #1223
> add option to show tab index in tab_bar title

- kitty/child-monitor.c
- kitty/glfw.c
- kitty/state.h
When `macos_quit_when_last_window_closed` is set to `no` (the default), Kitty does not exit on SIGINT. The signal handler just kills all OS windows, which on Linux or with the option set to `yes` will cause Kitty to exit.
This behavior is certainly annoying when hacking on Kitty. In this case I launch kitty as `python3 .` and then want to kill it from the dev terminal with Ctrl-C. The only way to kill it from the command line is `^Z kill -9 %1`, but that seems heavy handed and not as convenient.
My fix is to close the canary window when a kill signal is received. I think this bug is caused by conflating termination with closing all windows, which is why I also renamed `GlobalState.close_all_windows` to `GlobalState.terminate`.
> macOS: Exit on SIGINT

- docs/index.rst
- kitty/config.py
- kitty/tabs.py
This patch adds the `resize_window` configuration action, which has the following arguments:
1. Quality of resize amongst `wider`, `narrower`, `taller`, `shorter` (mandatory).
2. Increment in number of cells (optional, default: 1).
This makes it possible to configure keys as such:
map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+up resize_window taller
map ctrl+shift+down resize_window shorter
and have a behaviour which is somewhat close to Terminator's.
Should you accept this idea, I can add documentation in a subsequent patch.
> Add `resize_window` configuration action

- kitty/config_data.py
When I first read this in the docs:
> To setup shortcuts to change only the current window’s font size:
> `map kitty_mod+f6 change_font_size current 10.0`
I thought _current window_ meant the current layout's window (the window that you create with Ctrl+Shift+Enter), in that it would resize only this window's font size. Terminator has this feature, hence the confusion for me:
I thought this was a bug in kitty, but after reading the code I can see that it's meant to resize the whole OS window's font size:
```
if all_windows:
current_global_size = global_font_size()
new_size = calc_new_size(current_global_size)
if new_size != current_global_size:
global_font_size(new_size)
os_windows = tuple(self.os_window_map.keys())
else:
os_windows = []
w = self.active_window
if w is not None: …
```
> `change_font_size current ...` changes the current OS window's font size

- docs/index.rst
> Fix `resize_window` documentation example

- kitty/mouse.c
In my comment https://github.com/kovidgoyal/kitty/commit/009ef54de74d8c8acdd9fda1ccd4d172b4b20ce2#r31766142 I said that
```C
s = abs(((int)round(pixels))) / global_state.callback_os_window->fonts_data->cell_height;
if (pixels < 0) s *= -1;
```
is equal to
```C
s = (int)round(pixels) / global_state.callback_os_window->fonts_data->cell_height;
```
which is not correct because global_state.callback_os_window->fonts_data->cell_height is unsigned. Currently when scrolling down, `s` will be extremely large and not negative. Sorry about that.
> Fix broken downward scrolling

- kitty/mouse.c
Fixes #1257.
This commit ignores `wheel_scroll_multiplier` so that nothing changes on platforms that only ever report a `yoffset` of 1 or -1.
> Allow for scrolling acceleration in alternate screen mode when using low-resolution input devices like mice

- glfw/cocoa_window.m
- glfw/glfw3.h
- kitty/mouse.c
I added the other `NSEvent.Phase`s from https://developer.apple.com/documentation/appkit/nsevent/phase. We need one more bit in the flags variable. I changed the documentation to reflect my changes. I renamed one of the enum values from `StartMomentumPhase` to `MomentumPhaseBegan` for more consistency with the other values and the values in the cocoa code. I also moved the check for no scrolling distance from the cocoa code to `scroll_event()` because some `NSEvent.Phase`s can have zero `scrollingDeltaX` and `scrollingDeltaY` and with that check we would never see them in `scroll_event()`. I only check if `yoffset` is zero in `scroll_event()` because we don't care about `xoffset`. I also moved three lines of code down a bit because we don't need them if we return due to `if (yoffset == …
> Add more momentum scroll phases

- kitty/mouse.c
Fixes #1299.
Instead of multiplying `s` as I said I would do, I multiplied `yoffset` because it is also the variable being multiplied in the other case and doing it this way requires a little less code because we can reuse the check from the `if` statement above.
> Apply negative scroll multiplier in alternate screen mode

- kitty/border_fragment.glsl
- kitty/cell_fragment.glsl
Fixes #1285.
I played around with the cell_fragment shader code some more and while I don't really understand what's going on, this patch fixes the issue (while introducing a slight problem, which you should look at, I'll explain it later). This patch essentially undoes 074614bc8e940725939aa7a316f0a7086e01e05c and 96229becd1bef8bd69b412e61fac96146300646e except that it multiplies except of dividing. `final_color`, the result of the computation seems to need pre-multiplication and `final_color` before my new multiplication seems to not be pre-multiplied. Otherwise I can't explain why this patch works.
Here are some screenshots with various `background_opacity` settings and `background #ffffff` and `background #000000` colors in `kitty.conf` with and without the fix in front of a …
> Fix white background color not allowing transparency

- kitty/child-monitor.c
- kitty/glfw.c
- kitty/state.h
Fixes the problem reported in https://github.com/kovidgoyal/kitty/issues/1312.
I chose to do the unjamming in `set_cocoa_pending_action` to avoid similar issues in the future. This is probably not necessary for `PREFERENCES_WINDOW`, but the cost is minuscule.
> Unjam event loop when adding pending cocoa action

- kitty/fonts.c
The definition of `RENDER` has a semicolon at the end of it. Therefore we don't need another semicolon when `RENDER` is used.
> Remove unnecessary semicolons

- docs/index.rst
I'm pretty sure this line doesn't belong here. It was introduced in 4e99194022fa678708d2865843c0c957557b49c6.
> Remove unwanted line

- .circleci/config.yml
- build-terminfo
- kitty/main.py
- setup.py
I renamed some instances of `OS X` and `osx` to `macOS`, since that is the correct name since macOS 10.12 Sierra, which was released in September of 2016. `setup.py` can be called with `osx-bundle` as an argument. I added a new argument `macos-bundle` but kept the old one for backwards compatibility since I don't want to break anything. Should I keep that option in the list of `choices`?
Some instances of `osx` remain, mainly in `publish.py`, `.circleci/config.yml` and both in the filename and content of `update-on-ox` but I didn't change those because I'm too afraid, that that could break something.
> Rename OS X -> macOS

- setup.py
I missed one instance of "OS X" in #1341, sorry about that.
> Missed one instance of "OS X"

- kitty/boss.py
- kitty/child-monitor.c
- kitty/cocoa_window.m
- kitty/state.h
- setup.py
This pull request is supposed to implement a service on macOS that allows opening a new OS or kitty window or tab from Finder. I'm pretty bad at programming in Objective-C, so keep that in mind. Any suggestions are very welcome. Right now it's only a proof of concept, it only prints a message and doesn't actually open a new tab or whatever yet. The new files are probably in the wrong folder (glfw). I'm not sure if the new header file is needed. The code from iTerm2 helped me a lot. Could this be a problem since iTerm2 is licensed under GPLv2? Or does that not matter since it's only a very small part of it, which has been modified quite a bit?
> macOS Finder Service to open a directory in a new kitty tab or window

- docs/changelog.rst
- docs/index.rst
- kitty/config_data.py
Don't merge this yet @kovidgoyal. I'll change a few minor things, like removing the commented out `close_os_window` keyboard shortcut, before this is merged. I'd also like to get some feedback from other macOS users first, especially about the behaviour of `cmd+w`, the default of `macos_option_as_alt`, if there are any keyboard shortcuts I didn't add that should be added and if there are any issues. Should we ping some macOS users?
I went through all the options in `kitty/config_data.py`, my config file and the generic, Terminal.app specific and Safari specific Apple keyboard shortcut documentation and added all options that could apply to kitty on macOS, which are common in other macOS apps or which I think are sensible.
I've put the Mac specific keyboard shortcuts always right after the …
> [WIP] Add more common macOS keyboard shortcuts

- kitty/fonts.c
- kitty/gl.h
- kitty/shaders.c
I think most `fatal()` messages begin with an upper case character so I changed the lower case ones. I didn't change the one message beginning with `read_png_error_handler:` as that is a function name.
> Let all fatal messages begin with an upper case character

- kitty/glfw.c
Fixes a minor variable initialization mistake that causes the recent workspace-aware focus history on macOS to fail. See my comment in the referenced issue: #1379
> #1379 highest_focus_counter and loop index should be initialized to 0

- glfw/ibus_glfw.c
Im pretty sure this function is not supposed to return a boolean. I think this function is only used for `memcpy(ans, addr, MIN(strlen(addr), sizeof(ans)));`. Using a boolean here means that `memcpy()` copies at most one byte (I think). What sort of bugs would this cause?
> Fix function returning the wrong type

- kittens/choose/main.c
If `sizes` is `NULL`, then `clines` isn't freed. This pull request fixes that. I added `clines = NULL` because I think it's good practice but it doesn't do anything here, so if you don't like it, you can remove it.
> Fix memory leak

- kittens/diff/config_data.py
- kitty/config_data.py
Most color codes are lower case. This pull request changes three color codes that have upper case characters in them.
> Consistent case for color codes

- kitty/fonts.c
The check `if (cell_height > 1000)` a couple lines below considers `cell_height` to be valid if it's 1000 or less but the check `if (ch >= 4 && ch < 1000)` considers `ch` to be valid if it is less than 1000. I changed it so 1000 is still a valid value.
> Change cell_height and cell_width checks to be consistent with later check

- kitty/fonts.c
This might be helpful for #1380 but I think it could also be useful in other circumstances.
> Log the exact value of the cell height/width when it's invalid

- docs/protocol-extensions.rst
- kitty/config_data.py
- kitty/window.py
If no-append is present in clipboard_control, this will disable kitty's OSC 52 extension of concatenating to the clipboard. See #995
This is a compromise that I hope will be acceptable, since it doesn't change kitty's default behavior, and won't catch existing users off-guard.
I also considered using a separate option, but it seems unnecessary to add yet another option for something that only tweaks the behavior of OSC 52. Let me know if you'd prefer a separate option and I'm happy to update the PR.
> Allow no-append in clipboard_control

- build-terminfo
When compiling the terminfo file by calling `package()` in `setup.py`, an extra `terminfo` was created. See https://github.com/kovidgoyal/kitty/pull/1435#issuecomment-469446044. This pull request should fix that. Sorry about that.
> Fix wrong terminfo location

- kitty/core_text.m
When `gray_color_space` is `NULL`, it is passed into `CGBitmapContextCreate()`. Since there are no guarantees in https://developer.apple.com/documentation/coregraphics/1455939-cgbitmapcontextcreate?language=objc to what happens in that case, depending on the implementation there may be undefined behaviour.
> Fix potential undefined behaviour

- kitty/config_data.py
- kitty/fonts.c
- kitty/fonts.h
- kitty/screen.c
- kitty/screen.h
- kitty/shaders.c
- kitty/state.c
- kitty/state.h
In #461 you gave a few helpful tips, and after a couple hours of trying different things, I came up with the following code that doesn't even touch any CPU or GPU cells and seems to work as a proof of concept. There is a line `render_ligature = (i != 4)` with a constant (4 in this case). All ligatures beginning in the third cell from the left of the screen will be rendered as individual characters.
Does this look promising to you? Is this the right approach?
> Do not render ligatures under cursor

- kitty/mouse.c
I know that you wrote in #1516 that this was never an intended feature, but as I wrote in the commit message:
> I believe this behaviour has come to be expected by users, since GNOME Terminal, Terminator, xterm, rxvt, major browsers, LibreOffice, and many more significant applications have it.
> Double-click + drag to select multiple words

- docs/index.rst
This is to make sure, beyond more documentation, that #1521 is considered a feature as it is documented.
> Docs: update mouse features

- kitty/config_data.py
- kitty/tabs.py
When setting `tab_bar_switch_to_previous_when_closing_current_tab` kitty will now switch to the left tab instead of the previously active one when the currently active tab is closed. This makes the closing of tabs a bit more predictable. It works well in my workflows as I tend to open and close a lot of tabs.
Note that we are not touching the handling of the active_tab_history at all. I was considering it, but we want to keep track of it in any case to keep the 'switch to previous tab' shortcut working.
Thanks!
> Add option to disable switching to the previous tab when closing the current one.

- LICENSE
- __main__.py
- docs/build.rst
- docs/conf.py
- docs/faq.rst
- docs/protocol-extensions.rst
- kitty/charsets.c
- kitty/config_data.py
- kitty/khrplatform.h
- kitty/modes.h
- kitty/screen.c
- kitty/shaders.c
I converted those URLs because HTTPS should provide a bit more security than HTTP.
I checked every single URL by hand and ran `make linkcheck` to make sure that the site supports HTTPS.
Is it ok to change the URLs in the LICENSE? Not sure.
I didn't change the URL for `http://man7.org/linux/man-pages/man7/shm_overview.7.html` as `man7.org` doesn't even allow connections on port 443. I didn't change `http://pygments.org/` because the certificate is only valid for a different domain. The same is true for `http://cocoadev.com/index.pl?GameKeyboardHandlingAlmost` but that site seems to be totally dead atm, showing a 404 for that specific page and the nginx welcome page in the root directory. There are also some HTTP URLs in the tests, which I did not touch because I'm pretty sure that no …
> Convert HTTP URLs to HTTPS URLs where possible

- docs/changelog.rst
In 934336e64278dae88ab87aa75c9bf553a5931fa6, the config option
`disable_ligatures_under_cursor` was renamed to `disable_ligatures` and the
behaviour of that option was altered so that it is now possible to
disable ligatures completely. This commit reflects that change in changelog.rst
> Update changelog.rst to reflect change to disable_ligatures config option

- kitty/config_data.py
It was really hard to find why some font didn't work, I tried to use `Hack Nerd Font` as in `fc-list` output, but kitty accepts another name: `Hack Regular`.
I found this command `kitty list-fonts` in https://github.com/kovidgoyal/kitty/issues/1098#issuecomment-433576219 but not in docs and not in `man kitty`. So I think it should be mentioned in font related docs.
> Mentioned `kitty list-fonts` command

- build-terminfo
`build-terminfo` had no header with the encoding and license, so I added it.
> Add file header to build-terminfo

- glfw/cocoa_window.m
This reverts commit 89692064503ccfbb66374a42d63401a96511501f.
Fixes #1621.
When committing b3f1acd400d524c079a0a5ea833756053834db5d, applying the glfw upstream patch https://github.com/glfw/glfw/commit/3c3981a4f00cdee0f20be6866305715a29b94125 for https://github.com/glfw/glfw/issues/1461, this commit should have been reverted as it was just a quick fix for https://github.com/glfw/glfw/issues/1461.
> Revert "macOS: Fix cocoa mouse y-coord off by one"

- kitty/config_data.py
Fixes #1626.
This makes it harder to miss this option in case a user is confused why the mouse cursor keeps disappearing.
> Move documentation for `mouse_hide_wait` config option to the top of the `Mouse` group

- docs/index.rst
I rewrote the first sentence since there are also package managers for macOS and Nix can be used on most Linux distributions. I didn't include MacPorts since the kitty package there doesn't currently have a maintainer: https://www.macports.org/ports.php?by=name&substr=kitty.
I verified that kitty works when installed on macOS via Homebrew and Nix.
Since Nix doesn't only work on NixOS but also on macOS and on Linux, I removed the line specifically mentioning NixOS since people using NixOS will most likely know that Nix works on NixOS. I changed the link to the Nix package because in my opinion the new link is more helpful to the average user than the old one.
Does putting `(` and `)` into the name for the link cause any problems?
> Add Homebrew and Nix (not only on NixOS) as package manager to the installation instructions

- kitty/freetype.c
gcc 4.8 produces the following warnings:
kitty/freetype.c: In function ‘render_bitmap’:
kitty/freetype.c:369:36: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
for (unsigned int i = 0; i < bitmap.rows; ++i) {
^
kitty/freetype.c:371:40: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
for (unsigned int j = 0; j < bitmap.width; ++j) bitmap.buffer[i * stride + j] *= 255;
> Fix warning with gcc 4.8

- docs/conf.py
The man page showed the year 2018 at the bottom. Instead of changing it to 2019, I made it dynamic so that it is always current the year at the time of building.
> Make the copyright year dynamic for the documentation

- docs/conf.py
`docs/conf.py` had no shebang, so I added it.
You may also want to add the usual
```
```
but I'm not sure if you want that in this file.
> Add shebang for docs/conf.py

- kitty/boss.py
- kitty/config_data.py
- kitty/layout.py
Fixes #505.
Needs some documentation, but I'll wait for a review first.
> Stack layout: Add align_top_left option

- kittens/ask/main.py
- kittens/diff/collect.py
- kittens/diff/main.py
- kittens/tui/images.py
- kittens/unicode_input/main.py
- kitty/boss.py
- kitty/child.py
- kitty/client.py
- kitty/cmds.py
- kitty/config.py
- kitty/constants.py
- kitty/main.py
- kitty/remote_control.py
- kitty/rgb.py
- kitty/shell.py
- kitty/tabs.py
- kitty/update_check.py
- kitty/utils.py
- kitty_tests/gr.py
- publish.py
- setup.py
- update-on-ubuntu
Using
```Python
with suppress(OSError):
os.remove('somefile.tmp')
```
instead of
```Python
try:
os.remove('somefile.tmp')
except OSError:
pass
```
makes the code more compact and more readable IMO.
This pattern was recommended by Raymond Hettinger, a Python Core
Developer in his talk "Transforming Code into Beautiful, Idiomatic Python" at https://www.youtube.com/watch?v=OSGv2VnC0go. The transcript is available at https://github.com/JeffPaine/beautiful_idiomatic_python
> Use "with suppress()" to suppress python exceptions

- kitty/boss.py
As far as I can tell, `.active_window` does absolutely nothing, so I
removed it.
> Remove useless code

- gen-apc-parsers.py
The `payload` variable is assigned twice.
Static program analysis FTW!
> Remove double assignment

- kitty/boss.py
The result from `self.add_os_window()` is overwritten later and not used
between the two assignments, so I removed the first assignment and moved the second
assignment to the line after the call to `self.add_os_window()`.
> Simplify code

- kitty/window.py
Searching for `color_as_vec3` yielded no results in the entire project
but I encourage you to verify that this function is really not used
anywhere.
> Remove unused function

- kitty_tests/datatypes.py
`lspace_test()` has a parameter called scheme with the default value `http`. It
is called in a nested for loop, but the scheme from the inner for loop is
just ignored.
> Fix `test_url_at`

- kitty/borders.py
I think it's better to use `ImportError` here instead of the much more generic `Exception`.
> Use more specific exception

- publish.py
As far as I can tell, these attributes are not used anywhere.
> Remove unused code

- count-lines-of-code
All python scripts start with `#!/usr/bin/env python3` so I did the same
for a bash script.
> Use "#!/usr/bin/env bash" shebang instead of "#!/bin/bash"

- glfw/egl_context.c
- glfw/glx_context.c
- glfw/input.c
- glfw/monitor.c
- glfw/nsgl_context.m
- glfw/osmesa_context.c
This only changes some formatting, whitespace, etc.. There are no
changes to the functionality, except maybe
```diff
-if (value > 65535.f)
-    value = 65535.f;
+value = fminf(value, 65535.f);
```
Let me know if you don't like some of those changes.
> Reduce the difference of glfw to upstream

- setup.py
Calling `Env()` without the `ldpaths` parameter after a call with the `ldpaths` parameter, keeps the list from the first call because the argument is mutable. This is probably not what was intended. This commit fixes this issue and also reverts a change to two lines introduced in 091e74d618daca960193639bce96c3db82331e70, which was probably a workaround for this issue.
> Make default argument non-mutable

- .gitignore
Building `kitty-profile` on macOS creates a `kitty-profile.dSYM` directory, that should be ignored, just like `asan-launcher.dSYM`.
> Ignore all *.dSYM directories

- setup.py
I see a couple problems with using git to determine the files to delete:
- git needs to be installed
- The manual cleaning code is supposed to function correctly, so why not always use it? That way bugs in the manual cleaning code are also more likely to get discovered
- If some files ignored by git should not be deleted, they need to be added to a sort of blacklist. If some files should be deleted by the manual cleanup code, they need to be added to a sort of whitelist. If someone forgets to add files to one of these lists, then not deleting files that should be deleted is better than deleting files that should not be deleted.
> Always clean files manually instead of using git

- launcher.c
The `<sys/stat.h>` include in `launcher.c` is only used to check if the executable is a symlink on macOS. Therefore it is not needed on other platforms.
> Only #include <sys/stat.h> on macOS

- setup.py
`file` and `arguments` are accessed using the square bracket syntax, while `output` is accessed using `.get()`. This commit uses square brackets for all three. This will throw a `KeyError` if `compilation_database` does not have the key, which is the correct behaviour IMO.
> Unify compilation_database access

- setup.py
`ans.append('KITTY_VCS_REV="{}"'.format(rev.strip()))` strips the
whitespace again later.
> .strip() only once

- setup.py
I think the build directory is a better place for these temporary files. Maybe you have a different opinion though.
Is the nested directory structure ok or do you prefer a totally flat structure with no directories?
> Move temporary location for shared objects into build directory

- kitty/child-monitor.c
- kitty/cocoa_window.m
I renamed `cocoa_update_title()` to `cocoa_update_menu_bar_title()` since that more accurately reflects what this function actually does.
> Rename cocoa_update_title() -> cocoa_update_menu_bar_title()

- kitty/mouse.c
Assuming the call to `update_drag()` returns basically instantly, this call to `monotonic()` can be safely removed.
> Remove unnecessary call to monotonic()

- kitty/cocoa_window.m
All the other casts to `NSWindow` in this file have the same formatting.
> Remove space from cast in kitty/cocoa_window.m

- glfw/internal.h
Caused by https://github.com/kovidgoyal/kitty/commit/fe62700825ef4b9bb143b3792797959d85181b29.
> Fix indentation of bool variables in glfw/internal.h

- glfw/input.c
From https://github.com/glfw/glfw/commit/9420e6f0d090f2f3fe61f71d5e05220f5245c861.
> GLFW: Fix invalid ranges for gamepad axis sources

- glfw/egl_context.h
Caused by https://github.com/kovidgoyal/kitty/commit/fe62700825ef4b9bb143b3792797959d85181b29.
> Fix indentation of bool variables in glfw/egl_context.h

- .gitignore
The `build` directory is always located at the root directory of the repository. Therefore it's better to only ignore `build` in this location.
> Ignore the `build` directory only in the root of the repo

- kitty/main.py
According to https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait, `wait()` throws a `TimeoutExpired` exception when the process is not done after the timeout. I noticed this because kitty crashed for me.
The old code looks like it's trying to wait as long as it takes for the process to finish, which is what I implemented.
> Fix crash when the shell takes too long to start when reading the environment

- docs/graphics-protocol.rst
- docs/installer.py
- gen-wcwidth.py
- glfw/glfw.py
- kittens/tui/images.py
- kitty/child.py
- kitty/cli.py
- kitty/client.py
- kitty/conf/utils.py
- kitty/keys.py
- kitty/rgb.py
- kitty/utils.py
- kitty_tests/gr.py
- publish.py
- setup.py
- update-on-ox
- update-on-ubuntu
Inspired by https://github.com/kovidgoyal/calibre/commit/d50a6ddc1b71a575283e344a0d7bc539539bc5d1.
There are a couple instances of `open()` left where we're not using context managers that I didn't change because I'm not sure how to do that: There are a couple instances of `sys.stdin = open(os.ctermid(), 'r')` in the kittens, `self.dump_bytes_to = open(args.dump_bytes, 'wb')` in `DumpCommands` in `kitty/boss.py`, `subprocess.call(['pprof', '--callgrind', exe, '/tmp/kitty-profile.log'], stdout=open(cg, 'wb'))` in `kitty/main.py`, `fd = os.open(path, os.O_CREAT | os.O_WRONLY | os.O_TRUNC | os.O_CLOEXEC)` in `kitty/utils.py` and `io.BufferedReader.__init__(self, open(path, mode))` in `publish.py`.
> Use context managers to open files

- docs/changelog.rst
- kitty/child-monitor.c
- kitty/cocoa_window.m
- kitty/config.py
- kitty/config_data.py
- kitty/data-types.h
- kitty/glfw.c
- kitty/state.c
- kitty/state.h
See #1072.
Don't merge this yet please.
I have a couple questions:
Do I need the autoreleasepool in `cocoa_hide_window_title()`?
Why are there seemingly two places for the deprecated config options? One below
```Python
@deprecated_handler('macos_show_window_title_in_menubar')
```
and one here:
```Python
if not getattr(opts, 'macos_show_window_title_in_menubar', True):
opts.macos_show_window_title_in = 0b01
```
Is there some way to have one config option but two independent variables where that option is stored? `macos_show_window_title_in_menubar` and `macos_show_window_title_in_window` are really two different, independent options. I agree that having one config option for the two things is better but in the code I'd like to treat them separately, so I don't need to use bit masks and bit …
> Add option to hide the window title on macOS

- glfw/glfw.py
These Frameworks are added again a couple lines below in the check for `module == 'cocoa'`.
> Don't add Apple Frameworks twice

- kitty/glfw.c
In b5c21632383f9ff27c13991c91c5a72187a1196a I introduced a bug where only the window title of the first OS window would be hidden. This commit fixes that bug.
The bug was caused by the code hiding the window title being in an `if` statement that only executes once.
> Fix hiding the window title in macOS

- kittens/hints/main.py
The hints kitten's help documentation did not mention what syntax to use
for the regular expressions. I knew much of kitty was implemented in
python so I guessed correctly but not everyone might know this.
I also fixed some double-spaced sentences because most of them are
single-spaced.
> Add expected regex syntax to hints kitten docs

- glfw/cocoa_window.m
- kitty/boss.py
- kitty/glfw.c
Closes #1368.
Since two people asked for this feature and I agree that this would be nice to have, I implemented it.
Is calling `_glfwInputDrop()` for dropped text the right thing to do?
I also thought about adding a `flags` parameter to `_glfwInputDrop()` to signal if a string was a file URL or normal text. But since it's possible that the array of strings contains both types, I didn't do that. I would have to add this information to every string individually.
Is calling `_glfwInputError()` in the `else` case the right thing to do or can you think of a better solution? This code should never be called but I just want to make sure nothing bad can happen.
I'm not sure which convention to follow regarding the curly braces. GLFW seems to have them in new lines but your code seems to not do …
> macOS: implement drag and drop of text into kitty

- glfw/cocoa_window.m
- glfw/wl_window.c
This commit changes the indentation of two error messages to match the indentation in the rest of the code.
Mostly unrelated: Why are the functions `_glfwPlatformSetClipboardString()` and `_glfwPlatformGetClipboardString()` in `wl_window.c` so different between the GLFW version in kitty and the upstream version? I thought we could maybe combine the two to get the best from both and then try to get the new version upstream as well.
> Correct indentation for two _glfwInputError() messages

- glfw/glfw.py
This commit removes the need for `is_macos` in `glfw/glfw.py` by moving a few lines of code. Instead of relying on the information that the compilation is or isn't happening on macOS, the code now does the right thing based on which `module` is being built.
This changes the order of the compilation flags slightly.
> Simplify GLFW compilation code

- glfw/cocoa_window.m
See https://stackoverflow.com/questions/720052/nslog-incorrect-encoding.
The `%s` format placeholder for `NSLog()` expects an encoding other than UTF-8, which leads to garbled Unicode characters when trying to print a UTF-8 encoded string:
```Objective-C
NSLog(@"Ä %s %@", "Ä", [NSString stringWithUTF8String:"Ä"]);
```
prints `Ä √Ñ Ä`.
As can be seen in the example above, the workaround is to convert the UTF-8 encoded C-string to an `NSString` and print that instead.
`debug_key()` calls `NSLog()`.
> Fix NSLog() printing of unicode format strings

- glfw/glx_context.h
- glfw/linux_joystick.h
- glfw/posix_thread.h
- glfw/posix_time.h
- glfw/xkb_glfw.h
The wrong indentation was caused by the removal of GLFWbool in https://github.com/kovidgoyal/kitty/commit/fe62700825ef4b9bb143b3792797959d85181b29.
> Fix bool indentation

- glfw/glfw3.h
- glfw/input.c
- kitty/glfw-wrapper.h
- kitty/key_encoding.py
When adding keys after `GLFW_KEY_UNDERSCORE`, one now needs to change a `#define` right below the last printable key instead of changing it elsewhere in the code.
This commit now also marks `GLFW_KEY_PLUS` and `GLFW_KEY_UNDERSCORE` as printable characters.
Why does `GLFW_KEY_SPACE` not count as a printable character in `glfwGetKeyName()`?
> Make adding more printable keys slightly easier

- kitty/key_encoding.py
I did not run `update_encoding()` when I added `LAST_PRINTABLE` in b3b830bb5ffb8f42d5e2367e5aab03579be3a45f. This commit fixes that.
> Format kitty/key_encoding.py with yapf

- glfw/glfw.py
Rather than using null_joystick.c when _plat is a bsd, use linux_joystick.c when _plat is a linux.  This fixes a build issue with other non-BSD, non-Linux platforms.
> Only use linux_joystick.c on Linux

- kitty/colors.c
For reference: https://github.com/joejulian/xterm/blob/master/256colres.pl#L63-L88
Can be tested using `echo -e "\e[48;5;232m                \e[0m"` ([via](https://raw.githubusercontent.com/roosta/colors/master/scripts/support/256-colors.sh))
> Fix color index 232

- kitty/key_names.py
In #1928 I accidentally added `PLUS` to `key_name_aliases` even though in https://github.com/kovidgoyal/kitty/pull/1942#issuecomment-526873757 you said that this won't work.
> Remove PLUS key from key_name_aliases

- glfw/null_joystick.c
- glfw/null_monitor.c
- glfw/null_window.c
kitty didn't compile on FreeBSD for me because of unused parameters in glfw/null_joystick.c, so I added the `UNUSED` attribute to them.
I also added `UNUSED` to the unused parameters in glfw/null_monitor.c and glfw/null_window.c as well even though they are probably not used.
> Mark unused parameters in glfw/null_*.c

- kitty/glfw.c
In 535606fadb95316f336be4492470ab889b642bc5, I had kitty resize its text on OS DPI change. 0b3c8210f3472c7d420c503193391fe9ace0c8cc appears to have broken that feature. This PR fixes it.
> Fix window resize on DPI change

- kitty/update_check.py
`CHECK_INTERVAL` wasn't used anywhere and since it's also set to `24 * 60 * 60`, I replaced the second `24 * 60 * 60` with `CHECK_INTERVAL`.
> Use the update CHECK_INTERVAL constant

- .gitattributes
I think `linguist-generated=true` is missing here. This line was added in 5faa649452fd8c3006cc113ecb4f8ad8349f866a.
> Mark kitty/unicode-data.c as being generated

- glfw/cocoa_init.m
- glfw/cocoa_platform.h
- glfw/cocoa_window.m
From https://github.com/glfw/glfw/commit/ea7eb2ddab823e21c846c68d112d90f91fcba318.
I'm trying to apply this commit from upstream but I ran into a little problem:
`glfwSetApplicationShouldHandleReopen()` and `applicationShouldHandleReopen()` in `glfw/cocoa_window.m` access the variable `handle_reopen_callback`. I need to move `applicationShouldHandleReopen()` to `glfw/cocoa_init.m`. One of the two functions will no longer be able to access the variable.
What is the best way to solve this problem? Can I somehow move `glfwSetApplicationShouldHandleReopen()` or make the variable visible in the two files?
> Cocoa: Move app delegate and menu creation to init

- glfw/cocoa_init.m
From https://github.com/glfw/glfw/commit/2fbb560eb72fea695687d33066c91a329d6d0465.
I don't think this bug actually affects kitty.
> Cocoa: Fix window creation blocking after re-init

- glfw/glfw3.h
In 4c4c6ab0e68c56710f9a1eb07ae8a4d878664ace you added a weird unicode character, which is apparently called an Object Replacement Character, instead of a space.
> Replace weird character with space

- docs/index.rst
Instead of a fragment identifier, the URL now needs a query parameter.
> Fix link to Nix kitty package

- .gitattributes
- count-lines-of-code
`kitty/khrplatform.h` was removed in f872f955b02b4c352939d6ebb507d80f73de5da9.
> Remove remaining references to kitty/khrplatform.h

- docs/conf.py
All the other python encoding headers are of the form `vim:fileencoding=utf-8`.
> Unify python encoding headers

- count-lines-of-code
This file is automatically generated and should not count towards the total line count.
Does this list of files have any order or should I just append the file name at the end like I did?
> Exclude kitty/parse-graphics-command.h from the line count

- kittens/icat/main.py
- kitty/fonts.c
- kitty/fonts/box_drawing.py
Fixes #2006
:tada: :tada: :tada: 
Thanks for the help @kovidgoyal 
---
I updated the testing functions to use the new format of the class `setup_for_testing` (was probably a function before, now it uses a `with ...:` syntax).
I also changed something in icat, because the testing functions for box drawing make use of the method `show` from icat, which previously gave an error saying that `screen_size` is None at this line:
https://github.com/kovidgoyal/kitty/blob/26b7b1ec63198979a3d7795eaa36ed28646e7f3d/kittens/icat/main.py#L125
(which is called from `show`)
> Fix triangle glyphs scaling by drawing them manually

- kitty/config_data.py
- kitty/tab_bar.py
This PR adds support for powerline styled tabs. I had to add the inactive fg/bg colors to the draw_data to be able to produce the colour transitions properly. To avoid having the background colour continue after the last tab i added the `is_last` parameter to the `draw_tab_with_x` method. This can probably be reused to have the `separator` style stop at the last item too. 
It's been a while since I've written any python so please let me know if here are things I should have done differently.
> Adding powerline style tabs

- kitty/mouse.c
- kitty/screen.h
- kitty/state.h
Scrolling in one screen shouldn't affect the `pending_scroll_pixels` for another screen in the same OS window.
> Store pending_scroll_pixels for every screen

- kittens/icat/main.py
Fixes https://github.com/kovidgoyal/kitty/issues/2081.
This bug was introduced in 10e5fcc37535fdf6eed7f03f1c5380a2b4f0db9c.
One place in the code requires the actual `screen_size_function`, not just the result of it.
> Fix icat kitten

- kitty/constants.py
The `if` can be removed by using `get()` with a default parameter to access `os.environ`. This also reduces the number of accesses to `os.environ`.
> Simplify access to os.environ

- kitty/config_data.py
- kitty/main.py
- kitty/utils.py
Fix #2096
I've tried to maintain the current semantics. For example, I still try `EDITOR` if `VISUAL` isn't found on the system rather than blindly defaulting to `VISUAL` as long as it's set.
I'm not sure if any documentation needs updating outside of the config template?
> Prefer VISUAL to EDITOR

- kitty/constants.py
When `PATH` is not in `os.environ`, kitty could potentially throw a `KeyError`.
> Fix potential error when $PATH is not defined

- setup.py
When a linker process fails, `failed` will be set to a value other than `None`. When a second linker process fails, the `else` case will be taken because `failed is None`, which executes `compile_cmd.on_success()`. This function tries to rename or move the file generated by the linker but since the linker process failed, the file will most likely not exist. This will throw an error, which will prevent printing the actual error message from the linker.
> Fix error when two linker processes fail

- docs/pipe.rst
The @selection input placeholder is not currently listed in the documentation. This commit adds it to the top of the list.
> docs: added '@selection' to pipe documentation.

- glfw/wl_window.c
In 841c907efc643a4f4f06b2686d0d1e6022710600, the `%m` format specifier was replaced by `%%m`, which just prints `%m`. To keep the functionality of `%m` without using `%m`, the error string can be printed manually.
> Restore proper error reporting functionality

- docs/index.rst
As of 3.0.0, fish sources `kitty +complete fish` by default.
Relevant fish commit: https://github.com/fish-shell/fish-shell/commit/9c6bd8b1b4fc2069d1e9aed0945e1b9aff0f493d#diff-2974c7d52acf4bc7a0580f6a2cd35fe1
> Update fish completion docs for fish 3.0.0

- kitty/keys.c
When a key is pressed and `mouse_hide_wait` is less than zero, kitty will hide the mouse cursor. When a key is pressed, kitty will also scroll the history to the bottom. Both of these things don't happen if the key being pressed was a modifier key. Both of these things should not happen when Caps Lock is pressed, so this key should be added to the list of modifier keys.
`is_modifier_key()` is not used for anything else.
> Add Caps Lock to the list of modifier keys

- glfw/x11_monitor.c
From upstream: https://github.com/glfw/glfw/commit/e96dc5d2199032d565b55c4177820ab28b1d67c9.
> X11: Assume 96 DPI if RandR monitor size is zero

- glfw/wl_init.c
- glfw/wl_platform.h
From upstream: https://github.com/glfw/glfw/commit/a9f674e719cd663560418de2a7fa1147ce6c6c9b.
> Wayland: Don’t reload the cursor on every pointer motion

- kitty/glfw.c
In bef9490fa8d06a3f2b64a63912b06f7e05604aa8, `unjam_event_loop()` was removed but not the corresponding comment.
> Remove obsolete comment

- glfw/cocoa_init.m
- glfw/cocoa_platform.h
- glfw/glfw.py
- kitty/cocoa_window.m
- kitty/glfw-wrapper.c
- kitty/glfw-wrapper.h
- kitty/glfw.c
GLFW creates the menu bar in the applicationWillFinishLaunching method, while kitty creates it in `create_os_window()`. This patch changes the behaviour to match GLFW.
In practice, without this change, there can be a short time where the menu bar is not fully populated.
> Create macOS menu bar where GLFW creates it

- glfw/cocoa_platform.h
- glfw/glfw.py
- kitty/glfw-wrapper.h
- kitty/glfw.c
`on_application_reopen()` and `intercept_cocoa_fullscreen()` both only have two possible return values and can therefore have a return type of `bool`.
I got this idea because the first function returns `true` and `false` anyways.
> Change return type of two functions

- glfw/cocoa_init.m
This piece of code is not run when the `GLFW_COCOA_MENUBAR` init hint is set to `0`, which kitty does.
This reduces the difference to GLFW upstream a little.
> Comment commented out code back in

- kitty/boss.py
There was a small bug in the code that selects the standard input for the `launch` command, which caused it to choose the wrong case.
> Fix condition in stdin selection for launch

- README.asciidoc
- kitty/cli.py
- setup.py
Since `https://sw.kovidgoyal.net/kitty` redirects to `https://sw.kovidgoyal.net/kitty/`, it would be better to directly use the second URL.
> Change URL to avoid redirect

- docs/faq.rst
The configuration file that's suggested to force a font to
show up as monospace is very helpful, but it appears you may
need to force fontconfig to rebuild the cache in order for the
change to take effect.
> Direct user to rebuild fc-cache in font FAQ

- kitty/desktop.c
Hi there, I was building kitty from source and upon launching the built binary, I encountered the following error when pressing backspace when there's no input in the terminal:
```
Failed to load libcanberra.so, cannot play beep sound, with error: (null)
```
After inspecting kitty/desktop.c, I found a bug in the loading of libcanberra (the wrong variable is used) and fixed it in this pull request.
> Fixed bug in loading libcanberra when falling back on alternative library names

- kitty/constants.py
When calling the completion code, kitty tries to access the config directory and create it if it does not exist. If kitty has no permission to create it, a temporary directory will be created instead. This will fail on a read-only file system because that raises an `OSError` and not a `PermissionError`.
In practice this happens when building kitty on macOS Catalina using Nix because `HOME` is set to `/homeless-shelter` for purity and `/` is a read-only filesystem.
> Fix OSError when failing to create config directory on read-only file system

- kittens/panel/main.py
Opening a panel with `kitty +kitten panel -c <config>` results in no config file loading at all, the same way it happens when an invalid file is given to `kitty -c`.
This PR fixes that.
> fix kitty +kitten panel -c <config> resulting in no config at all

- kitty/child-monitor.c
Since all the time values use `monotonic_t` now, `maximum_wait` is no longer measured in seconds. Instead of replacing seconds with nanoseconds, I removed it because the definition of `monotonic_t` is supposed to be changed easily, in which case this comment would not be accurate again.
> Make comment more accurate

- glfw/wl_init.c
From upstream: https://github.com/glfw/glfw/commit/ef6189f348d7f911afe640e6b817e2e945dc86a1.
> Wayland: Unset the cursor shape on border exit

- glfw/egl_context.c
From upstream: https://github.com/glfw/glfw/commit/9486ec0c0223dc4e5f51a44fdc9c7d28b5a1d059.
The upstream commit mainly changes some cmake stuff, which we don't use and only really adds curly braces to `egl_context.c` (and changes some formatting).
> Add curly braces

- glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/9b6d68ec70da775c4e2bf6481f86117cf9d9f551.
> X11: Fix missing checks for EWMH attention atoms

- glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/0b652a44d2afe593d6eca8a0d586c20555a0497c.
> X11: Fix invalid read when clearing GLFW_FLOATING

- kitty/main.py
On macOS the keyboard shortcuts are visible in the menu bar. When the keyboard shortcut is used, the corresponding menu bar item flashes to indicate which action was just executed.
kitty allows defining multiple keyboard shortcuts for the same action but macOS allows only one, so kitty needs to decide which one should be handled by macOS. Currently it chooses the first keyboard shortcut with only the command key as a modifier key or the first shortcut when there are no shortcuts with only the command key as a modifier.
When a user tries to set their own keyboard shortcut (and doesn't use `clear_all_shortcuts yes`), this won't change the shortcut displayed in the menu bar since the first (default) shortcut with the command key is <kbd>⌘</kbd>+<kbd>n</kbd>.
I think simply choosing the last …
> Change keyboard shortcut selection algorithm for new_os_window on macOS

- kitty/keys.py
Since 9135387cfa141e9ec27271bc41d5b6c43da90197 kitty should not be started with `python3 .` anymore.
> Update comment to remove legacy way of starting kitty

- kitty/keys.h
Since `CIRCUMFLEX` and `^` were removed from `UN_SHIFTED_PRINTABLE` in b2d428618cbb2b6cc316105fe8135f6d523303da by 3a2a16f54ceac0f999fc31957e2653239a9b11b5 and b5229ec73c07dcb5ddbc0727e77f5af0e6adfb53, `generate_key_table()` wasn't yet run again.
> Regenerate key table

- kitty/cocoa_window.m
This call even reliably caused a crash for code I was trying to develop.
> Remove call to release on an automatically memory managed object

- glfw/cocoa_window.m
- glfw/glfw.py
- kitty/cocoa_window.m
- kitty/glfw-wrapper.h
- kitty/glfw.c
- kitty/state.h
Please don't merge this yet. I need to do some cleanup and want to get some feedback first.
`glfwGetCocoaKeyEquivalent()` in `glfw/cocoa_window.m` expects the returned characters to be of type `unichar`, which won't work for all unicode characters because it is defined as `unsigned short` according to https://developer.apple.com/documentation/foundation/unichar?language=objc, which is only guaranteed to be at least 16 bits in size. The code calling this function also expects the encoding to be UTF-16.
When I added the various keys in #1928, I missed these facts. This means, that `glfwGetCocoaKeyEquivalent()` will behave unexpectedly when called with any of the new-ish keys. Luckily this function is currently only used for determining the macOS shortcut for `new_os_window` but I plan on …
> Fix macOS keyboard shortcut encoding

- kitty/cocoa_window.m
`addItemWithTitle:` can be used instead of `initWithTitle:`. It returns an `NSMenuItem`, which removes the need for allocating an `NSMenuItem` manually and releasing it again.
> Simplify some code in kitty/cocoa_window.m

- kitty/cocoa_window.m
When there is no keyboard shortcut for a new OS window, the macOS menu item should still exist, it should just not have a keyboard shortcut.
> Always show the macOS New OS Window menu item

- kitty/cocoa_window.m
Most macOS Apps have a Help menu as the last menu item in the menu bar. They usually have a menu item with the keyboard shortcut <kbd>⌘</kbd>+<kbd>?</kbd>, which shows some kind of help or documentation. I named the menu item "Visit kitty website" and let it open the kitty website as documentation.
macOS also magically adds a search feature to the help menu.
Is hardcoding the URL like this a good idea? Or can I get it from somewhere else?
> Add help menu to macOS menu bar

- kitty/glfw.c
The hints, once set with `glfwWindowHint()`, retain their values until changed again. This means, that the `GLFW_DECORATED` hint only needs to be set once, even on non-macOS.
> Remove duplicate code

- kitty/child-monitor.c
The timeout is 0.25 seconds. Printing 0.25 instead of 0.250000 looks a lot nicer and a resolution of 10 milliseconds should be enough for this warning message anyways.
> Print warning message timeout rounded to two digits after the dot

- kitty/config.py
- kitty/config_data.py
- kitty/fonts.c
- kitty/fonts/render.py
Close #2247
This doesn't look like very much code; but as they say, **reading code is much harder than writing code**, and I had to really understand how Kitty works to write this, so it took a long time. :smile:
> Add `font_feature_settings`

- docs/changelog.rst
- glfw/cocoa_window.m
- glfw/glfw3.h
- glfw/internal.h
- glfw/null_window.c
- glfw/window.c
- glfw/wl_window.c
- glfw/x11_window.c
- kitty/config_data.py
- kitty/glfw-wrapper.c
- kitty/glfw-wrapper.h
- kitty/glfw.c
- kitty/state.c
- kitty/state.h
This makes increments-based resize work for me (on X11).
(Let's discuss before merge, but it makes me a lot happier)
> Implement resize by increment

- glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/aa5e31356178de43d42f43f48914a62c25033f4b.
> X11: Fix BadMatch focusing a window on non-EWMH WM

- kitty/boss.py
- kitty/child.py
- kitty/cli.py
- kitty/conf/utils.py
- kitty/data-types.c
- kitty/main.py
- kitty/remote_control.py
- kitty/session.py
- kitty/shell.py
- kitty/update_check.py
- kitty/utils.py
- logo/make.py
- setup.py
- update-on-ubuntu
According to the text just above https://docs.python.org/3/library/exceptions.html#EnvironmentError, `EnvironmentError` has been an alias of `OSError` since Python 3.3. Replacing it makes the code more consistent since `OSError` is used in other places in the code too.
> Replace all instances of EnvironmentError with OSError

- glfw/wl_window.c
This PR contains a few minor changes to the wayland loop, each in their own commit:
1. Ensure that wl_display_cancel_read is called immediately on error.
2. Ensure that wl_display_cancel_read is only called if wl_display_prepare_read has succeeded.
3. Simplify wl_display_dispatch_pending error handling, as it does not return EAGAIN.
4. Avoid unnecessarily clearing errno before calls to wayland, as errno will be overwritten if an error occurs.
5. Use errno for both calls to abortOnFatalError, instead of errno for one and wl_display_get_error for the other.
> wayland: Minor rework of error handling in handleEvents

- kitty/main.py
`with open(os.ctermid()) as sys.stdin:` should work as expected, right? I tested it and it seems to work fine.
> Use python context managers to open files

- docs/index.rst
- kitty/config_data.py
Hey,
That's a rather important piece of information [you've provided](https://github.com/kovidgoyal/kitty/issues/2258#issuecomment-573272518) in #2258.
I think it's worth documenting 😉
Also, list layouts in the documentation in the order they actually appear to make it less confusing like it was to me 😅
Cheers!
> Document default layouts order

- kitty/config_data.py
- kitty/fonts.c
- kitty/state.c
- kitty/state.h
Close #2252.
This allows users to forcibly disable RTL; since Kitty doesn't support BIDI anyway, this makes selecting RTL substrings more tolerable, but many users may prefer the current behavior, so it's off by default. 
@kovidgoyal called this a "bandaid", and I understand why, but I hope he merges it because I find it useful, and I know that @hseg will too
> Add `force_ltr`

- kitty/blit_fragment.glsl
My very limited knowledge of OpenGL led me to believe, that this line is unnecessary. Is that correct?
What is this shader used for?
> Remove useless code from shader

- docs/changelog.rst
- kitty/gl.c
- kitty/gl.h
- kitty/shaders.c
- kitty/state.c
- kitty/state.h
This commit fixes graphics rendering when more than one OS window is
open, all OS windows are semi-transparent, and multiple windows contain
graphics.
This commit closes #2310.
> Make each OS window have its own framebuffer

- kitty/bgimage_fragment.glsl
- kitty/bgimage_vertex.glsl
- kitty/borders.py
- kitty/child-monitor.c
- kitty/config_data.py
- kitty/data-types.h
- kitty/glfw.c
- kitty/graphics.c
- kitty/graphics.h
- kitty/screen.c
- kitty/shaders.c
- kitty/state.c
- kitty/state.h
- kitty/window.py
This PR closes #163, and builds off my prior work in #2311 and 8020657d8c0a42ce79057b1d9a5db6801c4e4698, and also work by @kovidgoyal to correct my mistakes, which made this possible.
This PR has been tested both on Nvidia's proprietary OpenGL driver, and Mesa, both on Arch Linux. Sorry, I have **no ability** to test on OS X, (which is also an impediment to my work on FontForge, but my friends there test it for me,) but think it should work.
@kovidgoyal asked if I enjoyed the journey. I really did! Never did anything with OpenGL before this. It perhaps folly to take this on as my first OpenGL project, but hopefully users enjoy the result of much trial and error.
> Add `background_image`

- kitty/marks.py
Fixes the exception below that happened for function-markers:
```
File "/usr/bin/../lib/kitty/kitty/boss.py", line 540, in dispatch_special_key
return self.dispatch_action(key_action)
File "/usr/bin/../lib/kitty/kitty/boss.py", line 612, in dispatch_action
passthrough = f(*key_action.args)
File "/usr/bin/../lib/kitty/kitty/window.py", line 615, in toggle_marker
self.screen.set_marker(marker_from_spec(ftype, spec, flags))
File "/usr/bin/../lib/kitty/kitty/marks.py", line 92, in marker_from_spec
return marker_from_function(runpy.run_path(path, run_name='__marker__').marker)
```
> Bugfix exception when executing marker functions

- glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/0c27ed1d0ef36672f0ef28d86bf8e108cc6e379d.
> X11: Fix setting the clipboard string to itself

- kitty/graphics.c
Found with Cppcheck:
```
kitty/graphics.c:263:13: error: Common realloc mistake: 'buf' nulled but not freed upon failure [memleakOnRealloc]
buf = realloc(buf, capacity);
^
```
> Fix memory leak when realloc() fails

- kittens/tui/line_edit.py
Previously, the cursor would end up one character after the last typed
character when pressing end in the unicode input kitten.
> tui line_edit: Set correct cursor position on end

- kitty/complete.py
This will allow adding completions without using `kitty + complete setup zsh | source /dev/stdin` by piping the code into a file named `_kitty` in a directory in `$fpath` instead of piping to `source`. This is especially handy for package managers that package kitty.
See https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org.
The `compdef _kitty kitty` line at the end doesn't seem to have any ill effects when using the completion code in a completion function file. When piping the code to `source` like before, the added line should be interpreted as a comment and be ignored.
> Add #compdef comment to zsh completion

- setup.py
png2icns is used when building kitty with nix because iconutil seems to be closed-source. They currently patch the build system to use png2icns: https://github.com/NixOS/nixpkgs/blob/569d6d0fb11b0d3a26e565c61f3dbef15a5c1348/pkgs/applications/misc/kitty/png2icns.patch. It would be nice if kitty would support using png2icns without patching.
libicns also has an iconutil clone called icnsutil in the source tree but the last release is from 2012, which does not include this utility yet.
I'm printing a warning message because png2icns does not provide the same functionality as iconutil (no retina support). Is this a good way of printing the warning message or is there a better way to do this?
> Add support for png2icns as an alternative to iconutil

- kitty/layout.py
I'm really not sure of what I'm doing here so please double check :)
But it seems that in commit f7eef3f456f7ca38044355b88cd6ffe45cd91061 the `if` statement got "inverted" and in doing so a typo cause the condition to fail.
For reference this is the change (from f7eef3f456f7ca38044355b88cd6ffe45cd91061):
```diff
-            if w is active_window and not draw_active_borders and not w.needs_attention:
-                yield no_borders
-            else:
+            if (w is active_window and draw_active_borders) or w.needs_attention:
yield all_borders
+            else:
+                yield no_borders
```
The `if` initially being `A && !B && !C` it should have been translated to `!A || B || C` when inverted. That's what this fix does.
Fixes #2474.
> fix(window): inactive window border fix

- kittens/hints/main.py
I chose `*` because that's what vim uses for the primary selection, but I'm fine with a different character if you want to chose something else.
> Add an option to hints for copying to the primary selection

- kitty/core_text.m
- kitty/fast_data_types.pyi
- kitty/fonts.c
- kitty/fonts.h
- kitty/fonts/render.py
- kitty/freetype.c
This reads the strikethrough position and thickness from the font so it
is rendered correctly.
This is only implemented for FreeType, not Core Text, because I didn't
find any way to get the info from Core Text, and I don't have a Mac to
test it on either. When using Core Text or when the font doesn't provide
the info, the same approximation as before is used.
> Read strikethrough info from font when using FreeType

- docs/faq.rst
As suggested in #2516, changing "match target" to "font" in the fonts.conf file.
> Changing "match target" to "font"

- glfw/xkb_glfw.c
XKB has various options for using keys to switch the keyboard layout.
When these are set, XKB will return keysyms which are unknown to GLFW,
so kitty will fallback to using a keymap without the options set, which
causes the keys to be interpreted as the original keysyms.
However, when these options are set, kitty shouldn't interpret the keys.
Therefore, check for some specific keysyms and return before translating
to GLFW keysyms.
There may be more keysyms which should be ignored, but as far as I can
see from https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/xkeyboard-config-2.29/symbols/group
these are the ones which can be triggered by XKB options.
Fixes #2519
> Ignore keys for switching keyboard layout

- kitty/layout.py
- kitty/tabs.py
Layout.must_draw_borders = True enforces drawing of a border even
though only a single window is visible. See #2531.
Here how it could be used in the `zoom_toggle.py` kitten in order to indicate that window is zoomed:
```python3
def main(args):
pass
from kitty.layout import Stack
from kittens.tui.handler import result_handler
@result_handler(no_ui=True)
def handle_result(args, answer, target_window_id, boss):
tab = boss.active_tab
if tab is not None:
if tab.current_layout.name == 'stack':
tab.last_used_layout()
else:
try:
Stack.must_draw_borders = True
tab.goto_layout('stack')
finally:
Stack.must_draw_borders = False
```
> Add flag to Layout to enforce drawing a border

- docs/index.rst
The link was pointing to a deprecated `copr`. Let's point it to official Fedora repos! (as copr page suggests anyway)
> Update Fedora link

- docs/kittens/custom.rst
- kitty/fast_data_types.pyi
- kitty/mouse.c
- kitty_tests/keys.py
This allows you to a control a program running in kitty from a kitten
using mouse events. If the program is not receiving mouse events of that
type, it is not sent.
> Add support for sending mouse events from a kitten

- kittens/hints/main.py
This allows you to pass in --word-characters "" which will make hints
only match \w.
> Don't set word_characters to select_by_word_characters when empty string

- glfw/glfw.py
With large objects, use of `-fpic` will fail to link on certain architectures due to size limitations of the global offset table (GOT).  For example, the link stage for glfw-wayland.so fails on sparc64, as below.  Using `-fPIC` avoids these size limitations.
./glfw/osmesa_context.c:73:(.text+0xf2c): relocation truncated to fit: R_SPARC_GOT13 against symbol `_glfw' defined in .bss section in /tmp/glfw-wayland.so.SYvdxr.ltrans0.ltrans.o
/tmp/glfw-wayland.so.SYvdxr.ltrans0.ltrans.o: in function `swapIntervalEGL':
./glfw/egl_context.c:238:(.text+0xf68): relocation truncated to fit: R_SPARC_GOT13 against symbol `_glfw' defined in .bss section in /tmp/glfw-wayland.so.SYvdxr.ltrans0.ltrans.o
/tmp/glfw-wayland.so.SYvdxr.ltrans0.ltrans.o: in function `destroyContextOSMesa': …
> Use -fPIC instead of -fpic

- kitty/graphics.c
`GraphicsManager.image_count` is declared as a `size_t`, so the Python type needs to be the same width.  On 64-bit big-endian architectures, this mismatch was showing up as test failures:
======================================================================
FAIL: test_gr_delete (kitty_tests.graphics.TestGraphics)
----------------------------------------------------------------------
File "/<<PKGBUILDDIR>>/kitty_tests/graphics.py", line 319, in test_gr_delete
self.ae(len(layers(s)), 0), self.ae(s.grman.image_count, 1)
ch = 20
cw = 10
delete = <function TestGraphics.test_gr_delete.<locals>.delete at 0x3ffb7fc38b0>
dx = 0.2
dy = 0.4
layers = <function put_helpers.<locals>.layers at 0x3ffb77709d0>
put_image = <function put_helpers.<locals>.put_image at …
> Use T_PYSSIZET for GraphicsManager.image_count

- docs/kittens/icat.rst
When using icat with tmux we get the following:
```
$ kitty icat ~/Pictures/fc.jpg 
Terminal does not support reporting screen sizes via the TIOCGWINSZ ioctl
```
In #2597 this was confirmed to generally be a limitation of terminal multiplexers and adding support in kitty would add too much maintenance overhead.  We document this for users.
> Add note clarifying icat won't work with tmux [take 2]

- kitty/tab_bar.py
This makes tab separators only drawn between the tabs.
Relates to #2616
> Omit final tab separator

- kittens/icat/main.py
Otherwise we can easily hang when "icat"-ing resources from unreliable websites/webcams, etc.
> Set a default socket timeout when retrieving remote items in icat.

- kitty/tab_bar.py
The documentation for v0.17.4 states this about the `tab_title_template`:
> Note that formatting is done by Python’s string formatting machinery, so you can use, for instance, {layout_name[:2].upper()} to show only the first two letters of the layout name, upper-cased.
However, because the templating uses String `.format`, this generates an error:
```
Invalid tab title template: "{layout_name[:2].upper()}" with error: string indices must be integers
```
If instead we used an f-string, we could fulfill the promise of the docs.
I'm fairly new to Python, so not sure if there is a more direct / safer way to pass a variable to an f-string.
> Use f-string instead of format for tab_title templates

- kitty/config.py
- kitty/marks.py
This PR fixes an issue with multiple simultaneous mark groups defined. The issue exists on a latest Kitty version and on top of the master branch. If I try to define several marks simultaneously in any available approach I got a text colored just by one color and that color just corresponds to a first mark group in the making definition.
**Steps to reproduce:**
1. `echo -e 'WARN\nERROR\nFAIL'`
2. `kitty @ create-marker regex 1 FAIL 2 ERR  3 WARN`
All three words should have different colors but all of them just colored as the `FAIL` word by the color of the first group in the applied marking definition.
**Bellow screenshots demonstrate the issue:**
**With the PR fix:**
**P.S: And thanks for the great project!** :rocket:
> Fixed marks grouping and coloring for simultaneous multi marks definition

- glfw/glfw.py
- kitty/desktop.c
- setup.py
Don't merge this yet.
I'm trying to make the paths to `libEGL.so.1`, `libstartup-notification-1.so` and `libcanberra.so` configurable during build time. This is useful for nix since all paths to libraries are hardcoded in the binary for reproducibility and look like `/nix/store/rcli75fxa9x8raklf19kp0hfcyjc0kfn-libGL-1.2.0/lib/libEGL.so.1`. See https://github.com/NixOS/nixpkgs/blob/b16a5e2847b4e78a29be9fb2d157706f4ca84083/pkgs/applications/misc/kitty/default.nix and the parent directory for how this is done currently.
To change the paths, I want to define preprocessor variables containing a string with the path. I'd like to use the `SPECIAL_SOURCES` dict. Can I move the definition of `SPECIAL_SOURCES` into the function where it is used? I could then pass in the paths as arguments to the …
> Make paths to libraries configurable at build time

- docs/changelog.rst
- kitty/boss.py
The `confirm_os_window_close` parameter set to 1 has no effect on current master branch.
Current implementation works like **"starting from a number allow close without confirmation"** but
I suspect should be **"a minimum allowed to close without confirmation"**.
> Fixed confirm_os_window_close bug introduced in commit 7bf83603c8ad6a

- kitty/boss.py
There is an issue with ability to save scroll buffer from a default less
scroll buffer viewer by just typing relative path to an output file,
because the running less instance inherits cwd from Kitty's cwd
instead of cwd of active window.
How to reproduce:
1. Start Kitty.
2. Go to some place.
3. Press 'kitty_mod+h'
4. Press 's' and you'll see a less prompt like 'log file:'
5. Type a just file name without any path and press Enter then press 'q'
6. See that there is no such file in a current shell directory.
> Fixed issue with a cwd for kitty_mod+h scroll buffer viewer

- glfw/backend_utils.c
- glfw/backend_utils.h
- glfw/wl_window.c
- kitty_tests/glfw.py
This is my attempt at fixing the issue mentioned in the comment.
Where would be a good place to put `utf_8_strndup()`?
Can `title` be NULL? There was a check for it but I don't think `_glfw_strdup()` could handle this situation.
While developing this function, I wrote a little test suite for it and it would be nice to have it in the kitty tests. Maybe not to run it every time by the CI as that seems a little wasteful but as a sort of "extended" test suite to be run manually. There are a few other tests for similar functions that could be written in the future.
> Ensure valid UTF-8 when cutting string

- kitty/child.c
Fix typo: "#ifdef TIOCSTTY" -> "#ifdef TIOCSCTTY"
Include standard header sys/ioctl.h for ioctl(), needed on MacOS.
Include standard header termios.h for TIOCSCTTY.
Fixes this error on spawn of child shell process:
bash: cannot set terminal process group (-1): Inappropriate ioctl for
device
bash: no job control in this shell
Tested on FreeBSD and Linux.
- Fix #2529
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
> Fix child spawn on FreeBSD.

- glfw/wl_window.c
From upstream: https://github.com/glfw/glfw/commit/754b7feaa144b22383457f9c0561adc9ebb24fd7.
1fa66ca45d6234e9a56ecb6616e8af9f9442479d didn't include the changes to `wl_window.c`.
> Wayland: Rename handlers for more unicity

- docs/graphics-protocol.rst
Examples in `Deleting images` section were incorrect.
> Fix incorrect examples in graphic protocol

- glfw/wl_window.c
This is actually a quick bugfix: animated mouse cursors on Wayland currently do not hide when using any nonzero value for `mouse_hide_wait`. They hide for one frame of animation, then immediately reappear. This fixes that.
> Avoid incrementing hidden cursors' images

- kitty/data-types.h
- kitty/keys.c
- kitty/mouse.c
- kitty/state.h
I'm working on a little bug fix. Unfortunately I can't figure out how to get it to compile because I need to pass a pointer to a `Window` to `fake_scroll()` but I can't do that since `Window` is not defined in `kitty/data-types.h`. I can't import `state.h` in `data-types.h` because `state.h` already imports `data-types.h`. I can't put `fake_scroll()` into `kitty/mouse.c` because `send_key_to_child()` is not defined there. Can you please help me find a way to make this work? Maybe making `send_key_to_child()` available in `kitty/mouse.c`?
> Fix fake scroll when scrolling in unfocused kitty window

- glfw/glfw3.h
In 55ad228166bc537e5e6508c2efac0e31bfd6d71b I forgot to replace `GLFW_TRUE` with `true` in a comment.
> Remove GLFW_TRUE in comment

- docs/kittens/custom.rst
- kitty/glfw.c
- kitty/mouse.c
- kitty_tests/keys.py
This adds support for sending the back/forward mouse buttons to terminal applications, makes modifier keys reported in move and drag events and improves how modifier keys are tracked. See the commit messages, which describes these changes in detail.
> Improve mouse event handling

- glfw/cocoa_platform.h
- glfw/egl_context.h
- glfw/internal.h
- glfw/null_platform.h
- glfw/osmesa_context.h
- glfw/wl_platform.h
- glfw/x11_platform.h
From upstream: https://github.com/glfw/glfw/commit/bcb85581896910c7205596cc4eec9b16d8b7e565.
> Remove EGL and OSMesa struct member macros

- glfw/cocoa_window.m
- glfw/egl_context.c
- glfw/egl_context.h
- glfw/glfw3.h
- glfw/init.c
- glfw/internal.h
- glfw/wl_window.c
- glfw/x11_window.c
- kitty/glfw-wrapper.h
From upstream: https://github.com/glfw/glfw/commit/0dea8a4441828311af4c31de8ba798ba330c4755.
I incremented the constants `GLFW_DEBUG_KEYBOARD` and `GLFW_ENABLE_JOYSTICKS` by one. That doesn't cause any problems, right?
> EGL: Add support for EGL_ANGLE_platform_angle

- glfw/wl_window.c
From upstream: https://github.com/glfw/glfw/commit/5f60c22cfa5c3d62e2cb2f281fd057384fc58f54.
> GLFW: Wayland: Fix partial framebuffer size retrieval

- glfw/wl_init.c
From upstream: https://github.com/glfw/glfw/commit/f760b124ca849d99effbedb91fb8d10a828aea00.
This commit does not actually change any behaviour, it merely makes the code style of the two lines more similar to the new upstream code.
> GLFW: Wayland: Fix scroll offsets being inverted

- glfw/cocoa_init.m
- glfw/cocoa_joystick.h
- glfw/cocoa_joystick.m
- glfw/glfw3.h
- glfw/init.c
- glfw/input.c
- glfw/internal.h
- glfw/linux_joystick.c
- glfw/linux_joystick.h
- glfw/null_joystick.c
- glfw/wl_init.c
- glfw/x11_init.c
- glfw/x11_window.c
- kitty/glfw-wrapper.h
- kitty/glfw.c
This PR removes our custom `GLFW_ENABLE_JOYSTICKS` GLFW init hint and replaces it with the new lazy joystick initialisation from upstream.
> GLFW: Make joystick platform code init on demand

- kitty/cocoa_window.m
- kitty/fast_data_types.pyi
- kitty/glfw.c
- kitty/tabs.py
The API used is rather plain, not private or suspicious.  (I did research, though, and AFAICT, private APIs will pass the notary, but Apple threatened that they wouldn't when they first introduced the notary, so ... ??.) 
I'm running this locally, and the window ids are stable and agree with yabai's window numbers (apparently in spite of the vague comment in `windowNumber`'s documentation):
```
jfelice@C02X421DJHD4 src 
$ echo $WINDOWID
20273
jfelice@C02X421DJHD4 src 
$ yabai -m query --windows --window | jq '.id'
20273
```
I chose to reuse the `WINDOWID` variable because it seems like the same purpose and it is possible that some scripts might now work on Mac OS.
Let me know about any code quality issues, and I'll fix them up.
(See #2552 and koekeishiya/yabai#625)
> On Mac OS, set $WINDOWID to OS's window number

- glfw/cocoa_monitor.m
From upstream: https://github.com/glfw/glfw/commit/a2674a903434b7dfc0b0bcc5d0b479da417367ff.
> GLFW: Cocoa: Fix potential leak of CFNumber object

- glfw/cocoa_joystick.m
From upstream: https://github.com/glfw/glfw/commit/0d355379e070d094a6b9e0894f4fa51e00e1364f.
> GLFW: Cocoa: Support some sim page joystick elements

- kitty/constants.py
I think it's useful to get an error message here instead of just returning a path that might not exist.
> Let kitty_exe() raise an error message if kitty could not be found

- glfw/ibus_glfw.c
This is required when the actual dbus is not from ibus but session bus.
This may happen when other run a shim layer for ibus, or ibus is
running with flatpak mode.
> Register to bus when connect to ibus.

- glfw/null_joystick.c
This patch declares _glfwPlatformInitJoysticks() to return bool which
matches its prototype in glfw/internal.h.
Without this patch, kitty is failing to build under FreeBSD with the following error:
```
gcc -MMD -DNDEBUG -D_GLFW_WAYLAND -D_GLFW_BUILD_DLL -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -march=native -fvisibility=hidden -D_FORTIFY_SOURCE=2 -fPIC -flto -fPIC -pthread -I/usr/local/include -I/usr/local/include/libepoll-shim -I/usr/local/include -I/usr/local/include/libepoll-shim -I/usr/local/include -I/usr/local/include/dbus-1.0 -I/usr/local/lib/dbus-1.0/include -c glfw/null_joystick.c -o build/glfw-wayland-null_joystick.c.o
glfw/null_joystick.c:36:5: error: …
```
> Declare _glfwPlatformInitJoysticks() to return bool

- docs/kittens/custom.rst
Since send_mouse_event now uses the same numbers as X11 for buttons
instead of the same numbers as GLFW, it is misleading to use the GLFW
constants. I forgot to change this example in commit 8efe08c4.
> Don't use GLFW buttons in custom kitten example

- kitty/tabs.py
Proposed fix to make move_window_to_top keyboard shortcut work.
> tabs.py::move_window_to_top fix

- glfw/glfw3.h
- kitty/glfw-wrapper.h
From upstream: https://github.com/glfw/glfw/commit/1ed1489831e32337c13fbcbac2c2562ac4163bd3.
> GLFW: Fix typo in GLFWwindowmaximizefun documentation

- kitty/cocoa_window.m
According to the python documentation, `Py_CLEAR()` has no effect when the argument is `NULL`, see https://docs.python.org/3/c-api/refcounting.html#c.Py_CLEAR.
In case you were planning to release a new version in the next couple days, could you please wait til this weekend, when I will have made all the PRs that I would like to include in the next version?
> Remove unnecessary condition

- kitty/launch.py
As said in #2711, here is a PR that describes the limitation of `launch --copy-env` as well as hint at its workaround.
I also added code blocks for `--stdin-source` in a separate commit so that if it is not wanted, it can be reverted easily.
EDIT: I would like to provide an example of using the remote control feature workaround. I will try to make it work for me but if you read this before I commit the example and you have the solution, could you point me toward it ?
> launch documentation improvements

- kitty/boss.py
- kitty/cocoa_window.m
- kitty/fast_data_types.pyi
- kitty/notify.py
This used to be implemented before 4e3c6e52aad41b9deb98d052c806f4a84846b782, when the now deprecated notifications framework was still being used.
Implement it again for feature parity, since my next PR will re-add the old notifications framework.
Note that I don't know how to actually test this, since it apparently requires signing and notarization, which I can't do.
Since this isn't actually used anywhere yet, do you think we should just leave this feature out?
Also, should I implement it in `kitty/notify.py` and in `send_test_notification()` as well?
How do you call `send_test_notification()` when testing? Which command do you use?
> macOS: add ability to show subtitles in notifications

- setup.py
Disabling Link Time Optimization is useful for Nix on Darwin because LTO is broken there and has been for a long time, see https://github.com/NixOS/nixpkgs/pull/19312.
This is currently worked around in the Nix package with a patch that removes the lines that add -flto to the compiler flags.
I also would have found this flag useful in the past, for example for compiling on OpenBSD.
> Add flag to disable LTO

- setup.py
When piping the output of `setup.py` to another program, that program cannot usually deal with escape sequences well. To fix this, output the compilation progress on new lines instead of overwriting the current line.
> Better build system output when stdout is not a tty

- kitty/cocoa_window.m
- setup.py
Please don't merge this yet.
This PR adds the deprecated macOS notification API again, so that notifications work when compiling from source without code signing. It was removed in 4e3c6e52aad41b9deb98d052c806f4a84846b782.
What did you mean by "compile time version detection" in https://github.com/kovidgoyal/kitty/pull/2876#issuecomment-697109685? Simply check if the macOS version is 10.15 (Catalina) or lower and then use the old API? But I think it would be useful to be able to use this API as long as it's still only deprecated and not removed. Do you have an idea, how this could be done best?
> macOS: re-add deprecated notification API

- .github/workflows/ci.py
There was a warning when the CI executed the "macOS Brew" job:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```
To fix this, use pip3 instead of pip.
> Use pip3 instead of pip for CI

- kitty/update_check.py
Without this fix the file with the list of notifications looks like this:
```
0.19.0,1601899026.4373078,<built-in method count of Notification object at 0x7f8c582193b0>
```
which ends up notifying about a new version all the time.
> Fix repeated version notifications

- setup.py
The Python version is already checked at the top of the file. That check was added in 81a58186c6fae2de7bb4d7c7a3dc1a418d2b3d03.
> Remove outdated Python version check

- docs/kittens/hyperlinked_grep.rst
It's called `hyperlinked_grep` not `hyperlink_grep`.
> Fix wrong kittenname in documentation

- kittens/hints/main.py
- kitty_tests/hints.py
This PR adds a new type for the hints kitten: IP.
This type matches both v4 and v6 IPs. Subnet mask notation (`ip/32`) is not supported, but could easily be added.
This PR contains two commits:
The first commit adds a very simple regex to match IPv4/IPv6 **with no validation** and tests that cover matching valid and invalid IPs.
The second commit adds validation by adding a postprocessor for the `ip` type, and a new exception called `InvalidMatch`, which can be raised by the postprocessor to ignore a given match. This postprocessor for `ip` makes use of the Python standard library's `ipaddress` module to validate the matched IPs. This commit also improves the previous test by adding a few testcases of invalid matches being ignored.
The bodies of the commit contain this information as …
> Kitten hints: Add new IP (matches v4 and v6) type

- kitty/screen.c
When selecting text by dragging upwards, the "end" of the selection is above the "start". This causes the `selection_has_screen_line()` to never return `true` in this case.
In practice this bug causes the selection to not be cleared when the screen contents under the selection change if it was made by dragging upwards.
Please double-check that `s->start_scrolled_by` and `s->end_scrolled_by` don't need to be subtracted from `top` and `bottom` instead as I'm not sure.
> Fix upwards selection not being cleared when lines change

- kitty/macos_process_info.c
This is a copy & paste error. This bug was introduced in 72e2307c16e777e24d35e7c6c72788f5e2f26850 in Jul 2018.
> Fix double free and memory leak

- kitty/glfw.c
`create_os_window()` calls `get_window_content_scale()` without initializing the `xscale` and `yscale` variables. Instead of initializing them everywhere, where this function is called, just do it once in the function itself.
> Fix potential garbage pointer dereference

- setup.py
For some reason it can happen that the `UserNotifications` framework exists but the `UserNotifications/UserNotifications.h` header doesn't.
The temporary directory is needed because clang would try to write to `/dev/null.d`, which would obviously fail.
Closes #3042.
> macOS: Fix detection for notification API

- setup.py
While developing the previous PR (https://github.com/kovidgoyal/kitty/pull/3043), I was using more compiler command line arguments, one of which was `-MMD`. This caused the .d file to be created. Without this argument, there is no need to create a temporary directory.
> Creating a temporary directory is not actually required

- kitty/cocoa_window.m
The error message was: "Method accepting NSError** should have a non-void return value to indicate whether or not an error occurred".
> Fix Clang Static Analyzer complaining about Apple coding conventions

- glfw/wl_window.c
On Wayland, some compositors refuse to implement SSDs in which case we draw
primitive CSDs.  However, the destructors were called in the wrong order,
leading to a dereference of an already freed object.
> wl: Fix destroying CSDs in correct order (#3051)

- docs/build.rst
- setup.py
- shell.nix
This makes it possible to execute `nix-shell` to create the correct environment to build kitty. Use `nix-shell --pure` to eliminate most of the influence of the outside system, e.g. globally installed packages.
This works on NixOS and any Linux or macOS system with the Nix package manager installed.
The build inputs are split into `buildInputs`, `nativeBuildInputs`, `propagatedBuildInputs` and `checkInputs` so it closely resembles https://github.com/NixOS/nixpkgs/blob/2bb3a9da24ca60d9f5bed69f679a1ec50dbdf997/pkgs/applications/terminal-emulators/kitty/default.nix. This makes it easy to port changes between the two files.
I tested that it works correctly with NixOS (both X11 and Wayland), Arch Linux with Nix installed (just X11) and macOS of course.
I first created this file a couple months …
> Add shell.nix

- kitty/cocoa_window.m
The function `schedule_notification()` for the new notification API also does not `release` similar objects.
> Fix incorrect decrement of the reference counts of objects

- kitty/fonts/box_drawing.py
The scheme used in draw_sextant works well enough, but the
feed was broken. 21 and 42 need to be skipped, not 20 and
40. Without this change, the following glyphs are broken:
U+1FB13 BLOCK SEXTANT-35 🬓 renders as LEFT HALF
U+1FB26 BLOCK SEXTANT-46 🬦 renders as SEXTANT-146
U+1FB27 BLOCK SEXTANT-146 🬧 renders as RIGHT HALF
With this change, the entirety of the sextant block works
correctly. Found debugging the Notcurses sextant blitter:
https://github.com/dankamongmen/notcurses/issues/1112
Closes #3106
> Sextants: fix arithmetic mistake that broke 🬓, 🬦, 🬧

- kitty/screen.c
- kitty_tests/screen.py
There are two user-visible changes in here:
1. If a scroll region is set such that there is a bottom margin and no
top margin, scrolling the region forward used to discard the top
lines. Now those lines are appended to the scrollback.
```shell
printf '\033[H\033[J\033[3J\033[0;5r' && seq 100
```
This command used to result in an empty scrollback. Now it contains
the numbers 1-96.
2. If a scroll region is set such that there is a top margin and no bottom
margin, scrolling the region forward used to append the top lines to
the scrollback. Now these lines are discarded.
```shell
printf '\033[H\033[J\033[3J\033[2;24r' && seq 100
```
This command used to populate scrollback with the numbers 2-78. Now
the scrollback is empty. The numbers on the screen are the same as
before: 1 and 79-100. …
> Change the flow of lines from the scroll region to the scrollback

- kitty/config_data.py
- kitty/mouse.c
- kitty/state.c
- kitty/state.h
Enabled by default add new option `detect_urls` that will allow you
contorl if kitty should detect URLs under the mouse cursor.  If disabled
the URLs are still clickable with open_url_modifiers.
In the almost the same spirt of #1828 but doesn't change current
funcationalty and makes the user opt. in.
> Add new option `detect_urls` to check for URLs under the mouse cursor

- kitty/config_data.py
- kitty/tabs.py
Add tab_switch_strategy option 'right' to switch to the tab to the right of the closed tab, as in Firefox, Safari, and Chrome.
> Add tab_switch_strategy option 'right'

- docs/faq.rst
In fontconfig version `2:2.13.91+48+gfcb0420-2` from the Arch Linux extra repository (which is what I am using), the target must be set to `scan` for the `spacing` value to be successfully overwritten. I am unsure about other versions.
> Update example fontconfig

- kitty/config.py
- kitty/config_data.py
- kitty/fast_data_types.pyi
- kitty/fontconfig.c
- kitty/fonts/__init__.py
- kitty/fonts/core_text.py
- kitty/fonts/fontconfig.py
- kitty/fonts/render.py
As discussed here: https://github.com/kovidgoyal/kitty/pull/2248
> Support default font_features from fontconfig

- kitty/terminfo.py
Should not hurt anything, it's just documenting kitty's existing VT220 compatibility.
I had some third-party bash scripts fail, since they were using
`echo -ne "$(tput u7)"`
vs a direct
`echo -ne '\e[6n'`
¯\\\_(ツ)\_/¯
I got the terminfo strings from:
```
$ infocmp -q1 xterm | grep -oP '(?<=\t)u[0-9]=.+'
u6=\E[%i%d;%dR,
u7=\E[6n,
u8=\E[?%[;0123456789]c,
u9=\E[c,
```
> Generate u[6789] with terminfo.py

- kittens/diff/config_data.py
- kitty/config_data.py
Allow diff kitten to not override foreground color for selections.
Related #1358
> kitten/diff: allow specifying none color for select_fg

- kittens/unicode_input/main.py
The bases for the index were being decoded as base 16, despite being displayed as base 36 (0-9, a-z). This fix makes it so typing 'search string .index' returns the unicode char at the expected index, based on what is displayed by the program. The previous behavior was that to enter the symbol that is displayed at index 18, you would actually have to type `.2c`, since `18 base 36` = `2c base 16`. This fix makes it so to type the symbol at index 18, you type `.18`, which seems more reasonable
It also slightly changes the behavior. Before, only the selected result would appear. For example, musical note `musical note .18` would only show a single result (with index 0 always), since there was only a single result at index 18. Now, searching by index doesn't remove codepoints/results, it …
> Fixes Incorrect Index Behavior in Unicode Name Selector

- kitty/cocoa_window.m
I often find that I accidentally hit Cmd-W when coding, and accidentally close the window, sometimes losing changes, and often just having to deal with the pain of recovering swap files. MacOS allows you to overwrite the shortcuts for an app, but it seems like it's only if the command is explicitly in one of the menus.
For example, I am able to create a new shortcut for "Quit kitty" so that I don't accidentally quit the entire application, but I am not able to do it for "Close" since there is not a dedicated menu option for it.
Other applications I have looked at have it in the "Window" menu tab and call it "Close", so the UX will be similar enough to other MacOS applications.
> Add MacOS menu option to close window

- setup.py
just a small change- on current arm macOS, it seems that python's `platform.processor()` lies. This should make the build work correctly on apple silicon.
I added another conditional because i'm assuming is_arm isn't just for apple, and assuming other platforms behave better.
```
[00:04:03][pjjw@loon:~/src/kitty(master)]$ file /usr/bin/python3
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):	Mach-O 64-bit executable arm64e
[00:04:29][pjjw@loon:~/src/kitty(master)]$ arch -arm64e /usr/bin/python3
Python 3.8.2 (default, Nov  4 2020, 21:23:28) 
[Clang 12.0.0 (clang-1200.0.32.28)] …
```
> Make is_arm predicate work on macos

- kitty/config.py
[Mapping a key](https://sw.kovidgoyal.net/kitty/marks.html#creating-markers-dynamically) to create marks dynamically, and attempting to create a mark such as `text 1 'a b'` results in an error: 
This PR allows quoted marks to be created from `map` keybindings :
> Allow quoted args to toggle_marker

- kitty/boss.py
This change allows a shortcut bound to `detach_window ask` to be cancelled—similar to how `detach_tab ask` is cancellable.
> Allow cancellation of "detach_window ask"

- docs/build.rst
I needed to install these to get `make` to work on a clean checkout. I think they should be in this list, although the error message from `make` is certainly plenty clear.
> Add two more build-time dependencies to the docs

- kitty/config_data.py
- kitty/tab_bar.py
I added options for powerline tab_bar_style to not just have the default angled symbol.
The three options are angled, slanted, and rounded.
I've attached some screenshots using the following config:
include ayu.conf
background_opacity 0.85
enable_audio_bell no
font_family     MesloLGS NF
tab_bar_style           powerline
#tab_powerline_style     angled
#tab_powerline_style     slanted
#tab_powerline_style     round
tab_bar_edge            top
active_tab_foreground   #3D424D
active_tab_background   #39BAE6
active_tab_font_style   bold-italic
inactive_tab_foreground #B3B1AD
inactive_tab_background #3D424D
inactive_tab_font_style normal
> Made powerline tab_bar_style have different display options

- docs/graphics-protocol.rst
Clarify that RFC1950-style zlib-wrapped deflate (as opposed to RFC1951-style raw deflate) payloads are sent in the graphics protocol, and that base64 encoding follows compression (implied by remarks elsewhere, but go ahead and make it explicit here).
BTW, I'd consider a new flag to indicate that base64 encoding is not being used. You already provide a means to detect support for the graphics protocol; if I've verified that, we pretty much know I can handle arbitrary characters, right? Maybe I'm missing something.
Overall, I like this protocol much, much more than Sixel, especially the attention paid to the z-axis.
> Add some notes to graphics protocol docs

- kitty/config_data.py
- kitty/history.c
- kitty/line-buf.c
- kitty/lineops.h
- kitty/screen.c
- kitty/state.c
- kitty/state.h
- kitty_tests/__init__.py
- kitty_tests/screen.py
This is the beginning of a change to optionally fill the buffer with lines from the history when enlarging a window.
References #1206, #1972, #2398, #2531
This PR is unfinished, and it may take me some time to do so because I am unfamiliar with the codebase and out-of-practice with C. Any advice on the remaining work would be appreciated.
> Add `scrollback_fill_enlarged_window` option

- docs/binary.rst
Added `/` at the applications, otherwise applications may be considered a file if the directory is not present. The addition of `/` also ensures user knows that he/she needs to create new directory if it is not present.
> Fix installation docs

- kitty/fonts/box_drawing.py
Firstly, I want to thank you @kovidgoyal for your patience and help; I really appreciate all the work you do on Kitty! ❤️
Given the discussion at https://github.com/kovidgoyal/kitty/issues/3409#issuecomment-803767623...
>You basically want to change the values returned by the lower x() function by a delta. Play with it and see what happens, though in my testing, the current code is optimal across all cell sizes.
I agree that the rectircle equation is correct/perfect, but I found that the cause of the seemingly-misaligned corners (especially on the right side) is due to subpixel rendering when the `x()` functions return certain floats / decimals on certain displays.  I found that applying `math.floor()` to the left quadrant, and `math.ceil()` to the right quadrant prevents subpixel …
> Prevent subpixel rendering on box drawn corners

- glfw/cocoa_window.m
- glfw/glfw.py
- kitty/cocoa_window.m
Hi there 👋 
I was missing the "Secure Keyboard Entry" functionality, so here you go 🚀 
Mostly based/copied from https://github.com/gnachman/iTerm2/blob/master/sources/iTermSecureKeyboardEntryController.m
Toggled by `Command-Option-S`
> [macos] - Add "Secure Keyboard Entry" menu item

- docs/graphics-protocol.rst
Signed-off-by: Henner Zeller <h.zeller@acm.org>
> Fix timg link (underscore was missing).

- kittens/hints/main.py
This fixes an `UnboundLocalError` when opening a hyperlink with the binding `kitten hints --type hyperlink --program default`.
> Fix unbound variable in hyperlink handling

- glfw/cocoa_window.m
The constants `NSControlStateValueOn`, `NSControlStateValueOff` and `NSControlStateValueMixed` are only available for macOS 10.13 or above according to https://developer.apple.com/documentation/appkit/nscontrolstatevalueon?language=objc.
Without this commit, compilation fails with this message:
```
glfw/cocoa_window.m:1537:28: error: use of undeclared identifier 'NSControlStateValueOn'
item.state = NSControlStateValueOn;
^
glfw/cocoa_window.m:1539:28: error: use of undeclared identifier 'NSControlStateValueMixed'
item.state = NSControlStateValueMixed;
^
glfw/cocoa_window.m:1542:47: error: use of undeclared identifier 'NSControlStateValueOn'
item.state = controller.isDesired ? NSControlStateValueOn : NSControlStateValueOff;
^
glfw/cocoa_window.m:1542:71: error: use of undeclared identifier …
```
> Fix compilation on macOS 10.12

- glfw/xkb_glfw.c
Fix #3514 .
Some day, someone will map one of their shift keys to control, or worse, caps lock to shift, and then we won't be able to do anything about it.
> Give shift, control and caps lock precedence over other modifiers

- logo/attribution.txt
The Big Sur template includes a CC BY 4.0 license, hence the attribution with the details of the change.
Add attribution for the new logo in https://github.com/kovidgoyal/kitty/pull/3548.
I hope this looks okay?
> chore(logo): add missing attribution

- kitty/cocoa_window.m
The spotlight search in the "Help" menu of the menu bar did not appear when the system language is set to a language other than English. macOS magically adds the search box when the text in that menu matches the translation of "Help" in the system language. On my German system for example replacing "Help" with "Hilfe" will make the search box appear again. This is however not a good solution for kitty as it would require implementing localization support for all languages. Removing `CFBundleAllowMixedLocalizations=True` from `setup.py` also brings back the search box but that may break the locale again. The line was added in  8818b5d8df686c0e340ef3d15a069bf54082d112 to fix an issue related to https://github.com/kovidgoyal/kitty/issues/1233.
Luckily I found a seemingly undocumented …
> macOS: fix spotlight search in help menu not working on some machines

- kitty/boss.py
subprocess.Popen inherits the current environment if you pass env=None,
but only sets the environment you pass when you pass something else.
This causes an issue with using launch with --stdin-source and
--type=background, e.g. that DISPLAY is not set so you can't launch
graphical processes. Therefore, we have to include os.environ when we
pass an env to Popen.
Fixes #3602
> When running a background process, always inherit env

- kitty/fonts/render.py
Fixed/Improved rendering of curly underlines on HiDPI (i.e. Retina) displays.
I took the existing algorithm for the anti-aliased line (Xiaolin Wu) to calculate an upper & lower bound and applied a solid fill in between. This way the amplitude & weight of the undercurl is correctly scaled for HiDPI displays. 
Feedback welcome :)
- Issue: Curly underline is thinner than normal and appears flatter (less curly)
- Change: Undercurl has correct thickness and curly-ness :)
> Improve undercurl rendering for HiDPI displays

- kitty/cocoa_window.m
Most apps on macOS have the menu items for opening and closing tabs and windows in the "File" menu. Since this doesn't really apply to Terminal emulators, both Terminal.app and iTerm2 have them in the "Shell" menu instead.
This change makes the menu bar of kitty more consistent with these applications.
I also changed the case of "New OS window" to "New OS Window" for consistency.
> macOS: move menu bar items for opening and closing OS windows and tabs to new menu

- kitty/child-monitor.c
- kitty/cocoa_window.m
- kitty/main.py
- kitty/state.h
As promised in #3647.
Please double-check that I made the changes in exactly the right places, not in too few places and not in too many. I basically just searched the code base for an already existing shortcut and then replicated the appropriate looking code for the new shortcuts.
Should I sort the shortcuts in the code into a particular order or just append to the end like I did now?
I successfully tested this change.
> macOS: add menu items for new_window and close_window

- kitty/rgb.py
- kitty/tab_bar.py
This change makes it so that when using powerline-style tab bars, and
if the `tab_bar_background`, `inactive_tab_background` and
`inactive_tab_foreground` are all different, the separator between
inactive tabs uses the less contrasting color between the inactive
foreground, and the tab bar background.
This fixes #3664.
> Use less contrasting color for powerline alt separator

- kitty/options/definition.py
I was wondering what the syntax was to set `cv93=3` as font feature (different `%` sign for Iosevka) - so I ended up digging in the source and finding the harfbuzz docs describing the format.
> doc: Link to harfbuzz font feature format

- kitty/core_text.m
- kitty/freetype.c
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/to-c.h
- kitty/options/types.py
- kitty/options/utils.py
- kitty/state.h
Add option `adjust_baseline` to adjust the baseline position on macOS
Fixes #3728
> Add option `adjust_baseline` to adjust the baseline position on macOS

- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/to-c.h
- kitty/options/types.py
- kitty/state.h
- kitty/unicode-data.h
This option, like select_by_word_characters, is a set of characters, but
for which to *exclude* from URL parsing. See
https://github.com/kovidgoyal/kitty/issues/3688#issuecomment-862711148.
> Add `url_excluded_characters` option to exclude characters from URLs.

- kittens/hyperlinked_grep/main.py
I want to start using the `hyperlinked_grep` kitten, but it currently ignores the context options, which I use frequently. Some sample expected output:
```
$ rg -C 1 'write_hyperlink' kittens
kittens/hyperlinked_grep/main.py
14-
15:def write_hyperlink(write: Callable[[bytes], None], url: bytes, line: bytes, frag: bytes = b'') -> None:
16-    text = b'\033]8;;' + url
--
47-                if m is not None:
48:                    write_hyperlink(write, in_result, line, frag=m.group(1))
49-                else:
--
54-                    in_result = b'file://' + hostname + path
55:                    write_hyperlink(write, in_result, line)
56-                else:
```
But the kitten does not output context:
```
$ kitty +kitten hyperlinked_grep -C 1 'write_hyperlink' kittens
15:def …
```
> Make hyperlinked_grep kitten respect context options

- docs/kittens/hints.rst
No idea, if I correctly referenced this part of the documentation `https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.kitten_alias` with:
```
:ref:`kitten_alias` 
```
> mention kitten_alias in hits documentation

- kitty/guess_mime_type.py
Currently, one can't assign a custom action to folders in hyperlinks because they aren't associated a MIME type. This is because python's `mimetypes` library doesn't include that mime type. You also can't add this in the `.config/kitty/mime.types` file because folders have no extension.
This way any directories automatically get the right MIME type.
> Directories should have MIME type inode/directory.

- kitty/fonts/box_drawing.py
Fix U+1FB3F so that it matches its mirrored glyph U+1FB4A.
before:
after:
> U+1fb3f: upper middle left to lower right 🭊🬿

- kitty/options/definition.py
The previous wording about "system-wide" slightly confused a friend of mine who's starting with kitty, so I made the description a bit more precise (to my eyes). See what you think.
> clarify the text for the "editor" config variable slightly

- shell.nix
NOTE - I know very very little about nix. But, when I tried to do `nix shell`, I got an error that `stdenv.lib.getLib` did not exist. It _seems_ like this is the right fix (and it runs without errors!) but please verify.
> Fix shell.nix error with stdenv.lib.getLib

- docs/kittens/hints.rst
Full command line option documentation no longer comes after this note.
> docs: typo in hint.rst, adaption to new layout

- shell.nix
As promised in https://github.com/kovidgoyal/kitty/commit/f787a377c3a32563cef19c603ff0ec76eedcfb46#commitcomment-53677490, I finished packaging all the new dependencies for building the documentation a few days ago. They are now in the unstable channel.
Sorry that it took so long, I had some trouble packaging furo because I did not realise that furo needs an additional build step running gulp to build some CSS and JavaScript files when fetching directly from GitHub. I'm now just using the version from PyPI.
I also made a few other changes, most notably renaming pkgconfig to pkg-config since it was renamed in Nixpkgs as well.
> shell.nix: add new dependencies for building the documentation

- docs/glossary.rst
- docs/keyboard-protocol.rst
- glfw/xkb_glfw.c
Pull request 3430 created hyper and meta for X11, but could not support Wayland since xkbcommon does not provide a way to map virtual modifiers to real modifiers. This patch identifies modifiers for the common case of each mapped modifier generated by its own single key. If such modifiers are not found, it falls back to the current static mapping; the current static mapping does not support meta and hyper. Tested with a wayland session on Plasma Wayland desktop.
Example of supported xkb modifier maps with normal key mapping:
modifier_map Shift  { Shift_L, Shift_R };
modifier_map Lock   { Caps_Lock };
modifier_map Control{ Control_L, Control_R };
modifier_map Mod1   { Meta_L };
modifier_map Mod2   { Alt_L };
modifier_map Mod3   { Hyper_L };
modifier_map Mod4   { Super_L, Super_R };
Example …
> Heuristic to find hyper and meta on wayland

- docs/build.rst
I faced the same issue since I don't have python from homebrew.
I hope this helps future attempts to discover a solution more quickly.
> Add linker fail build notes for macos

- kitty/lineops.h
Without this, Clang would complain:
```
In file included from kitty/fonts.c:9:
In file included from kitty/fonts.h:9:
kitty/lineops.h:67:29: error: suggest braces around initialization of subobject
[-Werror,-Wmissing-braces]
const CellAttrs zero = {0};
^
{}
```
Please check, that this is actually the correct fix.
> Fix Clang warning

- kittens/icat/main.py
Currently, if icat is invoked with stdin closed, it will throw `AttributeError: 'NoneType' object has no attribute 'isatty'`.
This happens even if `--stdin=no` is given at command line. Try for instance in bash:
```bash
kitty +kitten icat --stdin=no <image_file> <&-
```
This PR fixes it so:
- if `--stdin=no` is given, `sys.stdin` is not even queried
- if `--stdin=detect` is given and `sys.stdin` is None, it will behave as if `--stdin=no` was given
> icat: fix exception thrown if stdin is None

- shell.nix
The dependency on librsync was introduced in f0fab80f5b9dec2c8eafc995fb9bdd7818bcb2ce.
> shell.nix: add dependency on librsync

- glfw/ibus_glfw.c
fcitx5 works fine with kitty, except that when you restart fcitx5, kitty stop working with fcitx5, because the dbus_connection_get_is_connected(ibus->conn) in #check_connection is always true when you use fcitx5.
this patch add a dbus name owner changed detection to detect the online status of ibus, in case the ibus backend uses the session bus, like fcitx5.
> ibus's dbus name owner changed detection

- glfw/ibus_glfw.c
- glfw/xkb_glfw.c
- glfw/xkb_glfw.h
The ForwardKeyEvent ibus signal is used to maintain ordering between CommitText events and non-IME key events.
The ordering is important for Korean IMEs, where it automatically commits text whenever a character is fully composed. This is different from Chinese/Japanese IMEs, where user manually presses a key to commit each word.
Without this patch, kitty can't handle non-IME key events when used with ibus-hangul, which utilizes ForwardKeyEvent signal.
Without ForwardKeyEvent:
```
key | sequence of events from application's view
r   | UpdatePreeditText 'ㄱ'
k   | UpdatePreeditText '가'
1   | (receives the reply to ProcessKeyEvent call: "native_key: 0x31 release: 0 handled: 0")
| -> UpdatePreeditText ''
| -> CommitText '가'
```
Application receives "1가", which is incorrect.
With …
> ibus: Add support for ForwardKeyEvent signal

- kitty/data-types.c
- kitty/debug_config.py
- kitty/fast_data_types.pyi
- kitty/utmp.c
- kitty_tests/utmp.py
Currently, in the debug_config page, the issue file looks really ugly because escape codes are not evaluated properly. For example, my issue looks like this:
The double backslashes are particularly bothersome.
Instead, since it's not that complicated to evaluate an issue file, just do that.
Note: this PR introduces another C method that is interfaced with from Python. I would appreciate if you took a look at that and made sure all was well with reference counting, GIL, and that kind of thing as I don't have much experience there.
> Properly evaluate /etc/issue placeholders

- kitty/bgimage_vertex.glsl
- kitty/boss.py
- kitty/data-types.h
- kitty/fast_data_types.pyi
- kitty/graphics.h
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/to-c.h
- kitty/options/types.py
- kitty/rc/set_background_image.py
- kitty/shaders.c
- kitty/state.c
- kitty/state.h
This PR adds two new options: `background_image_anchor` and `background_image_layout clamped`.
We already have a nice option called `background_image_layout`. But there are situations where `tiled` and `scaled` are not enough. Let's take an example:
I want to show a cute kitty on the bottom edge of the screen, so I created a background image that matches the size of my window. Looks like the problem has been solved.
But once I change the size of the window, everything is messed up.
This occurred because the size of the image is synchronized with the size of the window. 
Since I don't want to squash my kitty, I changed `background_image_layout` to `tiled`, and created a new background image with a large padding to align it with size of the window.
However, this still did not solve the …
> Add `background_image_anchor`

- kitty/window.py
When the cursor is not on the screen, the cursor position should not be reported to the scrollback pager.
https://github.com/kovidgoyal/kitty/issues/3948#issuecomment-954886836
> Do not report cursor position when the cursor is scrolled off the screen

- kitty/cli.py
- kitty/main.py
Make sure kitty is first in the PATH and not repeatedly added when it already exists
After setting `env PATH=/path:$PATH`, the kitty path does not stay first, so the executed version of kitty may be incorrect. Also, the added path still exists when there is already a corresponding kitty in the new env PATH.
```shell
PATH=/usr/bin:/bin:/usr/sbin:/sbin kitty/launcher/kitty --config=NONE -o 'map f1 show_kitty_env_vars' sh -c 'printenv PATH;read'
```
```shell
mkdir -p /tmp/kitty/bin
ln -s $PWD/kitty/launcher/kitty /tmp/kitty/bin/
PATH=/usr/bin:/bin:/usr/sbin:/sbin  kitty/launcher/kitty --config=NONE -o 'env=PATH=/tmp/kitty/bin:$PATH' -o 'map f1 show_kitty_env_vars' sh -c 'printenv PATH;read'
/tmp/kitty/bin:/path/to/kitty/launcher/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
```
This …
> Make sure kitty is first in the PATH and not repeatedly added when it already exists

- kitty_tests/file_transmission.py
Commit 85cea78b3c157a3662f0aeb629c7a23fe3d783e7 missed a couple instances where the mtime was not a multiple of 1µs.
See https://github.com/kovidgoyal/kitty/issues/4175.
> Don't rely on nanosecond resolution when testing mtime transmission

- kitty/boss.py
- kitty/rc/set_colors.py
When the file specified in the set colors parameter does not exist, using shortcuts to execute set_colors does not prompt an overlay error message and the keystroke is output to the program (e.g. shell).
The exception message is output to the kitty process stderr.
```shell
kitty -o 'map f1 set_colors invalid'
```
This PR provides friendly information for file non-existence exception and displays an overlay message prompt on errors. Users can also see better error messages when executing in the kitty shell.
> Handle set colors exceptions

- kitty/colors.c
- kitty/fast_data_types.pyi
- kitty/rc/get_colors.py
- kitty/window.py
Some colors can be set to none.
Everything works fine when using `set-colors --configured` and `get-colors --configured`.
However, after setting the current window color to none, get-colors still returns the color, with a value of `#000000` .
```shell
$ kitty @ set-colors selection_background=none
$ kitty @ get-colors
...
selection_background    #000000
...
```
This PR adds None type to current_colors.
Returns none correctly when the color is explicitly set to none.
The value will be updated or removed when get-colors is called.
> When the color is set to none get-colors should not return a color value

- kitty/cocoa_window.m
- kitty/fonts/core_text.py
- kitty/options/definition.py
Capitalize the menu item and slightly adjusted the position of the Service menu item according to the convention.
Make them consistent with other menu items.
Add a note on the priority of bold fonts in the document.
Also I found that in the generated kitty.conf, the valid values in the comments are not easily distinguishable from the normal text. Would you be willing to leave backquotes to specifically indicate the values that can be set?
I also found that ``` :link:`title <url>` ``` is forcing line breaks in kitty.conf if the URL is too long, making the URL not recognized by mouseover and certainly not by kitten hints. I don't have a good idea for now and it doesn't matter, so I'll leave it like that.
> macOS menu and docs minor tweaks

- kitty/options/definition.py
Update the documentation to be more explicit about the scope of confirm_os_window_close.
> Clarify the scope of confirm_os_window_close in effect

- docs/shell-integration.rst
- kitty/data-types.h
- kitty/screen.c
- kitty/shell.py
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
- shell-integration/kitty.bash
Mark different prompts with a binary mark.
This allows kitty to distinguish between different prompts when performing scroll to prompt, and to scroll to the exact position.
Please review if it is appropriate, thank you.
The kitty shell, fish and bash integration script has been updated and works well.
However, I don't know how to implement it in zsh and need help.
This issue was previously mentioned in #4166
> Make scroll to prompt action perform better positioning

- docs/shell-integration.rst
Add fish-related instructions to the shell integration documentation.
A brief description of how it works, and how the user should configure it manually.
> Add how the fish shell integration works and how to configure it manually

- docs/changelog.rst
- kitty/boss.py
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/types.py
- kitty/options/utils.py
Similar to the hints custom alphabet feature, allows the user to configure the numeric and alphabetic order for visual window select.
Users can select windows using a more convenient sequence of keys that they can press, especially when there are many windows.
> Allows to configure the characters for visual window select

- kitty/conf/types.py
- kitty/options/definition.py
- kitty/options/utils.py
I've noticed that many macOS shortcuts are missing from the commented config.
This PR adds all shortcuts to the commented config file.
Users can learn from the default config file and use the shortcuts, or change them as needed.
Also added abbreviated name for macOS Option keys `opt` and unified the use of abbreviated names, and the ordering of modifier keys `ctrl+shift+alt/opt+cmd`.
Please review if it is appropriate, thank you.
> Add default shortcuts to the commented config, and unify the modifier key abbrs and ordering

- kitty/screen.c
Without this, the VIM banner might not be properly cleared when overlay text is active.
Repro:
1. Switch to Korean IM (to trigger screen updates while overlay text is active)
2. Run `nvim`(https://neovim.io/) (note that nvim clears banner after first text input while original vim clears banner when user switches to insert mode, so only nvim triggers  the bug)
3. Check that the VIM banner is shown.
4. Press r, k, s, and then k. Pressing k commits a text(가) with overlay text(나) still active, and triggers the bug. The VIM banner needs to be cleared, but some characters are not cleared.
When nvim move cursor & issues CSI ECH to clear the banner lines, kitty only clears the overlay text and not the actual text backed up in `Screen.overlay_line`. When kitty later deactivates the overlay line(to …
> Also move overlay line for CSI ECH,DCH

- docs/build.rst
Changes
- Reformat build-time dependency list for readability
- Add build-time package dep of librsync-dev
Tested locally by building docs and verifying links in browser.
> Improve doc on building from source

- docs/shell-integration.rst
Also add additional shortcut binding instructions for jumping back to the last jump position.
Regarding the `this` documented in the documentation. Do you think the mappable action needs to be renamed? The current name is `mouse_select_cmd_output`.
Also I found that when mouse_map is bound to an invalid action, it does not output an error message in stderr when loading and verifying the configuration file.
> Docs: scrolling to the last jumped position

- docs/shell-integration.rst
- kitty/fast_data_types.pyi
- kitty/mouse.c
- kitty/options/definition.py
- kitty/options/types.py
- kitty/screen.c
- kitty/screen.h
- kitty/state.c
- kitty/state.h
- kitty/window.py
Add `mouse_show_command_output`
Name the `command` consistently:
- For the user configuration part, use `command`.
- Use `cmd` in code, in parameters, to shorten the length.
Now mouse click will record the last jump position. So when using the relevant get last visited command output, it will also take effect for mouse actions.
Also there are too many shell integration URLs in the commented configuration files now, do you have any good ideas? Or just leave it as is?
> Allows to open the command output in pager by mouse click

- kitty/screen.c
fixes ibus positioning problem when shell outputs text with pre-edit
overlay open as per suggestion in this comment:
https://github.com/kovidgoyal/kitty/issues/1000#issuecomment-972550266
Thanks for the suggestion!
> screen_linefeed: add missing MOVE_OVERLAY_LINE_WITH_CURSOR

- glfw/cocoa_window.m
- kitty/cocoa_window.m
Allow macOS notification to play system alert sound.
Also solved an issue with macOS notifications not showing up. Now macOS notifications from the cli program will be properly alerted when kitty is in the foreground.
> Allow macOS notification to play sound

- kitty/conf/types.py
For MultiOption, if `documented=False` is set and long_text is also present, then the commented configuration file will be generated with only the long_text, without any name above.
The recent `kitten_alias` changes is affected by this.
> Append long_text only if at least one documented option exists

- docs/basic.rst
- docs/conf.rst
- docs/keyboard-protocol.rst
- kitty/options/utils.py
Added command key full name.
Added modifier key Unicode character.
Replaced ASCII `^` with the control modifier key Unicode character representation.
I'm not sure about using :ref: `Modifier key definitions <modifiers>` in the documentation.
https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts
` For a list of modifier names, see: :link: GLFW mods ... `
```python
ref_map = { ..., 'modifiers': f'{website_url("keyboard-protocol")}#modifiers', ... }
```
I also found some :kbd: conversion issues in the generated HTML documents.
Execute make html in the master branch.
Comma in the key name. Space-separated words are parsed as standalone keys, e.g. `and`.
```html
the <kbd>Enter,</kbd> <kbd>Tab</kbd> <kbd>and</kbd> <kbd>Backspace</kbd> keys
```
In previous versions, such as the online version …
> Slightly tweaked macOS modifier key documentation

- docs/faq.rst
Closes #4292.
Due to how difficult this was to find, I imagine many users are just dealing with it, or like me, not noticing because they use single-instance. Good thing for people to try anyway.
> Document GPU power saving affecting kitty startup

- kitty/screen.c
Today I had a whim and used `show_last_visited_command_output` with the `unscroll` escape code, and as expected, the result of getting the last visited command output is incorrect.
```shell
printf "\e[3+T"
```
The last visited position is only increasing but not decreasing, so there is a problem.
This PR fixes the issue.
> Update the last visited command output position after unscrolling

- glfw/cocoa_window.m
As mentioned in the previous issue, if you switch window focus during input method input state, the pre-edit text is not cleared.
https://github.com/kovidgoyal/kitty/issues/4219
This PR solves the issue.
> Update IME status when window lost focus

- docs/faq.rst
I'm sorry to double PR @kovidgoyal , but while I was working on something else, it began to bother me that our FAQ told users to run some command to change the sysfs as root, so now that I know exactly what's wrong I wrote a better solution. Sorry for the trouble I've been to you of late..
> Make the GPU selection FAQ item not require root

- bypy/sources.json
- docs/kittens/hyperlinked_grep.rst
- glfw/cocoa_init.m
- kitty/cli.py
- kitty/colors.h
- kitty/main.py
- kitty/open_actions.py
- kitty/rc/launch.py
- kitty/remote_control.py
The remote control launch command description uses code blocks enclosed in the generated docs HTML.
This PR fixes the issue.
Also use `:code:` to enclose choices.
Replace links with HTTPS.
Removed some duplicate imports.
> Docs: Fix remote control launch description and other minor tweaks

- kitty/options/definition.py
Add documentation for options that are missing valid values.
Since indented lines are considered commands without line break, so manually wrap these document lines.
> Docs: Add valid values for background image related options

- docs/changelog.rst
- kitty/boss.py
- kitty/options/utils.py
When the user has multiple OS windows, this action can be used to quickly switch to the desired window.
Some other terminal emulators also have this feature by default, but their shortcuts are not fully customizable.
> Add a new mappable action nth_os_window to focus OS window

- kittens/diff/options/definition.py
- kitty/rc/create_marker.py
- kitty/rc/get_colors.py
Use the pygments official website URL.
Use `:doc:` to generate relative URL with text in html document. Also show the link to the official website in the command line help.
Use `:code:` to wrap the command, which will be identified by cyan color in the command line help.
I can't replace `{hints_url}` in `kittens/hints/main.py` with a relative link to the document (which is the official URL in the locally generated document). So leave it as is.
> Docs: update the pygments URL and the markers doc URL

- docs/_static/custom.js
Fix an issue where opening a document link with hashtag in Chrome would not scroll to the anchor.
When the body of the document and the sidebar are in smooth scrolling at the same time, the scrolling of the body is stopped, resulting in not positioning to the anchor.
Any links that open in Chrome are at the top of the page.
https://stackoverflow.com/questions/49318497/google-chrome-simultaneously-smooth-scrollintoview-with-more-elements-doesn
> Fix document link scrolling issue

- kitty/options/utils.py
Fix the issue that action `paste` does not work.
```shell
kitty -o 'map f1 paste text'
```
```text
paste
Paste the specified text into the current window
```
https://sw.kovidgoyal.net/kitty/actions/#paste
> Fix paste mappable action

- kitty/screen.c
An exception occurs when executing `dump_lines_with_attrs`.
```text
TypeError: list.append() takes exactly one argument (4 given)
...
self.screen.dump_lines_with_attrs(strings.append)
SystemError: <method 'dump_lines_with_attrs' of 'fast_data_types.Screen' objects> returned a result with an error set
```
> Fix action dump_lines_with_attrs

- docs/actions.rst
- docs/kittens/hints.rst
- docs/overview.rst
- kitty/actions.py
- kitty/boss.py
- kitty/window.py
Improve the list of default shortcuts for kitten in the documentation by listing the kitten names.
https://sw.kovidgoyal.net/kitty/actions/#kitten
Also use action names as link text in some places.
> Docs: List kitten names in the kitten default shortcuts list

- publish.py
Sorry, I missed some files in the last PR.
I hope that all the required html files are generated this time.
```text
docs/_build/dirhtml/kittens/unicode-input.html
docs/_build/dirhtml/kittens/unicode-input/
docs/_build/dirhtml/kittens/unicode-input/index.html
docs/_build/dirhtml/kittens/unicode_input.html
docs/_build/dirhtml/kittens/unicode_input/
docs/_build/dirhtml/kittens/unicode_input/index.html
```
> Fix unicode-input docs redirect

- kitty/rc/scroll_window.py
When executing the remote control `scroll-window 1u` (or end with `+`), an exception is thrown.
```text
ValueError: invalid literal for int() with base 10: '1u'
```
I also found that when "unscroll" is executed with escape code or this remote control command. The cursor position does not seem to be updated. For example, after generating some empty lines under the current prompt cursor, execute unscroll. `printf "\e[3+T"`
Although the scrollback content is moved down. But the cursor did not move down together.
Would you mind taking a look? Thanks.
Perhaps the cursor position needs to be updated even when scrollback is scrolled, to keep it at the shell prompt. (when not unscrolling past the cursor position)
---
Also, for "unscroll", the common meaning of this word seems to be:
"To open or …
> Fix remote control scroll-window argument parsing

- docs/conf.py
I found that when building the docs, make html and make dirhtml end up with different kbd styles.
This PR enables sphinx KeyboardTransform builtin extension. The final result will be the same.
related:
https://github.com/sphinx-doc/sphinx/issues/7530
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd#representing_keystrokes_within_an_input
> Docs: Enable kbd transform when building dirhtml with sphinx

- glfw/cocoa_window.m
```shell
kitty --config=NONE -o hide_window_decorations=yes
```
Issue:
https://github.com/kovidgoyal/kitty/issues/4349
I am not sure if this is the best way to handle this, please review, thanks.
> macOS: Fix keyboard input not working after toggling full screen

- gen-config.py
- kitty/cocoa_window.m
- kitty/config.py
- kitty/fast_data_types.pyi
- kitty/glfw.c
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/utils.py
- kitty/state.c
- kitty/state.h
- kitty/window.py
Support for explicitly setting the window title bar style for macOS.
When the system appearance of macOS is set to Auto, you can set the appearance of kitty to a fixed Light or Dark.
> Add light and dark to the macOS title bar option

- kitty/options/utils.py
Catch exception and ignore the invalid title bar color instead of displaying it in the overlay, since it doesn't matter.
> Ignore invalid title bar color

- shell-integration/zsh/.zshenv
- shell-integration/zsh/completions/_kitty
- shell-integration/zsh/kitty-integration
- shell-integration/zsh/kitty.zsh
Note:
- Very lightly tested.
- Docs not updated.
> Rewrite zsh integration

- shell.nix
shell.nix is missing a depencency on the UserNotifications framework on macOS with Apple silicon. Unfortunately we can't just unconditionally include this dependency because Nixpkgs uses a different macOS SDK version for macOS on an Intel processor compared to macOS on Apple silicon. The older SDK version 10.12 on Intel does not have the UserNotifications framework, which would lead to an "attribute missing" error when trying to execute `nix-shell`. The condition can be dropped when the macOS SDK version for Intel processors is finally updated. See https://github.com/NixOS/nixpkgs/issues/101229 for progress on that.
See https://github.com/NixOS/nixpkgs/pull/137512 for more context.
Closes https://github.com/kovidgoyal/kitty/issues/4352.
@kovidgoyal Please don't merge this until someone …
> shell.nix: add dependency needed on Apple silicon

- glfw/linux_notify.c
- glfw/wl_text_input.c
- glfw/wl_window.c
- kittens/choose/main.c
- kittens/ssh/main.py
- kittens/themes/main.py
- kitty/conf/generate.py
- kitty/fonts/box_drawing.py
- kitty/freetype.c
- kitty/freetype_render_ui_text.c
- kitty/glfw.c
- kitty/layout/grid.py
- kitty/screen.c
- kitty/tabs.py
- kitty/utils.py
Refactor the code related to variable name and variable assignment.
https://lgtm.com/projects/g/kovidgoyal/kitty?mode=list
(There are many warnings that I think can be ignored.)
I'm not sure about the following one, so I left it unchanged and it looks like the variables w, h are not used.
```diff
diff --git a/kittens/icat/main.py b/kittens/icat/main.py
index 2507a28b..b60e0142 100755
--- a/kittens/icat/main.py
+++ b/kittens/icat/main.py
@@ -168,7 +168,6 @@ def set_cursor(cmd: GraphicsCommand, width: int, height: int, align: str) -> Non
cw = int(ss.width / ss.cols)
num_of_cells_needed = int(ceil(width / cw))
if num_of_cells_needed > ss.cols:
-        w, h = fit_image(width, height, ss.width, height)
ch = int(ss.height / ss.rows)
num_of_rows_needed = int(ceil(height / ch))
cmd.c, cmd.r = …
```
> Avoid defining variable names that already exist and remove redundant variable assignments

- kittens/diff/speedup.c
- kitty/glfw.c
The width and height of the window are already guarded by `if (w <= 0 || h <= 0 || ...) { ...; return; }`, no need to check them twice.
Rename the global variable LineBuffer `b` since `a` and `b` are used in the macros.
So far all the similar issues found have been fixed.
> Minor refactoring on variable name and conditional check

- kitty/mouse.c
Allow scrolling of the mouse pointing part of a multi-panel program when not focused under macOS.
https://github.com/kovidgoyal/kitty/issues/4367#issuecomment-1004641539
I'm a little concerned about the performance impact of these redundant update steps. I have not found any other good way to do this.
> macOS: Fix mouse scrolling multi-panel program when no focus

- shell-integration/zsh/kitty-integration
> Disable aliases when patching functions in zsh integration

- shell-integration/zsh/kitty-integration
- Replace ff63e58 with a better fix.
- Make writing to the TTY more robust.
- Remove PS2 patching as it has no effect.
I would very much prefer if kitty didn't inject zsh code into the shell (at least by default) but I don't think I can change your mind on it. The next best option is to make the injected code less likely to cause issues. I can help with the latter if you ping me whenever issues with zsh integration arise.
> Minor improvements in zsh integration

- setup.py
`CFBundleTypeOSTypes` is deprecated and replaced with `LSItemContentTypes`.
Add kitty to the text files and image files open with list.
Allows dragging arbitrary filename files to kitty, but does not include kitty in the open with list. Let kitty check and process other arbitrary files.
> macOS: Add kitty to the open with list for text files and image files

- docs/kittens/hyperlinked_grep.rst
It was documented for zsh (2 lines above) but not fish.
While looking for how to do the same in fish, I couldn't find how to do
*exactly the same*, but turns out there's a neat way to do both the
aliasing and autocompletion mapping at the same time.
See https://fishshell.com/docs/current/cmds/function.html :
> `-w WRAPPED_COMMAND` or `--wraps=WRAPPED_COMMAND` causes the function
> to inherit completions from the given wrapped command. See the
> documentation for [complete](https://fishshell.com/docs/current/cmds/complete.html#cmd-complete)
> for more information.
> kittens/hyperlinked_grep: document how to tell fish to autocomplete with rg

- glfw/cocoa_window.m
- kitty/boss.py
- kitty/child-monitor.c
- kitty/cocoa_window.m
- kitty/fast_data_types.pyi
- kitty/glfw.c
- kitty/main.py
- kitty/options/definition.py
- kitty/options/types.py
- kitty/state.c
- kitty/state.h
- setup.py
Allows to customize the key combinations for the `secure keyboard entry` feature.
The original hard-coded key combination can be rebinded by the user.
> macOS: Allow mapping secure keyboard entry keyboard shortcut

- glfw/glfw.py
- kitty/state.c
Revert the changes related to set_options debug_keyboard.
Remove the Carbon framework flag for glfw.
Sorry I didn't notice that debug_keyboard already exists.
Also the link dependency on Carbon has been moved and glfw no longer needs it.
> Cleanup previous PR

- glfw/cocoa_window.m
Implement our own NSTextInputContext and pass `doCommandBySelector` to the client for processing. There will no longer be a beep sound.
https://github.com/kovidgoyal/kitty/issues/4489
I have done a simple test, modifying the system key binding, the behavior remains the same as before, `doCommandBySelector` does not do anything.
```text
{
"^/" = (insertText:, "Hello");
} 
```
When insert text is used in the system keybindgs (see above), the text can be inserted normally.
---
It should be noted that there has been a problem with key combinations such as ctrl + xxx for input methods, as I mentioned in a previous issue.
Although the keys are processed by IME, the characters are also output to the child program (e.g. Ctrl+.  -> insert: . (ASCII dot) && toggle IME function). This has nothing to …
> macOS: Suppress the key combinations beep sound

- glfw/cocoa_init.m
- glfw/cocoa_platform.h
Add new global shortcut option from macOS Monterey.
Categorized by global shortcut key function group. (Sorting by ID is easy, but listing by function group is not.)
Watch for system preferences changes and update global_shortcuts.
I have adjusted some important features that are enabled. Here is the not enabled ones with consideration.
- keyboard
- kSHKkSHKChangeTheWayTabMovesFocus
* We don't have Cocoa UI components.
- kSHKTurnKeyboardAccessOnOrOff
* This is not important and should be set by the user. (The default shortcut works properly.)
- kSHKMoveFocusToTheWindowToolbar
* We don't have a Cocoa UI toolbar.
- kSHKMoveFocusToTheFloatingWindow
* We don't have a Cocoa floating window.
- screenshots - Not very important, but I'm not sure. (The default shortcut works properly.)
- …
> macOS: Watch for system preferences changes and update global_shortcuts

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Only use our cursor shape setting function in fish default keybindgs.
Use `fish_cursor_insert` to modify the insert mode cursor shape to a bar.
> Improve fish cursor shape integration

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
https://fishshell.com/docs/current/cmds/functions.html
functions --details
- "/path/to/func.fish"
- "stdin" (defined interactively / from cli / from stdin)
- "-" (created via `source`)
- "n/a" (not available)
`fish_title.fish` defaults to autoload, and fish comes with a function directory path that is always at the last one. All functions that are not read in the last directory location are considered overridden.
Please review if there are any issues, thanks.
https://github.com/kovidgoyal/kitty/issues/4452
The only thing I'm not comfortable with is a path sep "/" in the middle of `"$fish_function_path[-1]/*"`, maybe that should be removed?
> Shell integration: Only override default fish_title

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
The vi mode cursor in fish does not blink by default.
> Shell integration: Set the fish vi mode cursor to blink

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Remove functions early.
Integration scripts will not be run repeatedly if they are sourced multiple times or fail during execution.
---
I found a problem getting the output of the last command. Reproduced in zsh , bash. I'm still finding the cause.
Also I was thinking of using the fish "-C" parameter instead of environment variables. But I need to make sure that the execution order meets the requirements first.
> Shell integration: Remove functions that run only once at start

- kitty/screen.c
- kitty_tests/screen.py
When searching the output of the last command executed, if scrollback has been scrolled,
then the start point is actually outside (below) the screen and the number of scrolled lines needs to be added.
That's my bad. I don't know how this was slipped through. :(
> Fix searching the last command output

- docs/conf.py
- glfw/cocoa_init.m
NSEvent `charactersIgnoringModifiers` does not convert keystrokes to characters without the shift modifier, instead, the shift modifier is applied.
However, in the system preferences, it is always the unmodified keys that are recorded.
This PR tries to solve the issue. Do a conversion of the shift modifier key character and check it first. And adds the shiftable shortcut with "shift" to the global shortcut.
You can't use `event.characters`, since there are also the option key modified chars.
Please review if there is any problem, thank you.
---
https://developer.apple.com/documentation/appkit/nsevent/1524605-charactersignoringmodifiers?language=objc
> charactersIgnoringModifiers
> The characters generated by a key event as if no modifier key (except for Shift) applies.
keyDown: …
> macOS: Fix global shortcuts with shift modifier key not working

- docs/basic.rst
- docs/conf.rst
Add missing macOS shortcuts.
Change the description of the open URL action.
Also add a brief description of how to quickly switch to the nth OS window.
> Docs: Add missing macOS shortcuts and nth_os_window

- docs/shell-integration.rst
- shell-integration/fish/vendor_completions.d/kitty.fish
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
* Move the completion function to the autocomplete script.
It was written this way because the autocomplete script is located in the user configuration folder and overrides the script that comes with fish. So it was necessary to detect and use the old one. However, now it only loads when integration is enabled, so you can just use the new version.
And `no-complete` doesn't make sense either, because it's not appropriate to use `complete --erase kitty`.
* Fix some issues with cursor shape setting, respect user configuration.
The vi mode cursor setup takes effect when the user has not done any cursor configuration. Enables as a whole, otherwise it would be weird.
In previous version, the cursor functions is cleared when `set -g fish_key_bindings fish_default_key_bindings` is executed twice, …
> Shell integration: Improvements for fish integration

- kitty/debug_config.py
- kitty/options/utils.py
Adjust the order of modifier key names to match the config and docs.
The modifier key order was adjusted in the previous PR, but the debug config was left out and is now adjusted as well.
(ctrl, shift, alt/opt, super/cmd, ...)
https://github.com/kovidgoyal/kitty/pull/4238
Fix mouse maps are indented with one more space.
Add the missing mouse triggers click (-2) and double-click (-3).
Refactor the print functions to make it easier to use in custom kitten.
These functions, however, all seem to be repeating patterns, and I tried to "DRY" them, but got stuck with mypy.
BTW:
Why does kitty/boss.py have executable permission? In which scenario do it need to be executed directly?
> Add missing click and double click names to debug config

- kittens/tui/operations.py
- kitty/options/definition.py
- kitty/options/utils.py
Add new dotted and dashed underline values.
Add new style options for url underline style.
Also use "straight" for single underline, consistent with the protocol extension document.
Use fixed values for dict, which is unlikely to change in the near future, instead of string splitting and for loops.
> Add new dotted and dashed underline values

- kittens/ask/main.py
- kitty/boss.py
- kitty/window.py
Add default choice option for ask kitten.
Press Enter to select the default, Esc to select nothing (Ctrl+C).
Make the `No` click range the same as `Yes` for easy clicking.
Makes the default take effect for text input, applied in set_tab_title action.
The tab title can be cleared, and the window title will be used again.
Set reasonable default choice for some features that use ask kitten.
However, my personal preference for quit confirmation is still `No` as the default.
Please review if there are any problems, thank you.
> Add default choice option for ask kitten

- kitty/options/definition.py
Add modifier key names to the document.
No need to check the GLFW documentation, in case someone really can't figure it out.
> Docs: Add modifier key names and aliases

- glfw/cocoa_window.m
This fixes the preedit text being cleared when using shortcut keys to
switch candidate text in the input state.
Hope I didn't miss anything, please review, thanks.
> Update preedit text with markedText

- glfw/cocoa_window.m
Since I replaced caps_lock on my keyboard, I forgot to test it.
Also solve the issue that pre-edit is cleared by pressing F1, NUM_LOCK and other function keys, Ctrl+XXX and other modifier key shortcuts.
I have tested it and all related issues have been resolved so far.
Please review if there are any potential issues, thank you.
> macOS: Fix caps_lock not clearing pre-edit text when using IME

- shell-integration/bash/kitty.bash
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Set cursor shape to steady block before executing commands in vi mode. I left this out.
Configure the vi mode cursor shape on demand. If the user only uses normal mode, no vi mode global variables will be added.
Since it is unlikely that more features will be added in the future, remove one function call at each marking.
Add a brief comment to the XDG_DATA_DIRS section.
> Add comments and minor tweaks to fish integration

- glfw/cocoa_window.m
Some input methods do not cancel the input session when switching focus, resulting in inconsistent states.
Explicitly cancel it in this PR.
Also need to cancel when switching kitty windows (tabs), closing windows. looks like it needs to be called in python.
I don't know if the same issue exists under Linux.
> macOS: Explicitly cancel IME composition when losing the focus

- kitty/fast-file-copy.c
While testing the latest master version on Linux, I discovered that the test test_disk_cache (kitty_tests.graphics.TestGraphics) fails when the cache directory is on ZFS. This also happens with the latest version 0.24.1. On a tmpfs, everything works fine.
The error message is "Failed to copy data to new disk cache file during defrag: Invalid argument". I tracked the error to the call `ssize_t n = copy_file_range(infd, &r, outfd, NULL, len, 0);`, which returns -1 and sets `errno` to 22. One instance of the arguments to the function I observed was `infd`: 7, `r`: 72, `outfd`: 8, `len`: 36.
Perhaps this is caused by me running ZFS 2.1.2 on Linux 5.16.0, which is not a supported combination. This ZFS version is only "compatible with 3.10 - 5.15 kernels" according to the release notes. Or …
> Fix test on ZFS

- glfw/cocoa_window.m
- kitty/fast_data_types.pyi
- kitty/keys.c
- kitty/screen.c
- kitty/state.c
- kitty/state.h
- kitty/window.py
Switching windows or closing windows during typing will no longer leave pre-edit text on the screen.
Under macOS, calling `invalidateCharacterCoordinates` does not always update the position of the input method candidate bar.
Although it is possible to continue typing, it is rather awkward and meaningless.
You are right, it is better to cancel the IME.
> Cancel IME when the kitty window lost focus or closed

- glfw/cocoa_window.m
- kitty/keys.c
- kitty/window.py
When the inactive window is closed, the input method will no longer be canceled.
I also found that when the window is redrawn (resized), the overlay text is cleared. Is there a good way to redraw it? 
Honestly, the edge case handling requires time investment and is not very useful. The good thing is that it reduces inconsistent state cases and hopefully (if no new bugs are introduced) makes the software more robust.
> Cancel IME for active kitty or OS window only

- setup.py
Allow toggling input sources using CapsLock.
TICapsLockLanguageSwitchCapable
Allow programs to request photo, motion, speech recognition permissions.
NSPhotoLibraryUsageDescription
NSMotionUsageDescription
NSSpeechRecognitionUsageDescription
Add local network unicast or multicast usage description.
NSLocalNetworkUsageDescription
Remove iOS-only items.
NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription
Add kitty to the open with menu list to open any file, otherwise files with no extension or files not recognized by macOS cannot be opened easily.
> macOS: Refactor and update info plist permissions

- docs/basic.rst
- docs/conf.rst
- setup.py
Fix macOS shortcut for debug_config.
Set the InfoDictionary version explicitly, hopefully the behavior will be unchanged when the default version is upgraded.
Since we have the quit confirmation feature, so we explicitly specify that sudden termination is not supported.
> Fix macOS shortcut for debug_config and info plist minor tweaks

- kitty/debug_config.py
- kitty/options/utils.py
Remove a space that was introduced by mistake.
Also add colors to the colon after the title of the dict type in debug_config to be consistent with the rest.
> Remove a space that was accidentally introduced earlier

- docs/changelog.rst
- kitty/fast_data_types.pyi
- kitty/screen.c
- kitty/window.py
For some programs that don't work well, they won't clear the blank lines under the cursor line. This action can be used to reverse the scrolling.
Also adjusted the name of the menu item that clears to the cursor `Cmd+K`.
Used initial capitalization and simplified the text (as it also works for the cursor prompt).
Moved Reset to the bottom, as this cleans up the most.
Please review if it is appropriate, thank you.
> Add mappable action reverse_scroll_to_cursor

- kitty/tabs.py
When executing a script without execute permission via launch, the arguments are missing.
I didn't think of any reason why the arguments need to be removed, so please let me know if I'm wrong.
Also fix `cmd[0]` that was replaced with `kitty` being executed incorrectly when there was no shebang.
I have a question, why do we use `kitty +hold` here?
If opts.hold is configured, is this a double hold?
> Fix issue with launch when running scripts without exec permission

- kitty/cocoa_window.m
- setup.py
Add archive file type.
There are still file types that are not recognized (e.g. conf, rst), so add a standalone service to open them.
Users can right click on the file and select `Open with kitty` in the service submenu.
At this point, the compressed file can be extracted. Although it is not possible to compress the files.
If one really want to solve it, it looks like a kitten is needed to select the multi-file actions.
It is indeed very complicated.
---
One issue remains:
Opening kitty via service, an initial window appears, and then the new tab or new OS window is shown.
This also affects `New kitty tab Here`, `New kitty Window Here`.
I first checked the launch_urls, `def clear_initial_window()` not called.
```text
needs_window_replaced = 
(not …
```
> macOS: Add archive file type and standalone open with kitty service

- docs/changelog.rst
- kitty/boss.py
- kitty/child-monitor.c
- kitty/cocoa_window.m
- kitty/glfw.c
- kitty/state.h
- kitty/tabs.py
- setup.py
Add `kitty-launcher.desktop` to handle URL scheme for Linux.
Add changelog entry for previous PR.
The initial window is not removed when using launch_urls if the startup session is configured.
Simplifies reassembling for the command when executing the scripts without exec permission.
> Add launcher desktop file to open URLs on Linux and minor tweaks

- docs/open_actions.rst
- kitty/cocoa_window.m
- kitty/fast_data_types.pyi
Add the ability to set kitty as default URL handler.
Previous discussion:
https://github.com/kovidgoyal/kitty/pull/4618#issuecomment-1030777843
> macOS: Add a way to set kitty as the default handler for the URL schemes

- kitty/boss.py
Fix using service to open new tab when there is no OS window.
> macOS: Fix launching a new tab when there is no OS window

- docs/faq.rst
- kittens/icat/main.py
- kitty/options/definition.py
Replace `kitty list-fonts` with `kitty +list-fonts`.
According to the following commit, it is recommended to use namespaced launch points.
https://github.com/kovidgoyal/kitty/commit/b9f21f285ce800dfd020fd99d5b2fa622438d334
> Docs: Prefer namespaced launch points

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Need to restore XDG_DATA_DIRS after the script is loaded and before exiting. Otherwise it will affect other programs.
In fish master branch, loading from env will take precedence and hopefully will not affect other programs.
Reduce function calls again, since no more functions will be added to reuse them in the near future.
Use the simpler echo instead of printf to improve marking performance (Well, in ns, almost negligible).
> Shell integration: Restore XDG_DATA_DIRS right after fish integration script is loaded

- glfw/cocoa_init.m
Disabled shortcuts should be available in kitty.
Missed in the previous PR to revert the previous changes.
> macOS: Ignore when the global shortcut is disabled

- kittens/hints/main.py
Match and strip unicode single and double quotes.
U+2018, U+2019
U+201C, U+201D
When using `wget`, the downloaded filename is surrounded by Unicode quotes.
Since the quotes are matched on the left and right ends (after the file extension), it is unlikely to produce many false positives.
> hints kitten: Match and strip Unicode single and double quotes

- README.asciidoc
The current README packaging status image is linked to the cached image on the github camo service when shown on GitHub.
Change the link to Repology versions page.
> README: Add link for packaging status

- glfw/wl_init.c
This bumps seatVersion to 5. The code should still work if the user is using seatVersion 4.
Additionally this means that the code now requires libwayland 1.10 to compile. Even Ubuntu 16.04 had that version so we should be safe here.
Aside: doesn't glfw's license require marking the version as modified?
> Seperate discrete (mouse wheel) and continuous (touchpad) scroll events on wayland

- kittens/tui/loop.py
When the fourth and fifth mouse button is pressed, mouse demo shows the left and middle buttons.
Fix mouse extra button bit mask.
Add mouse scroll wheel buttons.
> Fix mouse demo kitten to show the extra buttons

- kitty/boss.py
Currently `select_tab` only show the default tab title even after renaming it with `set_tab_title`.
I'm not sure if this was done on purpose. I think showing the renamed tab title in `select_tab` window would be useful.
> Show tab name otherwise tab title for select_tab

- docs/changelog.rst
- kitty/mouse.c
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/types.py
- kitty/state.h
Under macOS, some mice have a scroll wheel that starts at yoffset 0.100...1 (with default multiplier it's 0.500..5), resulting in one line per click with a slow scroll.
If a larger multiplier is set, the acceleration is too fast.
Add a new option `wheel_scroll_min_lines` to set the minimum number of scrolling lines.
If the number is positive, the minimum number of lines will be taken. (Obviously acceleration does not take effect when the minimum number is not reached.)
If it is negative, the number of lines is always added and the acceleration remains the same and takes effect immediately.
For me personally, I use the default `wheel_scroll_multiplier 5.0`, and `wheel_scroll_min_lines -2`.
> Add wheel_scroll_min_lines to set the minimum scrolling lines

- docs/changelog.rst
- glfw/cocoa_platform.h
- glfw/cocoa_window.m
macOS will set the cursor to arrow after milliseconds after the switch
desktop animation ends.
So the cursor that was updated immediately after the focus will be changed again.
This also affects toggling fullscreen.
Reduce unnecessary cursor updates since we don't use cursor rects.
> macOS: Fix the mouse cursor being set to arrow after switching desktops

- docs/changelog.rst
- shell-integration/bash/kitty.bash
Explicitly use `builtin` to call the commands.
Use Bash's string manipulation facility to remove new lines.
Use the official project name of Bash.
GNU Bash
https://www.gnu.org/software/bash/
---
Also, the fish installed in CI is an outdated version. This version is broken and not worth supporting. I believe it will not work.
https://github.com/kovidgoyal/kitty/commit/081d6a3f166d013e49193838474415e0ded5ebd5
`sudo apt-get install -y ... fish`
```text
https://github.com/kovidgoyal/kitty/pull/4558#issuecomment-1020261408
faho commented on Jan 25
> ... Ubuntu's packages in 20.04 (the current LTS) are still at 3.1.0 (not even 3.1.2, the bugfix release) with some Debian patches.
> That's rather out of date (about 80% of commits in 3.3.1) and makes tests with it essentially meaningless. …
```
> Bash integration: Use builtin to call the commands

- .github/workflows/ci.py
- kitty_tests/shell_integration.py
Add fish integration tests.
Also I noticed that when getting the last command output and comparing the text on the screen it does not match. This is because the last command output is missing the newlines.
`kitty/kitty_tests/__init__.py`
```python
def last_cmd_output( ... ):
return ''.join(lines)
```
Do we need to use `\n` to concatenate lines here?
> Add fish integration tests

- .github/workflows/codeql-analysis.yml
- kitty/fonts.c
Avoid shadow the global variable name.
Disable automatic installation of Python dependencies on CI.
```text
CodeQL-Build
An error occurred while trying to automatically install Python dependencies:
Error: The process '.../auto_install_packages.py' failed with exit code 1
Please make sure any necessary dependencies are installed before calling the codeql-action/analyze step,
and add a 'setup-python-dependencies: false' argument to this step
to disable our automatic dependency installation and avoid this warning.
```
> Refactor: Avoid shadow the global variable name

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Efficiently check the version via the new variable added in fish 3.3.0 and exit when not satisfied to avoid breaking outdated fish.
```text
set --show fish_killring 
$fish_killring: set in global scope, unexported, with 0 elements
Variable is read-only
```
I have benchmarked that using glob or regex to check the version string will have performance loss. (The fish that comes with some Linux distributions is broken and has no version number.)
Consistent with the behavior when using lower version of the shell and not outputting warning text.
This is equivalent to not enabling integration.
I have not introduced `\eP@kitty-print|...` or `base64` to minimize the impact.
> Shell integration: Check fish version and exit on outdated versions

- kittens/show_error/main.py
When an error message is displayed, pressing ctrl+d will exit.
I've been annoyed with this one for a while now.
> show_error kitten: Exit at EOF

- kitty_tests/shell_integration.py
I'm guarding ZDOTDIR changes and others by `[[ -o globalrcs ]]` in `/etc/zshenv`.
However, `.zshenv` has not been read (and no chance anymore).
> Disable system startup files in zsh integration test with --noglobalrcs

- kittens/show_error/main.py
- kitty/boss.py
Use the show_error kitten.
This will allow to close with ctrl+d.
> Use show_error kitten to display launch URL error messages

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
The read-only variable fish_killring, added in fish 3.3.0, may become modifiable in the future.
So also fall back to check the last known working version: fish 3.2.0.
```text
https://fishshell.com/docs/3.2/relnotes.html#interactive-improvements
$status_generation: set in global scope, unexported, with 1 elements
Variable is read-only
$status_generation[1]: |0|
```
Finally check that the `$version` string does not match `3.1.*`.
All versions prior to 3.1.0 will not automatically load the integration script,
and if the user loads the script manually, errors will occur before reaching this check.
It will never reach `string match` unless fish breaks backward compatibility by removing the first two variables.
This is the last check to make sure the script will work properly.
Please review, …
> Also fall back to check the last known working version of fish

- glfw/wl_window.c
A surface commit must happen after the acknowledgement of a configure, even if it is a same size configure.
Just move the surface commit outside of the if statement to make it always run on a xdg configure.
> wayland: always commit surface on configure

- nerd-fonts-glyphs.txt
- Fix overlapping nerd fonts glyph.
- Add some reasonable keywords from font awesome official aliases.
`U+F67C` is `comment alert`, which you tested earlier.
Also I found that I couldn't search for the icons using some common font awesome names. I compared all the missing aliases and added some reasonable keywords (official ones).
> Fix overlapping nerd fonts glyph name

- kitty/shell_integration.py
- kitty_tests/shell_integration.py
- shell-integration/bash/kitty.bash
In POSIX mode, bash does not execute ENV when it is not an interactive shell.
There may be issues when executing bash commands or script files with `launch` (and perhaps with `--type=background`).
```shell
bash -c "exec sh -i"
```
In this PR, try to parse the arguments and ignore the non-interactive cases.
```text
bash -c "cmd"
bash file.sh
bash -i file.sh
bash -s arg1 --rcfile --posix
bash -ic "cmd" # This one is interactive, but not important so skip it.
```
Hopefully I didn't miss something.
> Shell integration: Fix running bash non-interactively

- kitty_tests/shell_integration.py
I see an error in the recent CI test.
Try to detect the right prompt first when testing the vi mode cursor.
> Try to make the fish vi cursor test more stable

- kitty/window.py
Fix not scrolling to the bottom when an interrupt is sent.
Replicates the same side effects of keyboard key event.
```c
if (screen->scrolled_by && action == GLFW_PRESS && !is_modifier_key(key)) {
screen_history_scroll(screen, SCROLL_FULL, false);  // scroll back to bottom
}
//...
schedule_write_to_child(w->id, 1, encoded_key, size);
```
https://github.com/kovidgoyal/kitty/discussions/4787
> Fix not scrolling to the bottom when an interrupt is sent

- kittens/ssh/main.py
- kitty_tests/shell_integration.py
- shell-integration/bash/kitty.bash
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
- shell-integration/ssh/bootstrap.py
- shell-integration/ssh/bootstrap.sh
- shell-integration/zsh/kitty-integration
- Avoid unnecessary which and fix typos.
- Adjust the order of exec function definitions: zsh, fish, bash.
- Improve SSH detection without affecting daily performance.
- Remove the fish integration B prompt marking. (The same as zsh, bash.)
For SSH detection, first exclude the case that KITTY_PID exists.
Then check the existence of KITTY_WINDOW_ID.
Call `who` only if sudo is running (environment variables are cleared) and shell integration is manually installed for the switched user.
- When run locally, only one environment variable, KITTY_PID, will be checked.
- In most SSH connections, only KITTY_PID, SSH_TTY will be checked.
- Only when the integration is installed manually and sudo is run, four environment variables will be checked and who will be called once.
Users can add …
> Minor tweaks to ssh kitten and shell integration

- shell-integration/bash/kitty.bash
- shell-integration/zsh/kitty-integration
Bash integration cannot clean up line breaks when outputting debug logs.
```text
[PARSE ERROR] DCS sequence contained non-printable character: 0xa ignoring the sequence
```
> Fix bash integration debug log printing

- shell-integration/ssh/bootstrap.sh
Use the more explicit b64encode b64decode.
Add Perl to support more systems.
I tested it on OpenBSD and it works fine now.
I found that if there are errors during execution, the cursor does not move to the beginning of the line after a line break. Is this normal?
```text
ERR: error message line one.
ERR: error message line two.
```
> ssh kitten: Fix support for OpenBSD and add Perl in bootstrap.sh

- docs/kittens/ssh.rst
- kittens/ssh/main.py
- shell-integration/ssh/bootstrap.sh
- Replacing `\n` and `!` with `\r` and `\241` (Inverted exclamation mark) for tcsh.
- Reimplement the login shell startup loading with POSIX ENV to support sh without the -l option.
FreeBSD 13.0 sh:
https://github.com/freebsd/freebsd-src/blob/release/13.0.0/bin/sh/main.c#L142-L151
Dash 0.5.11:
https://git.kernel.org/pub/scm/utils/dash/dash.git/tree/src/main.c?h=0.5.11#n149
All the default shells are now working fine under FreeBSD.
---
> ... running FreeBSD, ... relies on termcap rather than terminfo ...
> ... convert the terminfo file ...  on local machine with kitty
>     infocmp -C xterm-kitty
> The output ... which should be appended to `/usr/share/misc/termcap` on the remote server ...
Does this need to be added to bootstrap script (sh and python)?
I see that …
> ssh kitten: Add support for FreeBSD tcsh sh default shells

- setup.py
ssh kitten needs to send `terminfo/kitty.terminfo`.
> Add terminfo src file when packaging

- kittens/ssh/main.py
- shell-integration/ssh/bootstrap.py
- shell-integration/ssh/bootstrap.sh
- Remove the left out _ksi_safe_source in the sh startup script.
- Use POSIX LOGNAME when USER is empty.
- Allow shells that do not support `-l` option and shells whose names do not end with `sh` to run.
- Add uid suffix to macOS tmp rdir symlink.
- Other minor tweaks.
I tested dropbear SSH server, which is commonly used for embedded devices as well as network devices.
However, the parameter exceeds the upper limit (9000 bytes).
I tried trimming the bootstrap script and it works fine.
Maybe the comments and indents need to be removed in `prepare_script()`, or just send it via STDIN (--kitten or ssh.conf configuration).
Due to the recent changes, symlink loop error occurs. I solved it by removing the .terminfo folder.
```text
mv: can't stat '/root/./.terminfo/x/xterm-kitty': Symbolic link …
```
> ssh kitten: Improve login shell exec and add uid suffix to macOS tmp rdir symlink

- kittens/icat/main.py
passing tty as TextIOWrapper to screen_size_function results in a TypeError since the screen_size_function expects an int. calling fileno() on tty gives us the desired int. This also fixes the kitty matplotlib backend, if MPLBACEND_KITTY_SIZING is not set to manual
> Fix icat fail on mac with --print-window-size

- kittens/diff/main.py
After switching contexts in diff kitten, scrolling may result in a miscalculation of the number of lines, resulting in a blank drawing.
```text
screen_scroll 147
CSI code H is not allowed to have negative parameter (-115)
```
https://github.com/kovidgoyal/kitty/issues/4831
> diff kitten: Fix wrong number of scrolling lines after context switch

- kittens/ssh/main.py
- kitty_tests/shell_integration.py
- kitty_tests/ssh.py
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
- shell-integration/ssh/bootstrap.py
- shell-integration/ssh/bootstrap.sh
I don't use NetBSD, but I decided to install it for testing. I found an error reported in the terminfo preparation part. .terminfo.cdb is a file and cannot be accessed as a folder. I adjusted the order to make sure that both .terminfo (the folder) and .terminfo.cdb are generated.
dropbear has a 9000 bytes ssh args limit. Remove bootstrap script comments and indents to support connecting to OpenWRT or embedded devices.
Use built-in cwd reporting function name from fish. When the feature enabled by default in future fish versions, this will override the built-in one.
I also just added this (hours ago) and am about to suggest fish to enable this.
Do you think it would be acceptable to turn this on for all versions of kitty? (Obviously there would be at most some error logs, no more harm.) …
> ssh kitten: Reduce bootstrap args to support dropbear, fix NetBSD terminfo, and more

- kitty/window.py
The launch with cwd actions (e.g. `new_window_with_cwd`) uses the configured shell by default.
So when checking it is also compared against the configured shell.
Otherwise, if the action is executed on a window using ssh kitten, the configured shell will be used to open the remote cwd path locally.
https://github.com/kovidgoyal/kitty/pull/4836#issuecomment-1069070364
> Allow launch with cwd to work with ssh kitten when the shell is configured

- kittens/ssh/main.py
- kitty/boss.py
- kitty/utils.py
In macOS 12.3, less has been upgraded to 581.x, which is new enough.
Also check `/usr/bin/less` for lower versions of macOS, which will work when users replace it themselves.
When the sentinel file for SSH version exists, it will no longer be touched, reducing IO.
> Check macOS less version

- docs/shell-integration.rst
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
The PR I submitted has been merged in fish and will enable CWD reporting by default for kitty in the next fish release.
The format is `file://` escaped URL.
> Docs: no-cwd will not disable fish's built-in CWD reporting

- docs/changelog.rst
- kitty/boss.py
- kitty/child-monitor.c
- kitty/cocoa_window.m
Select multiple folders in Finder, right click, and `New kitty Tab/Window Here` in Services will open them all.
Before this PR only the last one will be opened.
https://github.com/kovidgoyal/kitty/pull/4618#issuecomment-1030595767
> macOS: Allow the New kitty Here services to open multiple folders

- glfw/wl_text_input.c
- kitty/fast_data_types.pyi
- kitty/screen.c
- kitty/state.c
- kitty/state.h
- kitty/window.py
Enable the IME under wayland after the window gets focus.
Also fixes the issue that pre-edit text cannot be cleared. After pressing backspace, the last character remains.
https://github.com/kovidgoyal/kitty/issues/4853
> Wayland: Fix IME is not enabled after switching the focus

- kittens/ssh/main.py
- kitty/boss.py
- kitty/rc/scroll_window.py
- kitty/utils.py
- kitty_tests/ssh.py
- shell-integration/bash/kitty.bash
- shell-integration/ssh/bootstrap-utils.sh
Fix ssh kitten URL hostname matching.
Fix bash integration cwd reporting missing hostname.
Fix not specifying the executable path when checking less version.
I noticed that if OSC 7 is output in the sub shell, it will remain after exit (since PWD does not change in the shell).
The only solution would be to unconditionally update CWD OSC7 when outputting PROMPT. 
But I think you have noticed this and have chosen not to do so.
In my opinion the current solution is good enough. I personally don't use many programs or sub shells that output OSC 7, so I don't care.
> ssh kitten: Fix SSH URL hostname matching and other minor tweaks

- glfw/cocoa_window.m
When dragging files with Unicode filenames under macOS, there are issues with path encoding and decoding.
The URL list needs to be escaped.
> macOS: Fix the path encoding issue from drag and drop files

- kittens/hints/main.py
- kittens/show_error/main.py
- kittens/tui/loop.py
- kittens/tui/utils.py
Fix hints kitten overlay ready reporting not enabled.
Report overlay ready in case of no match.
Eliminate flickering when kitten exits in overlay.
There may be cases where robustness needs to be improved.
> Fix hints kitten overlay ready reporting not enabled and eliminate flickering when exits

- docs/changelog.rst
- kitty/boss.py
- kitty/options/definition.py
- kitty/window.py
Refactor clear_terminal to move the functions to Window.
Add a standalone action for scrolling prompt to the top. (corresponds to `scroll_prompt_to_bottom`)
Fix the action not scrolling to the bottom when the screen is scrolled.
Avoid using already defined shortcuts in examples.
> Add standalone action for scrolling prompt to the top and fix scrolling

- docs/faq.rst
The `tic` that comes with macOS 12.3 is from ancient ncurses 5.7 (2008) and does not seem to support reading from /dev/stdin.
> Docs: Add instructions for compiling terminfo under macOS

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
When using Ctrl+C to cancel an unexecuted command, or when entering a command containing a syntax error,
the `fish_prompt` event will not be fired, even if a new prompt has been drawn.
These two events `fish_cancel`, `fish_posterror` will be triggered before the prompt is redrawn (at the beginning of the new line).
Also `fish_prompt` will not be triggered if the buffered prompt is repainted on a new line. For example, bind shortcuts to execute `echo debug; commandline -f repaint`.
However, I think the current way is good enough.
If you want to make sure the prompt carries OSC 133 and handles pipestatus correctly, please let me know. However this will result in more fish code to maintain.
> Shell integration: Mark fish prompt on cancel or syntax error

- docs/changelog.rst
- kitty/child-monitor.c
Fix inactive text alpha always being applied when starting a program with cursor hidden via session.
https://github.com/kovidgoyal/kitty/issues/4928
I'm not sure if there are other places affected, please review, thanks.
> Update cursor focus flag when preparing to render OS window

- kitty/keys.c
The cursor position could be used for determinating the ime popup position.
For the sake of consistent (possible) popup position, we should update
cursor position after rendered text.
> IME: put cursor after rendered text

- docs/changelog.rst
- docs/faq.rst
- kitty/boss.py
Since we can already close other windows in tabs with `close_other_windows_in_tab`, add another action to close other tabs.
> Add a new mappable action close_other_tabs_in_os_window

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
The builtin option from the latest version of fish is not used for now. clone-in-kitty has been tested with fish 3.2.x.
BusyBox env does not support the -0 option. Implemented with fish.
Builtins are heavily used in the scripts that come with fish, and any environment that overrides these builtin, I believe fish will not work properly. No need to guard with `builtin`, simplify the code for future maintenance.
If we use `command`, then `base64` or other commands that is not in the path, e.g. alias or function, will not work.
If builtin or commands don't work, I think `clone-in-kitty` is the last thing to worry about, leaving the user to work it out on their own, rather than rejecting the functions from the normal users.
Remove quotation marks and the trailing `# "`, `# ‘` by escaping …
> Minor refactoring for fish clone-in-kitty and allow use without env -0

- kitty/launch.py
Use new values for SSH environment variables, making sure SSH_TTY, etc. is correct.
Perhaps a configurable filter list (prefix `+` for whitelist item) would allow users to solve these problems on their own.
I'm wondering if we should check the `USER` environment variables matches current user in ssh kitten bootstrap script or when running it locally, and not use them (all env vars) if they (the user) are different. If SSH connects and switches users and then runs clone-in-kitty, the reported environment variables such as HOME, USER, etc. will most likely cause the environment to be abnormal.
> clone-in-kitty: Skip SSH_TTY and other SSH environment variables

- kitty/launch.py
There are also environment variables such as `XDG_*` (and `PATH`) that start with the `$HOME` path when the user is different. These are left to the users to work out.
> clone-in-kitty: Skip some user-related environment variables

- kitty/launch.py
- kitty/options/definition.py
- shell-integration/bash/kitty.bash
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
- shell-integration/zsh/kitty-integration
- Remove CONDA_PREFIX_* env vars
- Remove duplicate PATH entries in fish implementation
- Docs: Mention show_key kitten in send_text docs
Why `KITTY_CLONE_SOURCE_CODE / PATH` are no longer processed after activating venv?
It doesn't seem to conflict?
> clone-in-kitty: Remove duplicate PATH entries and minor refactoring

- docs/binary.rst
- docs/conf.py
The `parsed-literal` in the document does not display the copy button.
Put the install command snippets in `code-block` with string substitution.
I know little about Sphinx. Please review, thanks.
> Docs: Show copy button for installation command snippets

- docs/conf.rst
The question of default configuration has been answered several times.
Mention it at the beginning of the documentation, hopefully users who need it will notice that.
> Docs: Mention again that kitty.conf will be created if not present

- docs/changelog.rst
Add the new option `launch --cwd=last_reported` that was missing from the previous version of the changelog.
> Docs: Add launch --cwd=last_reported to changelog

- docs/glossary.rst
- docs/shell-integration.rst
- kittens/hints/main.py
- kitty/cli.py
- kitty/conf/types.py
- kitty/options/definition.py
Improve clone-in-kitty documentation and fix LANG descriptions
- Reduce duplicate `launch`.
- Add links to python venv and conda.
- Adjust the order of env vars, `.._CODE` takes precedence over `.._PATH`.
- Add clone-in-kitty env vars to glossary.
- Correct the description of the LANG env var.
Minor tweaks to the help documentation of hints kitten
Minor improvements to the kitty cli help documentation
- Add some text roles.
- Use `kitty --hold`.
- Use `appname` and `conf_name`.
- `appname` is also applied to the system-wide configuration path.
Improvements to the configuration documentation
- Slightly adjust and simplify the config option descriptions.
- Add more text roles.
- Initial capitalized key names.
- Change some examples to better demonstrate configurations.
- Fix listen_on …
> Docs: Improvements to the configuration documentation

- docs/faq.rst
- docs/glossary.rst
- docs/kittens/ssh.rst
- kittens/ssh/options/definition.py
- kitty/conf/types.py
- kitty/launch.py
- kitty/options/definition.py
Add more text roles and links.
Put the ssh kitten env example at the end.
The `alias` syntax of fish and bash requires quoting.
Document `SSH_ASKPASS`, `PATH` in the glossary.
Adds text to the text role.
Improve code containing spaces in commented configuration.
clone-in-kitty: Skip more SSH env vars to use the correct values.
> Docs: Improve the docs for ssh kitten, FAQ and config

- kitty/conf/types.py
Comment out multi-options that have no default values.
Anyone who has downloaded the sample kitty.conf will get errors when running, just that the new ssh kitten exposes the problem.
This is the cause of the following issue.
https://github.com/kovidgoyal/kitty/issues/4985
> Fix the generated sample kitty.conf containing invalid options

- docs/basic.rst
- docs/binary.rst
- docs/build.rst
- docs/color-stack.rst
- docs/conf.rst
- docs/deccara.rst
- docs/desktop-notifications.rst
- docs/glossary.rst
- docs/integrations.rst
- docs/kittens/hints.rst
- docs/kittens/query_terminal.rst
- docs/kittens/ssh.rst
- docs/kittens_intro.rst
- docs/launch.rst
- docs/layouts.rst
- docs/marks.rst
- docs/overview.rst
- docs/performance.rst
- docs/protocol-extensions.rst
- docs/quickstart.rst
- docs/rc_protocol.rst
- docs/shell-integration.rst
- docs/underlines.rst
- docs/unscroll.rst
- kittens/ssh/options/definition.py
- kitty/boss.py
- kitty/launch.py
- kitty/modes.h
- kitty/parser.c
- kitty/rc/base.py
- Mention close_shared_ssh_connections in ssh kitten config docs.
- Document the env vars set by kitty for auto shell integration.
- Add more text roles and links.
- Fix typos.
- Adjust the default shortcut order in overview.
- Notes on the impact of kitty-open.desktop on the default open apps.
- Document KITTY_DEVELOP_FROM in glossary.
- Add Python type hints to the watcher example.
- Mention clone-in-kitty in launch --copy-env.
- Fix remote control ls example does not work, by escaping the backslash.
I believe this is almost the last batch, there are still `*-protocol.rst` left.
> Docs: Improve the documentations

- kitty/rc/create_marker.py
- kitty/rc/scroll_window.py
I'm not sure how a `send-text` without a match should be handled properly.
If we simply check for empty matches, does that affect the broadcast function?
It seems that broadcast can first match an empty range, e.g. a focused tab with no windows (which should not report an error at this point), and later works for newly opened windows in the focused tab.
> Show error message when remote command arguments are invalid

- kitty/boss.py
- kitty/rc/create_marker.py
- kitty/rc/detach_tab.py
- kitty/rc/detach_window.py
- kitty/rc/get_colors.py
- kitty/rc/get_text.py
- kitty/rc/kitten.py
- kitty/rc/launch.py
- kitty/rc/new_window.py
- kitty/rc/remove_marker.py
- kitty/rc/resize_os_window.py
- kitty/rc/scroll_window.py
- kitty/rc/send_text.py
- kitty/rc/set_background_image.py
- kitty/rc/set_background_opacity.py
- kitty/rc/set_colors.py
- kitty/rc/set_spacing.py
- kitty/rc/set_window_logo.py
- kitty/rc/set_window_title.py
- kitty/rc/signal_child.py
DRYer: Use window matching function in remote commands
Fix remote command --match=all returns empty
(E.g. `kitty @ send-text --match=all 1`)
Raise an exception when not in broadcast and no match for send-text
send-text is currently send-and-forget, and if we change no_response to False, it might break backwards compatibility.
I have not made this change.
> DRYer for rc window matching and fix --match=all

- kittens/hyperlinked_grep/main.py
From the manual:
```
-p, --pretty                                 
This is a convenience alias for '--color always --heading --line-number'. This
flag is useful when you still want pretty output even if you're piping ripgrep
to another program or file. For example: 'rg -p foo | less -R'.
```
Took me a while to figure out that it's the kitten at fault and not less lacking hyperlink support :)
> Support the short pretty flag (-p) in hyperlinked_grep kitten

- kitty/parser.c
[Fig](https://fig.io) uses OSC 697 for its shell integrations, currently Kitty reports this as `[PARSE ERROR] Unknown OSC code: 697`, this PR will simply suppress those errors.
> Ignore Fig OSC codes

- kitty/fast_data_types.pyi
- kitty/state.c
Thanks for discussing the issue with me and giving many hints on possible solutions.
This PR exposes `wakeup_main_loop` to the python api in similar fashion as `mark_tab_bar_dirty`.
> Expose wakeup main loop in python api.

- kitty/conf/utils.py
`Path.glob` gives no guarantee about the order results are returned in.
This means that if files included by `globinclude` override each other,
the resulting config was non-deterministic. Resolve this by sorting the
results from `glob` to give consistent, well-defined order.
> Make globinclude sort files before loading

- docs/changelog.rst
- kitty/rc/launch.py
When the match argument is provided, an error will be reported if there is no match.
This does not seem to break backward compatibility.
Fixes #5210
> Allow remote control to launch a new OS window when there is none

- docs/faq.rst
This is a request to add to the alternative app icons list on the FAQ.
> Add "modern whiskers" alternative icon to FAQ

- docs/graphics-protocol.rst
Hello! 😃
I've just released a [new version](https://github.com/AnonymouX47/term-image/releases/tag/v0.4.0) of my project [term-image](https://github.com/AnonymouX47/term-image) with kitty graphics support.
> Add `term-image` to projects using kitty graphics protocol

- kitty/screen.c
- kitty_tests/screen.py
When getting the output of a command that is not yet finished (no next prompt), one line is missing when counting the number of lines.
```shell
echo -n "running" && sleep 5
```
> Fix missing last line when getting output of the running command

- docs/graphics-protocol.rst
Missed in 3eb5320e297c8de4bad8ff2bab62bb8fceaebe77
> Fix link formatting in docs

- kitty/fonts.c
Slight change to improve performance and readability 
Found this in recent commit a1f895b7810ed3ff1a8a93fd41b773c51695ec1f
> Convert unnecessary while loop into if statement

- docs/glossary.rst
Just a typo in the docs. Kitty is great, thanks for all the hard work.
> Fix doc typo: throught to throughout

- glfw/cocoa_window.m
Allow "Speak selection" (Option+Esc) to work properly.
Thanks for the last building block.
Fixes https://github.com/kovidgoyal/kitty/issues/5357
Minor improvements for code style:
Use spaces as indentation consistently.
EDIT:
The improvements about indentation have been picked to the master branch.
https://github.com/kovidgoyal/kitty/commit/06108d66b14c78456268622be285e7e5b11feb12
https://github.com/kovidgoyal/kitty/commit/0d116e6ef0f176bec053907920dd9c3655113562
> Implement macOS accessibility protocol to provide selected text

- kitty/tabs.py
In previous versions, `launch --allow-remote-control` was used to allow remote control with TTY in the window.
The following use case is supported in both windows. (previously supported)
```shell
kitty -o allow_remote_control=socket-only
kitty @ launch --allow-remote-control
kitty @ launch
```
```shell
kitty @ --to "$KITTY_LISTEN_ON" ls
```
This PR will only stop setting `KITTY_LISTEN_ON` when using the new launch option `--remote-control-password`, without breaking backwards compatibility.
---
In the future it might be possible to add window id+passwd authentication for socket.
> If you send your remote control over the socket, there is no associated window,
> so window based passwords cannot work. This is a technical limitation ...
```shell
kitty @ launch …
```
> Only when using the new remote control password option KITTY_LISTEN_ON is no longer set

- docs/build.rst
- docs/changelog.rst
- docs/glossary.rst
- kittens/show_key/main.py
- kitty/kittens.c
- kitty/options/definition.py
- kitty/remote_control.py
- Env var `KITTY_PREWARM_SOCKET` may need to be unset.
- Improve the list of data names in the commented config file for `tab_title_template`.
- Use the plus sign to connect shortcut keys consistently.
> Docs: Some improvements to the docs for recent changes

- glfw/cocoa_window.m
Check for >= 10.14 using Availability.h to use the accessibilityRole
callback which does not seem to be available in 10.13.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
I'm getting some test failures, I will try to look at that in a separate PR.
> Fix build on macOS High Sierra

- docs/extract-rst-targets.py
- docs/remote-control.rst
- kitty/boss.py
- kitty/cli.py
- kitty/conf/types.py
- kitty/constants.py
- kitty/launch.py
- kitty/options/definition.py
- kitty/window.py
- Using the lowercase form of the key name consistently.
- Use kitty --help long option name in the document.
- Remove the extra empty line in the CLI help for `--replay-commands`.
- Fix GitHub links in commented configuration.
- Shorten the reference link to the top of the page. (E.g. `https://sw.kovidgoyal.net/kitty/shell-integration/`)
- Hyperlink doc text role.
- Fix doc website URL with duplicate slashes.
- Unify the list style of available values.
---
There are still some unresolved issues.
Text role: The line after the line break fails to be highlighted in color.
For example, see the `--color` description in `kitty @ launch --help`.
Not so sure the same problem exists with italics and other styles.
Can't get the document title, the `:doc:` link is weird.
See `kitty @ launch …
> Some fixes and improvements to the documentation

- shell-integration/bash/kitty.bash
Some bash versions may not have that option and rather than checking if
they even have it or if it is set, just quiet the STDERR it may throw.
```
$ kssh myhost
bash: shopt: inherit_errexit: invalid shell option name
myhost:~$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
> bash shell integration: Send STDERR of unsetting inherit_errexit to /dev/null

- docs/kittens/hyperlinked_grep.rst
- kittens/hyperlinked_grep/main.py
If it's active, only matching lines get links, not file headers or context lines.
I have a kitten that steps through the links it finds to open them like "Find Next" when searching for text in a browser. It's way more useful if the links are only to the lines the search hits, which is what this flag enables.
> Add a --hyperlink-only-matches flag to hyperlinked_grep

- kittens/hints/main.py
- kitty_tests/hints.py
For URLs where there's fewer characters left to the right edge of the
window than the number of escape characters in the line, the next line
would be included in the URL, as if the URL went all the way to the
right edge.
For example with a 40 chars wide terminal, if you run:
echo -e '\e[31m1\e[m https://github.com/kovidgoyal/kitty\ntest'
And launch the hints kitten, you'll see that test on the next line will
be included in the URL.
This happened because the calculation for filling the rest of the line
with NUL characters counted the escape characters as well as the visible
characters, so it filled in too few characters.
This is a regression introduced in commit 91966712.
> Fix hints sometimes matching next line as part of URL

- docs/faq.rst
- kitty/cli.py
- kitty/launch.py
- kitty/rc/launch.py
- kitty/rc/new_window.py
- kitty/rc/set_background_opacity.py
- kitty/rc/set_colors.py
- Mention clear_all_shortcuts in the FAQ about show_key kitten.
- Remove the extra empty line in the CLI help and keep the example code in a code block in the HTML docs.
- Put example commands in code blocks.
This PR will show `for example::` as `for example:` in the CLI help.
Previous discussion:
https://github.com/kovidgoyal/kitty/pull/5409
> Text role: The line after the line break fails to be highlighted in color.
> ... the same affects hyperlink.
>
>> That's a bug in less where it resets styles at newlines.
Thanks for the explanation. The affected texts I mentioned are all indented, and I don't think indents (spaces) should contain styles, such as hyperlink's underline.
> I'm afraid I am not interested in changing that, it makes wrapping code much more complex, ...
So I manually put …
> Docs: Mention clear_all_shortcuts in the FAQ and improve the rendering of example code in CLI and HTML docs

- docs/binary.rst
- kitty/rc/focus_tab.py
- kitty/rc/focus_window.py
- kitty/rc/last_used_layout.py
The user should be able to execute the installation command correctly when copying (e.g. pressing the Copy to Clipboard button) on the document page.
https://sw.kovidgoyal.net/kitty/binary/#customizing-the-installation
Also add the missing no_response for some remote control commands.
> Docs: Remove the extra backslashes from the install commands

- docs/changelog.rst
- docs/faq.rst
- kitty/cocoa_window.m
- kitty/fast_data_types.pyi
- kitty/main.py
Changing the kitty icon manually as described in the FAQ is troublesome, so a new way to set custom icons via the CLI has been added.
Configure custom icon for the app bundle directly by calling the Cocoa framework's API.
Related discussion:
https://github.com/kovidgoyal/kitty/issues/5461
This PR does not fix the above issue because it does not yet add to the installer script the steps to: detect the presence of custom icon, backup, restore custom icon, etc, as this would add unnecessary complexity to the installation script.
I noticed the following commit, does that mean that using `doc` text roles without the `slash /` prefix is no longer supported?
https://github.com/kovidgoyal/kitty/commit/295743a96e21ffe5fadb67e2336effc140e29798
```text
:doc:`launch` -> …
```
> macOS: Add a way to set a custom application icon for kitty

- glfw/x11_window.c
XChangeProperty takes the number of items instead of the size of the data.
> Fix clipboard target properties and memory leak

- kitty/layout/splits.py
I haven't looked deeply, but this looked to be a simple typo unless it's checking one both times because of a type invariant. If that is the case, and the check is correct, then a comment and/or code refactoring to call attention to this would likely be a good idea.
> Check correct pair member

- glfw/wl_text_input.c
1. Only update preedit if preedit changed.
2. Only send cursor update if cursor position is not changed.
> Fix message recursion between wayland compositor (#5360)

- kitty/cocoa_window.m
- kitty/main.py
Failure to set custom app icon should not prevent launch.
When running `kitty/launcher/kitty` and no bundle path is provided, the icon of `kitty/launcher/kitty.app` should be changed instead of the `launcher` folder.
> macOS: Failure to set custom app icon should not prevent launch

- shell-integration/fish/vendor_completions.d/clone-in-kitty.fish
- shell-integration/fish/vendor_completions.d/edit-in-kitty.fish
- shell-integration/fish/vendor_completions.d/kitty-tool.fish
I also noticed that `kitty --help` and `kitty-tool --version` etc. are not listed.
For `kitty-tool`, it looks like `kitty-tool update-self` should not take effect under macOS, as it will break the signature of the entire application bundle.
I think it's best to run `kitty +update-self` to update the whole macOS bundle.
If anyone is interested in implementing this, replace the package downloaded via `kitty +update-self` the next time the user launches kitty via launchd, and run kitty again when the upgrade is complete.
Updates will not take effect when running kitty via CLI or `open` to avoid complications with handling envs, stdin, args, etc.
> Fix completion for fish

- gen-go-code.py
Hope I didn't miss anything, please review, thanks.
There are still some subcommands for internal use and `+icat` missing completion.
```text
+complete +edit +edit-config +hold +icat +shebang
```
> Add completion for kitty +list-fonts

- kitty/graphics.c
Otherwise some editors/plugins get confused
> Define END_ITER to prevent brace imbalance

- kittens/diff/main.py
- kittens/themes/main.py
- kittens/tui/line_edit.py
- kittens/tui/operations.py
I noticed that `set_cursor_shape('beam')` is used in ask kitten, however there is no such value (it will be set to **block** shape).
I remember asking you before whether it was `bar` or `beam`, and your choice was to maintain backward compatibility using `beam`.
So do the same in this PR.
No alias `bar` is provided to keep the code maintainable, rather than a mix of names.
> Refactor: Use a consistent name for beam cursor shape

- docs/conf.rst
- kitty/options/definition.py
- kitty/rc/send_text.py
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Send-arbitrary-text-on-key-presses
https://sw.kovidgoyal.net/kitty/remote-control/#kitty-send-text
Two backslashes are needed in Python, and two backslashes are needed in the generated rst, for a total of four.
However, `kitty-tool @ send-text --help` ends up with an extra backslash, and needs a little help here.
> ... The text follows Python escaping rules. ...
Also I noticed that `send-text -m id:1 "\x7f"` worked fine in the previous version of the kitty shell, but now it doesn't escape and send properly in the version implemented in Go.
When a command is executed without any output, a blank line is output in the kitty shell, while in previous versions the behavior is the same as in the regular shell, which prints the next prompt if …
> Docs: Fix missing backslashes

- kittens/hyperlinked_grep/main.py
- kitty/cli.py
- kitty/utils.py
- kitty/window.py
The cached hostname cannot be used in `open_url` as it may have been changed.
---
About launching with current cwd, I found an issue.
```shell
kitty --config=NONE -d=/tmp -o 'shell zsh' -o 'map f1 new_window_with_cwd'
ssh ksi-enabled-remote
```
After ssh disconnects, create a new window with the current cwd, which will then use the remote cwd.
The remote path probably does not exist locally and the shell starts at `/`, which is annoying.
I can think of a few ways to improve this user experience.
Check if the hostname matches the local hostname before `return reported_cwd`.
```python
def hostname_from_osc7_url(url: str) -> str:
netloc = ''
if url.startswith('kitty-shell-cwd://'):
netloc = url.split('/', 3)[2]
if url.startswith('file://'):
from urllib.parse import urlparse
netloc = …
```
> DRYer: Get hostname

- docs/changelog.rst
- kitty/options/definition.py
The new option will limit the tab visual width instead of the number of characters.
Place this new option alongside the tab title related ones for convenience.
Log the missing associated GitHub PR in the changelog.
> Docs: Slightly adjust the description of tab_title_max_length add the associated PR to changelog

- kitty/conf/types.py
- kitty/conf/utils.py
- kitty/options/definition.py
Remove extra backslashes from commented config.
Update docs to use `\e` in the example.
Fix the base path for envinclude.
```log
TEST='include target.conf' kitty -o 'envinclude TEST'
Could not find included config file: ~/.config/target.conf, ignoring
```
Do you think the base path in all environment variables should default to the kitty config file path regardless of where the config file uses envinclude?
So in the following example the `target.conf` file in the configuration folder will be loaded instead of `a/b/target.conf`.
```shell
TEST='include target.conf' kitty -o 'include a/b/envinclude-test.conf'
```
The current logic is equivalent to inserting environment variables as configuration lines into the line where `envinclude` is located, which is also understandable and reasonable …
> Fix the base path for envinclude and minor docs improvements

- docs/kittens/hyperlinked_grep.rst
- kittens/hyperlinked_grep/main.py
Previous discussion:
https://github.com/kovidgoyal/kitty/discussions/5742
If some options are disabled and then enabled by an option with another name (e.g. disabling file path output and then enabling it), they will not take effect.
I don't bother to deal with these cases specifically.
Also the configuration file is not currently parsed, so this will not apply to the case where the options are written in the configuration file.
> hyperlinked_grep kitten: Handle more rg command line options

- docs/kittens/hyperlinked_grep.rst
- kittens/hyperlinked_grep/main.py
URLs starting with `file://` should be used instead of paths.
Also I noticed in the recent FAQ update:
> Here X will the keys you press on the keyboard.
Is there a typo here?
> hyperlink_grep kitten: Fix the hyperlinks when listing files

- kitty/rc/launch.py
I don't quite remember where the option values defined here are used.
It looks like the protocol specification here is used in gen-go-code.py, but is not reflected in features like completion (which uses option_spec).
> Remote control: Add the missing option value overlay-main

- kitty/keys.c
Verified on Debian's hppa porterbox.
Closes #5802
> Define SingleKey bitfields according to endianness

- shell-integration/ssh/bootstrap-utils.sh
- shell-integration/ssh/bootstrap.sh
Allow programs that depend on terminfo.cdb as well as programs installed via pkgsrc that depend on the new version of ncurses to run.
When the program fails with `~/.terminfo.cdb` as specified by TERMINFO, it will fall back to `~/.terminfo/x/xterm-kitty` compiled with the new version of tic.
Fixes #5814
There is also a related problem, not limited to NetBSD, if the user compiles `~/.terminfo/x/xterm-kitty` with the new version of tic (`/whatever/path/to/tic`) and programs rely on the new version of ncurses, it will not work by default because ssh kitten overwrites terminfo unconditionally.
Should we check that `~/.terminfo/x/xterm-kitty` is older than `kitty.terminfo` before compiling and overwriting?
I don't really think too many checks should be added, as this can …
> ssh kitten: Compile terminfo with tic coming from pkgsrc under NetBSD

- kitty/graphics.c
- kitty_tests/graphics.py
This commit fixes an off-by-one error in image scrolling that caused images to not be scrolled or to be cropped at the wrong line.
> Fix scrolling images within margins

- kitty/boss.py
- kitty/fast_data_types.pyi
- kitty/glfw.c
- kitty/key_encoding.c
- kitty/key_encoding.py
- kitty/keys.c
- kitty/keys.h
Fix #5840
Applications that use key sequences:
* tmux works, tested by the `Ctrl+b>c` case in #5840 
* vim works, tested by `inoremap <C-b>e abcde` in vimrc
* modifier sequence is replayed correctly: https://github.com/kovidgoyal/kitty/pull/5841#issuecomment-1368175233
> Send sequence events to child if they don't match kitty.

- docs/open_actions.rst
- kitty/open_actions.py
When `shell` is configured as `bash --login`, `kitty +shebang $FILE_PATH $SHELL` will not work.
The PR fixes this.
- Only the executable path is used when expanding `$SHELL`.
- Also fix the non-working example `{SHELL}` in [the documentation](https://sw.kovidgoyal.net/kitty/open_actions/#scripting-the-opening-of-files-with-kitty-on-macos).
I actually tried to fix the problem of not being able to open image files with kitty under macOS.
However I don't know when the next version will be released, so it's better to let you know.
Steps to reproduce:
- Right click on the image file to open it via kitty.app, or drag and drop the file onto the Dock.
- Or run `kitty @ launch --type=os-window kitty +kitten icat --hold /path/to/image`.
- The new process ends and the new OS window is immediately …
> Fix SHELL env var in open-actions.conf and launch-actions.conf

- docs/graphics-protocol.rst
- kitty/options/definition.py
Although Go uses tab indentation by default, for consistency, space indentation is used in the source code of the documentation.
Anyone who has copied the code directly can format it themselves with gofmt.
> Docs: Fix mixed tab and space indentation in the example code

- kitty/options/utils.py
- kitty/rc/create_marker.py
The following will not work after recent commit.
```shell
kitty @ create-marker function mymarker.py
```
So revert that commit.
The `mark group` is used in the documentation to refer to that integer in the specification, so replace `color` with this in the error message to be consistent.
Fix `No color` error message when text is missing, e.g. `text 1`.
Related GitHub Issue:
https://github.com/kovidgoyal/kitty/issues/5937
> Only two arguments are required to create a marker

- tools/cmd/at/shell.go
- tools/cmd/completion/kitty.go
- tools/cmd/update_self/main.go
- The fix from a previous PR that was submitted but not merged, duplicate subcommand name `update-self` in usage.
- Show `help` in the kitty shell help, just for completeness.
- Adds a text role to the available value to apply the color.
- Use the current version in the example, so you don't need to maintain this every time you update the version in the future, otherwise it will look outdated.
> Docs: Improve usage and help documents for kitten

- kitty/launch.py
Forgot to remove the text role target when changing `term` to `code`.
> Docs: Remove the text role target that is no longer needed

- shell-integration/bash/kitty.bash
- shell-integration/zsh/kitty-integration
Currently `builtin return` is already being used in the script, so add `builtin` for the rest.
> Shell integration: More builtin commands

- glfw/dbus_glfw.c
- glfw/wl_window.c
- kittens/choose/unix_compat.c
- kitty/cursor.c
- kitty/gl-wrapper.h
- kitty/gl.c
- kitty/line.c
- kitty/mouse.c
- kitty/state.c
Fixes clang error:
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
> Use strict function prototypes

- kitty/screen.c
- kitty/screen.h
Fix the bug when IME uses single key to confirm and update pre-edit text.
- Correctly update the overlay position when cursor visibility changes.
- Restore the overlay line only when the cursor is visible.
- Clear the saved overlay when drawing new pre-edit text.
- Also update the cursor position when screen size changes.
- Use four spaces to indent instead of two.
When IME confirming text with a single key and updating the pre-edit text, the overlay is drawn at the initial x coordinate since the cursor position is not updated. Saving the overlay at this point will deactivate it and update cursor->x.
When deactivated, the line is marked as dirty and immediately redrawn, and it will appear that the confirmed text is drawn after the current pre-edit text.
So when the confirmed text is …
> IME: Fix IME commit text and update pre-edit at the same time

- .gitignore
- docs/changelog.rst
- docs/conf.py
- kitty/options/definition.py
Almost forgot about this.
https://github.com/kovidgoyal/kitty/discussions/5978#discussioncomment-4862564
>> Should we keep the comment ...
>> This will make it consistent with what ctrl+shift+f2 generates.
>
> Yeah, makes sense.
When I updated to the latest, the font was too thick since I configured `macos_thicken_font`.
Also mention this in the changelog, otherwise it is less likely to be noticed in the configuration comments or documentation.
Would you mind updating the following part of the documentation to mention `kitten` implemented in Go? Thank you.
https://sw.kovidgoyal.net/kitty/overview/#design-philosophy
> It is written in a mix of C (for performance sensitive parts) and Python (for easy hackability of the UI).
> Docs: Generate commented sample conf files and other minor improvements

- docs/changelog.rst
- glfw/cocoa_window.m
When the window title bar is configured to be hidden, the window control buttons should be displayed on the auto-hide title bar instead of a blank title bar when going to full screen.
When full screen is in traditional mode, hide the window button after exiting full screen.
Fixes https://github.com/kovidgoyal/kitty/issues/6009
It may still report `ruff` errors, but I don't bother to add an explicit E704 ignore.
> macOS: Update window button visibility after toggling full screen

- docs/changelog.rst
- kittens/transfer/utils.py
- kitty/boss.py
- kitty/guess_mime_type.py
- When reloading configuration, also reload `mime.types`
- transfer kitten: Use guess_type with custom MIME
After modifying `mime.types`, reloading the configuration will take effect immediately without having to end the kitty process and restart it.
> Reload mime.types custom MIME config

- kitty/fast_data_types.pyi
I wanted to add types to my kitten using this function, and realized it was missing.
> Add send_mouse_event to fast_data_types.pyi

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- docs/build.rst
- docs/changelog.rst
- docs/conf.py
- kitty/options/definition.py
No need to update multiple places when bumping the go version.
Also bump versions of the deprecated github actions to the latest.
> Get go version from go.mod

- setup.py
Add x-scheme-handler/ssh to mimetypes so that kitty open can be used to open ssh links by default.
> Add x-scheme-handler/ssh to mimetypes

- docs/changelog.rst
- docs/overview.rst
- glfw/cocoa_window.m
- kitty/boss.py
- kitty/fast_data_types.pyi
- kitty/glfw.c
- kitty/launch.py
- kitty/main.py
- kitty/session.py
- kitty/state.c
- kitty/state.h
- kitty/utils.py
- Fix the maximized window not taking up full space when the title bar is hidden or when `resize_in_steps` is configured.
- Display the newly created OS window in specified state to avoid or reduce the window transition animations.
- Allows to specify `os_window_state` in startup session file.
Various combinations of configuration option values that I can think of have been tested.
I'm not quite sure how to create a window with the specified state directly under wayland and x11, so I left it untouched.
If it can be started in various states, rather than created and then changed, then the first time the window is restored to the normal state it needs to be restored to the remembered window size or the configured fixed size, and `resize_in_steps` should be applied.
Fixes …
> macOS: Fix the maximized window not taking up full screen space and other improvements

- kitty/screen.c
This PR fixes a bug when images appear in wrong places when switching from the alternate screen back to the main screen.
Not sure if it's the best way to fix the bug though, maybe there is actually a deeper problem underlying it.
To reproduce the bug:
1) Display an image `kitten icat logo/kitty.png`
2) Switch to the alternate screen `tput smcup`
3) Display another image (it should be in a different position or have a different size)
4) Switch back to the main screen `tput rmcup`
Image 1 will appear in the wrong location (actually in the location of image 2).
> Fix image distortion when switching between screens

- docs/changelog.rst
- glfw/cocoa_window.m
- glfw/glfw3.h
- glfw/init.c
- glfw/internal.h
- kitty/child-monitor.c
- kitty/glfw-wrapper.c
- kitty/glfw-wrapper.h
- kitty/glfw.c
- kitty/keys.c
- kitty/screen.c
- kitty/screen.h
- kitty/shaders.c
Render overlay at the last visible cursor position with a separate cursor.
Fix the problem caused by wrong cursor coordinates. No more messing with the main cursor, instead the cursor is saved when receiving a pre-edit text update and used for drawing later.
Update the overlay to the last visible cursor position before rendering to ensure it always moves with the cursor. Finally, draw the overlay after line rendering is complete, and restore the line buffer after updating the rendered data to ensure that the line text being read is correct at all times.
This also improves performance by only rendering once when changes are made, eliminating the need to repeatedly disable and draw after various commands and not even comprehensively.
Allow IME to actively get the cursor position in real …
> IME: Render overlay at the last visible cursor position and improvements under macOS

- glfw/cocoa_window.m
- Fix resize_in_steps being applied when double-clicking on the title bar to maximize the window.
- Add comments to explain how to get the services related methods to be called and restore IME pre-edit text after inserting text from the service.
I've found one more annoying issue.
Using `launch --dont-take-focus` (`--keep-focus`) to create a new window, the `on_focus` callback will still be called. And there are four of these, the current window's as well as the new window, in and out.
And the side effect is not only this, it also causes IME composition to be cancelled.
I think any operation that creates, removes, changes the active window of an inactive tab, etc. should not trigger `on_focus_changed` as long as it does not actually change the current focus.
If you don't have time to …
> macOS: Fix double-click the title bar to maximize the window does not occupy the full screen and others

- .editorconfig
According to https://editorconfig.org/#file-format-details:
> indent_style: set to tab or space to use hard tabs or soft tabs respectively.
Apologies if this is known and the previous `spaces` syntax is preferred. In that case of course please just close the PR.
Thanks for kitty :cat:
> fix typo in .editorconfig

- docs/overview.rst
This fixes a small typo in `overview.rst`. "Come in" was spelled "comein".
I had to shift the lines around a bit to maintain the 80 character width.
> Fix typo in overview doc

- kittens/show_error/main.py
- kitty/rc/set_background_image.py
- kitty/rc/set_window_logo.py
- kitty/utils.py
When running `. /tests.py mypy`, it shows the following message and fails (exit code 1).
```log
DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
```
I noticed that the relevant remote control commands cannot be executed via shortcuts.
```shell
kitty -o 'map f1 remote_control set-window-logo /path/to/png'
```
```log
kitty.rc.base.StreamError: No stream_id in rc payload
```
Since this is related to the remote control protocol, could you update the documentation if you have some time? (And maybe the async part, such as `async_id`)
https://sw.kovidgoyal.net/kitty/rc_protocol/
The detailed traceback is printed before the `Press e to see detailed traceback ...` line. This minor issue is not important.
I see the use of `NamedTemporaryFile` in setting the …
> Replace the deprecated imghdr module

- docs/changelog.rst
- kitty/screen.c
- kitty/screen.h
Right align overlay when typing at the edge of the screen.
When the cursor is at the right edge of the screen, push the overlay to the left to display the pre-edit text just entered.
Some of the combining characters may be cut off at the beginning of the line, but it doesn't matter.
This is one of the last two IME-related issues I'd like to fix.
> IME: Fix overlay rendering when the pre-edit text to be displayed exceeds the screen

- docs/faq.rst
- nerd-fonts-glyphs.txt
- tools/unicode_names/names.txt
Nerd Fonts started migrating symbols from the misused region to the Unicode plane 15 private area.
This version contains both areas to ease the transition.
https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3
https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.0
> The old codepoints will be dropped with v3.0.0 because they are wrong/forbidden and cause a lot of problems for people that use non-latin letters. The old codepoints are F500 - FD46. The new codepoints are F0001 - F1AF0.
> Update to Nerd Fonts 2.3.3

- tools/tui/hold.go
Also consider the Enter key on the numeric keypad to be a valid key for exiting.
> hold: Allow pressing the numeric keypad enter key to exit

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Moving the operation of removing whitespace characters to the function that transmits the data.
This matches the implementation in zsh and bash integration scripts.
> Refactor: Remove newlines from the data in fish __ksi_transmit_data

- kittens/ssh/main.py
It looks like this was copied from the unicode input kitten and forgotten to modify it.
I also found another issue.
It reports an error after pressing the default shortcut `ctrl+shift+p>w`.
```log
... error parsing regexp: invalid or unsupported Perl syntax: `(?u`
```
tools/cmd/hints/marks.go
```go
... `(?u)[%s\pL\pN]{%d,}` ...
```
> Fix typo in ssh kitten

- kittens/runner.py
When pulling a git commit that contains delete folder actions, the local folders will not be deleted.
After pulling the latest master branch, the build fails.
```log
python3 setup.py kitty.app 
...
ImportError: No module named kittens.choose.main
make: *** [app] Error 1
```
> Fix empty folders being considered as kitten

- docs/installer.sh
- shell-integration/ssh/kitten
- shell-integration/ssh/kitty
This accommodates FreeBSD and perhaps others.
The change in `shell-integration/ssh/kitten` is the only one that matters; the other changes only run for Linux which, as far as I know, consistently uses "x86_64". But it's probably a good idea to keep all machine detection code more or less the same.
> Add "amd64" as a potential value for "uname -m"

- kitty/data-types.h
- kitty/desktop.c
- kitty/glfw.c
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/types.py
- kitty/state.h
Based on #2125. The default sound theme is `__custom`, which is the custom theme created by GNOME and Budgie. If this theme doesn't exist, canberra instead uses the default theme to produce the sound, so it should work without a hitch on all desktop environments.
This is a draft because I was unable to figure out how to regenerate `to-c-generated.h` to get the changes to propagate, and it seems that the code to add a new option changed in the time between #2125 and now. Let me know how to get everything connected and I'll get it ready to merge.
> Add option to set XDG sound theme on Linux

- kitty_tests/ssh.py
- shell-integration/ssh/bootstrap.py
More or less [the same issue already solved][1], where `getpwuid()` fails and raises a `KeyError` exception because the effective user ID isn't listed in the `/etc/passwd` file. The exception then directly fails the test before workarounds can be applied.
[1]: https://github.com/kovidgoyal/kitty/commit/89e5ae28bb60d5bf3aaadf25d62ea0864e5136bb
> Suppress getpwuid() exceptions

- kitty_tests/ssh.py
- shell-integration/ssh/bootstrap-utils.sh
- shell-integration/ssh/bootstrap.py
This properly fixes https://github.com/kovidgoyal/kitty/pull/6118 that I submitted earlier. Starting another PR to fix a PR generally shouldn't happen and I am sorry for my negligence. Please feel free to make changes or clean up the commit. Thanks.
kitty_tests/ssh.py
------------------------
`suppress(Exception)` actually suppresses the `SkipTest` exception raised by `self.skipTest(...)`, making the call useless. The program then proceeds to line 181 and throws an `UnboundLocalError` exception because `expected_login_shell` is never defined in the `try` clause.
shell-integration/ssh/bootstrap-utils.sh
----------------------------------------------
This is a spot making use of `getpwuid()` that I missed. The `exec()` is an ugly workaround but it is hard to wrap `try` and `catch` clause in …
> Rework of "suppress getpwuid() exceptions"

- shell-integration/ssh/bootstrap-utils.sh
> bootstrap-utils.sh: make grep silent

- docs/graphics-protocol.rst
Hi, 
The project [twitch-tui](https://github.com/Xithrius/twitch-tui) now uses the kitty graphics protocol.
> Add twitch-tui to projects using the kitty graphics protocol

- docs/integrations.rst
Just a minor issue in the docs, but [here document delimiters should not include trailing spaces](https://tldp.org/LDP/abs/html/here-docs.html#:~:text=The%20closing%20limit%20string%2C%20on%20the%20final%20line%20of%20a%20here%20document%2C%20must%20start%20in%20the%20first%20character%20position.%20There%20can%20be%20no%20leading%20whitespace.).
The `iplot` function snippet includes leading spaces before `EOF` , so if you run it as is you'll run into some issues.
<details>
<summary>Leading spaces included screenshot</summary>
</details>
Removing the leading spaces fixes this
<details>
<summary>Leading spaces removed screenshot</summary>
</details>
> Docs: fix heredoc issue in iplot snippet

- glfw/cocoa_init.m
- glfw/cocoa_monitor.m
- kitty/cocoa_window.m
- kitty/core_text.m
- kitty/data-types.c
- kitty/macos_process_info.c
Building on macOS 13.3.1 (22E261) clang 14.0.3 (clang-1403.0.22.14.1)
running to errors like #5477 where functions without argument lists at
least need void.
Looking for possible suspect functions via:
git grep -E "^([A-Za-z_]+ )?[A-Za-z_]+\()" \*.c \*.m
> More cases of #5477 functions with empty argument lists

- kitty/cell_fragment.glsl
This PR fixes #6209 by adjusting the alpha channel to account for gamma-incorrect blending performed by the compositor when background_opacity is < 1.0. At least wlroots, picom, GNOME, and MacOS perform gamma-incorrect blending by default with transparent windows.
It also includes a more precise sRGB-linear conversion to pretty much eliminate fringing completely.
This PR will however cause the following issues when using a transparent background:
* Some text will appear bolder, depending on the foreground color, the background, and the color of the pixels behind the semi-transparent window.
* Some of the transparent pixels will have incorrect hues due to incorrect blending.
* `background_opacity` will no longer be linear
See the following examples, the third variant of each is the current …
> Fix color fringing caused by gamma-incorrect blending in compositor when background_opacity is used

- shell-integration/bash/kitty.bash
With shell-integration, the user would see the last value of this variable (as set by the shell-integration script.
Fix this by making it local.
> bash_integration: Do not leak variable `i`

- kitty/fonts.c
- kitty/fonts/box_drawing.py
Addresses discussion here: https://github.com/kovidgoyal/kitty/pull/6146#issuecomment-1489047598. (Sorry for taking so long on submitting this PR; I was busy with classes).
The characters were implemented as a checkerboard of the correct fill density (like in the example characters in the Standard), but this might look a little dated. Let me know if you want me change their appearance.
- Light shade: 25% fill
- Medium shade: 50% fill
- Dark shade: 75% fill (implemented as inverse of light shade)
Additionally, it is extremely easy to add support for the inverse medium shade character (`🮐`, U+1FB90) now, as it should just be `[p(shade, invert=True)]`. Let me know if you want me to include that in this PR (I have also enabled "Allow edits by maintainers" if you want to add it yourself).
> Fix shade characters to follow unicode standard

- docs/graphics-protocol.rst
- docs/keyboard-protocol.rst
I created [a fully interactive Chromium-based web browser called awrit](https://github.com/chase/awrit) that renders in Kitty using the enhanced graphics and keyboard protocols.
It started as a fun little side project, but it might prove to actually be pretty useful to others, so I thought it might be nice to share it.
---
On a side note: I really appreciate all the hard work the contributors have put into Kitty becoming one of the best terminal emulators out there. The fact this is even possible is testament to how flexible and powerful it is.
> Add awrit, a graphical web browser that runs in Kitty, to the docs 

- docs/graphics-protocol.rst
Correct swapped row/column index in description of virtual placements.
> Correct typo in graphics protocol specification

- kitty/cell_fragment.glsl
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/to-c.h
- kitty/options/types.py
- kitty/shaders.c
- kitty/state.h
- kitty/window.py
This adds a parameter to text_composition_strategy that specifies a percentage difference of luminance below which the foreground color will be overridden. The foreground color is set to white if the background is dark or black if the background is light.
Many programs output colors that look good with the author's terminal's color scheme but which are completely illegible with other color schemes. This allows the user ensure that there is always sufficient contrast to read the text on the screen.
Since we want existing configs to continue working, this also makes it so that rather than taking exactly two parameters, text_composition_strategy takes one--three parameters, using the default values for those not specified.
> Add foreground override contrast threshold

- kitty_tests/crypto.py
Hello,
I talked about submitting a patch in https://github.com/kovidgoyal/kitty/issues/5466 but forgot to do it until today - so here it is.
On systems where the max locked memory (a.k.a., RLIMIT_MEMLOCK) is too low, the crypto test fails with "Cannot allocate memory".
Distros such as Debian and Ubuntu run the test-suite as part of the build process. This results in failed builds if the build machine itself does not have a sufficiently high value for RLIMIT_MEMLOCK. That said, the resulting builds would run perfectly when installed on machines that meet the requirements.
On supported systems, we now check if the RLIMIT_MEMLOCK is high enough and skip the crypto test if it is not.
NOTE: I only have access to Linux systems so I have run the test-suite only in Linux. I think it should work …
> Skip crypto test if RLIMIT_MEMLOCK is too low

- docs/_static/timestamps.css
- docs/_static/timestamps.js
- docs/_static/timestamps_source.js
- docs/conf.py
Originally discussed in #6281, this pull request adds timestamps under the introductory kitty [video](https://sw.kovidgoyal.net/kitty/).
Its purpose is to give a better overview in navigating and comprehending the video. 
Timestamps can be edited and expanded upon using `timestamps_source.js` and the `ARRAY` object in `timestamps.js` to get styling. 
A separate stylesheet is used with the timestamps namespace to differentiate itself from other parts of the code. 
`conf.py` is modified to include the new files needed to generate the new element and to specify the script being a module to be able to use a separate source file (timestamps_source.js).
To mitigate potential security vulnerabilities associated with using innerHTML and similar methods, this pull request intentionally creates and …
> Timestamps for the kitty video

- kitty/main.py
https://github.com/kovidgoyal/kitty/commit/9e7253c179e883157b4f7bcb6d02c8d7c4fd009e fix a situation where a valid locale code could not be formed with the country when the language was `en`.
But this does not actually only happen when the language is `en`. 
If the language is `zh`(Chinese) and the country is US, then the locale code `zh_US` is invalid. This will result in [the situation mentioned in the FAQ where double-wide characters cannot be entered and the locale code must be set manually](https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work) and make it impossible to enter CJK text.
---
I think this situation in the FAQ is entirely due to the invalid locale code, but suggest …
> fix: fallback to en_US when locale code is invalid

- kitty/options/definition.py
`Eight window` should be `Eighth window`.
> Fix typo in option definitions

- kitty/main.py
- kitty/notify.py
- kitty/utils.py
I'm just getting into kitty and, while reading the FAQ, I fell in love with DinkDonk's "dark kitty" icon. Imagine my dismay when, after successfully setting it as the launch and taskbar icon, I discovered that a custom *window* icon is supported in macOS, but not X11!
This PR changes that. It uses the same logic (and filename) to locate a custom icon to use for X11. Specifically:
- For OS windows under X11, if a file named `<config_dir>/kitty.app.png` or `<config_dir>/kitty.app-128.png` exists (preferring the 128px image, per the note in the source[^1]), it will be set as the window icon. Otherwise, the 128px version of `logo_png_file` (`<base_dir>/logo/kitty-128.png`) is used.
- For notifications under X11, when `icon=True`, if a file named `<config_dir>/kitty.app.png` exists, it will be …
> X11: Add support for custom window icon

- docs/kittens_intro.rst
[Changing kittens colors](https://sw.kovidgoyal.net/kitty/kittens/themes/) appears in the navigation bar of [Extend with kittens](https://sw.kovidgoyal.net/kitty/kittens_intro/), but is missing from the actual page.
> added missing "Extending with kittens" docs link

- docs/graphics-protocol.rst
- "neovim" instead of "noevim"
- "for convenience as a compact way" instead of "for convenience and a compact way"
- "as a way" instead of "has a way"
> fix three presumed typos

- tools/cli/command.go
From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/UkEZpnzmm5a
> cli/command: remove redundant nil check

- docs/conf.rst
- kittens/ssh/config_test.go
- kitty/conf/utils.py
- kitty_tests/options.py
- tools/config/api.go
- tools/config/api_test.go
This pull requests adds the line break syntax proposed in #6600.
With these changes, lines beginning with a backslash will be joined with the line above. The leading whitespace and backslash are removed.
```
map ctrl+1 combine
\ : send_text all \
\ : set_colors ~/path/to/theme.conf
becomes
map ctrl+1 combine : send_text all \ : set_colors ~/path/to/theme.conf
```
No whitespace is added upon line joining which allows for word breaks.
```
map ctrl+1 send_
\text all \
becomes
map ctrl+1 send_text all \
```
The changes affect both the python and go config parsers.
These changes pass all tests as well as some additional ones.
> Config line breaks

- docs/conf.rst
it looks like RST does not require backslashes to be escaped when encased in double backticks.
> fix double backslash

- shell-integration/ssh/kitten
Fix `Unknown CPU architecture armv7l` on raspberry pi 400
> kitten: Add armv7l alias to arm

- gen-go-code.py
- setup.py
Make openSUSE `kitty` package build reproducible
This needs 3 fixes:
* for an ordering issue in `docs_ref_map_generated.h`
* for a filesystem-order issue in `uniforms_generated.h`
* to normalize mtimes in the `data_generated.bin` tar
This patch was done while working on reproducible builds for openSUSE.
> Make build reproducible

- kittens/transfer/algorithm.c
When building without link-time-optimization through the
`KITTY_NO_LTO` env var or the `setup.py --disable-link-time-optimization` option,
compilation failed with a warning about freeing "ans" memory (probably it did not come from malloc itself).
Chances are, this is dead code that gets optimized out by LTO.
> Fix compilation without LTO

- docs/launch.rst
- kitty/launch.py
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/types.py
- kitty/screen.c
- kitty/window.py
Just a Proof of Concept at the moment.
This implements "send desktop notification when a command is done in a background window" as plugins in various shells do (e.g. https://github.com/franciscolourenco/done), but should work in any shells with OSC 133 shell integration.
TODO:
1. configuration (notify_cmd_done=off/unfocused/invisible, notify_cmd_done_min_duration)
Open questions:
1. Whether to hard-code it as in the PoC, or to extend the Watcher API and implement it as a built-in Watcher.
2. To detect the end of command, should we generate and parse OSC 133;D (end of command output), instead of using OSC 133;A (start of prompt) as in the PoC? 
3. Should the notification include the cmdline? By generating and parsing OSC 133;B? Or by injecting code in each shell and sending it via OSC …
> command done notification

- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Running `sudo --version` will now not error out.
Previously:
```
$ sudo --version
string match: --version: unknown option
Standard input (line 124):
if not string match -r -q "^-" "$arg" and not string match -r -q "=" "$arg"
^
in function 'sudo' with arguments '--version'
(Type 'help string' for related documentation)
Sudo version 1.9.15p2
Sudoers policy plugin version 1.9.15p2
Sudoers file grammar version 50
Sudoers I/O plugin version 1.9.15p2
Sudoers audit plugin version 1.9.15p2
```
> Improve resilience of shell integration for sudo in fish

- glfw/linux_desktop_settings.c
Even if current DE is not GNOME, it may still use the GNOME desktop portal as a fallback for Settings (e.g. KDE). So if the user installed xdg-desktop-portal-gtk, and KDE synced its cursor theme with GNOME, then we can still get it from the GNOME namespace in the Settings.ReadAll result from the portal.
reference:
https://github.com/KDE/xdg-desktop-portal-kde/commit/33f8d622559a59fa01e4099f5623af7d001de549
> Get cursor theme from desktop portal in non-GNOME desktops

- glfw/cocoa_window.m
This fixes the bug discussed in #6930.
> spawn new os_window on active screen on macOS

- glfw/wl_init.c
- glfw/wl_platform.h
- glfw/wl_window.c
According to https://wayland.app/protocols/cursor-shape-v1#wp_cursor_shape_device_v1:request:set_shape
> The serial parameter must match the latest wl_pointer.enter or
> zwp_tablet_tool_v2.proximity_in serial number sent to the client.
So we can't use wl.serial or wl.pointer_serial, because they are also updated in other places.
The symtom:
1. In KDE, open kitty.
2. Ctrl-shift-T to open a new tab.
3. Cursor not updating.
4. Move cursor outside of the kitty window then back fixed the problem.
> Fix Wayland cursor-shape-v1 cursor not updating

- kitty/fast_data_types.pyi
- kitty/glfw.c
- kitty/state.c
- kitty/state.h
Useful when using floating window managers to get a floating terminal placed appropriately with either a shell, compiler output or a man page or other reference material to be temporarily available at a glance.
> Add Python APIs to get and set os-window position

- setup.py
Rather than assuming that GO111MODULE hasn't been modified, this PR makes it so GO111MODULE is explicitly set when running `go list` to extract the required Go version from go.mod, ensuring the version check works even outside of module-aware mode.
Taken from [Debian](https://salsa.debian.org/debian/kitty/-/blob/debian/sid/debian/patches/0011-fix-go-version-check.patch).
> Explicit GO111MODULE=on when getting required Go version

- docs/integrations.rst
The dmenu-term link returns 404 now.
> Remove dmenu-term in docs

- shell-integration/bash/kitty.bash
The Bash integration script entirely replaces `PROMPT_COMMAND` when it is *empty*. However, the current empty check is incomplete. When the first element `PROMPT_COMMAND[0]` is empty, `[[ -z "${PROMPT_COMMAND}" ]]` succeeds even if there are non-empty elements `PROMPT_COMMAND[i]` (with `i` >= 1). Then, the entire array is replaced by kitty's shell integration script so that all the settings set with index `i >= 1` are lost.
Note: It should be noted that in Bash/Ksh/Mksh etc, `$array_name` always means the 0th element of the array, which is different from Zsh. Also, in these shells, for a scalar variable (i.e. a variable that is not an array), `${scalar_variable[*]}` just picks its value.
The presented situation happens with the setting suggested for *a robust setup* in the Bash mailing …
> Fix Bash integration removing existing elements of PROMPT_COMMAND

- kitty/boss.py
- kitty/options/utils.py
This should be pretty self-explanatory.
Rationale: I usually have plenty of different tabs open in which I'm doing different things (work/system troubleshooting/configuring nvim/htop/...) and use `detach_window` when my current tab gets too crowded. I would like related tabs to stay together, so an option to detach a window to a new tab, _which gets created next to the current tab_ would be useful.
> Add `new-tab-neighbor` option to `detach_window`

- kitty/options/definition.py
Building from source with python 3.12 from macports on macOS you get the following warnings:
```
...
kitty/options/definition.py:4116: SyntaxWarning: invalid escape sequence '\e'
long_text='''
kitty/options/definition.py:4116: SyntaxWarning: invalid escape sequence '\e'
long_text='''
kitty/options/definition.py:4116: SyntaxWarning: invalid escape sequence '\e'
long_text='''
...
```
Making long_text a raw string or escaping the \\'s also fixes this warning.
> Fix invalid escape sequence warning with reset_terminal long_text

- docs/shell-integration.rst
Without the need to click the link to read the discussion. 
In my tests, all these work fine
- Open the output of the last command in a pager such as less [ctrl+shift+g]
- Jump to the previous/next prompt in the scrollback [ctrl+shift+z]
Click with the mouse anywhere in the current command to move the cursor there
- Hold Ctrl+Shift and right-click on any command output in the scrollback to view it in a pager
- The current working directory or the command being executed are automatically displayed in the kitty window titlebar/tab title
> doc: add detailed step to enable shell integration for Nushell

- bypy/devenv.go
The `make develop` target no longer exists.
> Fix build instructions after ./dev.sh deps

- kitty/child-monitor.c
- kitty/shaders.c
- kitty/state.h
As discussed in #7301.
Previously, all windows would be drawn with inactive_text_alpha if the os window was unfocused. This changes the rules to the following:
- If there is a single window and the os window is unfocused, use inactive_text_alpha.
- If there are multiple windows, use inactive_text_alpha for all non-active windows, regardless of os window focus.
---
I've renamed the `can_be_focused` argument to `is_tab_bar`, since this makes the condition much more readable, and that's effectively what it signifies. Tell me if you want me to undo this rename.
> Update rules for inactive_text_alpha

- docs/keyboard-protocol.rst
- docs/shell-integration.rst
- shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
The upcoming fish 3.8 release will output OSC 133 sequences unconditionally [1].
I tested ctrl-shift-{g,x,z} bindings both without and with kitty's shell integration on top; everything seems to work.
Let's simplify kitty integration by removing the markers for the upcoming fish >= 3.8.
I have hopes that the native OSC 133 implementation address #7200 though I'm not sure if I could reproduce this bug
(I only saw a similar bug when `fish_handle_reflow` was not enabled, which fish also does now (same commit)).
cc @iacore, let me know if you can reproduce #7200 with latest fish master.
[1]: https://github.com/fish-shell/fish-shell/commit/3b9e3e251bf9d4c7d0b31275cac55df68fe0127a
> fish integration: drop redundant OSC 133 markers in upcoming fish 3.8

- docs/build.rst
recently built from source and noticed this minor typo
> fix typo in dependency name

- docs/faq.rst
- docs/keyboard-protocol.rst
- docs/kittens/hyperlinked_grep.rst
This applies the suggestion in https://github.com/kovidgoyal/kitty/issues/7402#issuecomment-2084726356
Fixes: https://github.com/kovidgoyal/kitty/issues/7402
> docs: use the hyphenated kitten name

- shell-integration/ssh/kitten
- shell-integration/ssh/kitty
On some Macs (e.g. M1, 2020), `uname` returns 'Darwin' and `uname -m` retuns 'arm64', this case is not handled in shell-integration. As a result, ssh kitten transfer fails with:
> Unknown CPU architecture arm64
Fix this by adding the case for arch=arm64 in kitten and kitty shell-integration scripts.
Tested this on Mac Pro (M1, 2020).
> shell-integration/ssh: Support arch=arm64, for MacOS

- shell.nix
Fixes error when building Kitty on Linux using the provided shell.nix file.
> Fixed missing C header file by adding "simde" dependency to the optionals field for stdenv.isLinux in file shell.nix

- docs/graphics-protocol.rst
- docs/integrations.rst
- docs/keyboard-protocol.rst
Fixes https://github.com/kovidgoyal/kitty/issues/7505
> Add Yazi terminal file manager to the list of software implementing kitty's graphics protocol

- kitty/options/definition.py
It's is incorrect here, which can clearly be seen by expanding the contraction to "It is". Its is correct for possessive.
Just a small typo I saw in kitty.conf that bothered me, sorry if this PR is too small or whatever.
> Fix small typo in definition.py

- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/to-c.h
- kitty/options/types.py
- kitty/options/utils.py
- kitty/shaders.c
- kitty/state.h
Implements what was discussed in #7532.
New option `window_logo_scale` takes int 0-100, scales the window logo image to x% of the window dimensions (smallest dimension sets scale).
Problem, using the current window_logo, you are able to position and clamp, but unable to enable scaling such that the logo does not take up too much space on a small terminal or be too small on a large terminal. Alternative solution would be to use background_image with cscale, yet if you want to have a logo anywhere other than the centre of the terminal, this quickly falls apart once you begin resizing the terminal outside the aspect ratio of the original image.
Adding the option to scale the window logo allows for the original goal of #7532 while being quite generic and overall a very minor code addition. …
> add option to scale window_logo via window_logo_scale

- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/types.py
- kitty/options/utils.py
- kitty/shaders.c
- kitty/state.h
Did this for myself and saw a few issues on it such as #7111.
I know the owner is not too fond of it, but given it's an option, and default behavior remains unchanged I decided to open a PR regardless, especially for people with tilers there are other indicators of window focus, and aesthetics are subjective after all.
Checked under bspwm on X and hyprland on Wayland.
> Option to change cursor shape for unfocused windows

- kitty/glfw.c
Fixes #7503 for me (Arch + Hyprland + AMD GPU).
This condition was added as a sanity check to fix #1696, however I don't have a Sway setup so I am unable to test if this causes a regression. I tried just unplugging the monitor that the window was open on, however this caused a segfault when I plugged the monitor back in even before my changes.
> Allow Wayland fractional scales less than 1.0

- docs/graphics-protocol.rst
The example is missing `a=c` but it has the remaining parameters.
> Fix composition example in Graphics Protocol

- kittens/themes/ui.go
The themes kitten used the truncated color name when formatting the colors themselves, which leads to broken coloring when the window is narrow enough to cause truncation to occur.
> Fix themes kitten not displaying colors in narrow windows

- docs/desktop-notifications.rst
This simply just removes a redundant word from the desktop notifications document.
> Remove unnecessary word in desktop notifications document

- docs/kittens/ssh.rst
It was erasing the remote variables instead of setting them.
https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.env
> Fix env assignation in ssh kitten docs

- kitty/fonts.c
- kitty/fonts/box_drawing.py
This symbols are for drawing git-like directed acyclic graphs in the terminal. Similar to box drawing characters, it is difficult to align these symbols perfectly when they're implemented only as font glyphs.
These codes are not based on any existing standard. I have implemented them using my experience creating the terminal-based branch viewer and vim plugin [vim-flog](https://github.com/rbong/vim-flog). I plan to use these symbols in flog.
Here is what the symbols look like in kitty, in order:
The order is similar to the original box-drawing characters. Particularly, where there are symbols with a mix of light lines and heavy lines, I replace the heavy lines with curves. Otherwise, I try to follow a similar order.
Some symbols effectively already exist, these ones in particular: …
> Add branch drawing symbols to box characters

- docs/kittens/cli_interfacing.rst
Since I am working on the IV kitten, I am surfing through the source code and figuring out alternatives built into the kitty for third-party stuff. Thanks to @kovidgoyal, he is helping us out in this journey, So I decided to create docs for stuff I feel like developers must know while working with the development of kittens in the future. Currently, I am trying to understand through source code and hashed, but that's a bit friction and hence, I would like to have some dev-docs that are made for the devs who would be working with kittens (or any other things) in the future and they can find the docs for them in kitty's official guide. 
For us, CLI interfacing was something we want to find, which Kovid explained through a commit, but for next time, devs should be able to find this in the …
> Added CLI Interfacing Doc for Developers building kittens

- docs/basic.rst
I think shift is required to switch tabs on default config.
⇧+
> docs typo: Next tab keybind macOS

- kitty/fonts.c
- kitty/fonts/box_drawing.py
I have been working with [other terminal branch viewer authors](https://github.com/SuperBo/fugit2.nvim/discussions/88) to determine how they feel about the [new extended branch characters](https://github.com/kovidgoyal/kitty/pull/7681).
The first change is to make commit circles slightly larger. There has been feedback that the circles are too small, which I agree with.
The second change is to add more commit symbols with branches connected to them at various angles.
Here are all the symbols, with the new symbols in the last two rows:
It can be hard to see what the new symbols are with the large commit circles, so here they are with lines next to them that show how they're connected:
The new symbols allow drawing the commit graph with branches merging directly into the commit rather than …
> Extend and tweak branch drawing symbols based on feedback

- kitty/mouse.c
- kitty/screen.c
- kitty/screen.h
This adds a new flag to the `<OSC>133;A` escape sequence from [Kitty's shell integration protocol](https://sw.kovidgoyal.net/kitty/shell-integration/#notes-for-shell-developers), `click_events=1`.
If this flag is used, Kitty will emit SGR mouse events rather than faked keypresses when the prompt is clicked.
**Note:** this does not update the shell integration code to actually use this new flag. Unclear if that should be in this PR or a separate one, due to the complexity involved.
> Add special flag to shell integration protocol to request real click events

- kitty/tab_bar.py
On thinking more about the related issue (#7871) I realized that the desired result can be obtained much more simply by suppressing the display of left/right margins whenever the user has set `tab_bar_margin_width` to `0.0` (which is the default).
Left and right margins pop in and out depending on blank space:
Left and right margins are not shown:
Closes: https://github.com/kovidgoyal/kitty/issues/7871
> feat: don't draw visible tab bar margins if width is 0

- kitty/animation.c
I noticed my terminal freezing when the visual bell would appear, and it seems floating point imprecision caused the bisection method loop to execute indefinitely, since I set my `visual_bell_duration` very low (to `0.2`). Limiting the iterations fixed the problem, so I simply limited them to 5 for now.
> Limit bisection method iterations to prevent infinite loop

- shell.nix
With the change, I was able to build the binary with `make` and successfully execute the tests with `./test.py` on darwin aarch64.
> nix: fix shell config for darwin

- kitty_tests/file_transmission.py
Nanosecond precision is not universally available on all platforms. [For example](https://github.com/NixOS/nixpkgs/issues/143987#issuecomment-955749038), nixpkgs python is built using Apple SDK 10.12 that does not have `utimensat`. Because of that, python `os.stat` falls back to microsecond precision.
This patch applies `os.utime` with zeroed nanoseconds to symlinks created by the test case, the same way as it is already applied to other files tested for transfer.
The failure was observed [here](https://logs.ofborg.org/?key=nixos/nixpkgs.338070&attempt_id=4dffb1e2-ba17-4efe-a538-1155a147da75).
The error is:
```
AssertionError: {'simple': Entry(relpath='simple', mtime=13[498 chars]k=1)} != {'abssym': Entry(relpath='abssym', mtime=17[498 chars]k=1)}
- {'abssym': Entry(relpath='abssym', …
```
> tests: apply `os.utime` to created symlinks too

- tools/cli/bash.go
When the user doesn't set up the `bash-completion` framework, the completion setting by the kitty shell integration causes an error message on attempting a completion:
```console
$ kitty kitten a[TAB]bash:_command_offset: command not found
[TAB]bash:_command_offset: command not found
[TAB]bash:_command_offset: command not found
```
This is because the completion [attempts to call the shell function `_command_offset`](https://github.com/kovidgoyal/kitty/blob/69e1534087698faf5d25fd094a7cc3a77920cb0d/tools/cli/bash.go#L38-L40), which is provided by the `bash-completion` framework.
It should be noted that `bash-completion` is a project separate from Bash itself, and `bash-completion` is not necessarily loaded in a Bash session. In fact, some users do not want to use `bash-completion` for …
> Call `_command_offset` from the `bash-completion` framework for Bash only if available

- kitty/fontconfig.c
- kitty/freetype.c
For some reason, `d`, the descriptor used to load the font face, points to a file that does not exist in my system, so `face_from_descriptor` returns `NULL`, and then `has_cell_text` segfaults. I don't know if it's a normal behavior. I also had to add a seemingly missing `return` (all the other lines had it, and it was segfaulting at `init_ft_face` otherwise). Maybe there is another root cause issue that should be fixed, but I don't know the code base enough to know.
Either way, have a great day!
> Fix segfault when font descriptor point to invalid font file

- kitty/cursor_trail.c
- kitty/screen.h
- kitty/shaders.c
- kitty/state.h
two main changes
* Reuse cursor color computed in `cell_update_uniform_block` to render cursor trail
* Refactored cursor trail update logic. So its behavior can be more easily grasped looking at the code.
> Similarly, I want to basically ensure no trail is started while in
rendering paused mode and that for cursor movements that happen in that
mode the position_changed_by_client_at field is the time at which
rendering was resumed. 
I believe the current implementation already addresses your concern. Here's why:
1. The trail only displays when the current trail position and target cursor position are not equal:
```c
ct->needs_render = false;
if (update_cursor_trail_corners(ct, w, now, os_window)) {
ct->needs_render = true;
}
```
2. The target cursor position does not change while in the …
> Minor fixes about cursor trail 

- kittens/diff/mouse.go
This issue happens when you select text from bottom to top. Selection would be empty.
Fix is simple: swap start and end if they are in wrong order.
> diff kitten: fix mouse move down up selection

- kitty/cursor_trail.c
- kitty/options/definition.py
- kitty/options/parse.py
- kitty/options/to-c-generated.h
- kitty/options/types.py
- kitty/shaders.c
- kitty/state.h
- kitty/trail_fragment.glsl
continued from https://github.com/kovidgoyal/kitty/pull/7970. 3 main changes
1. Improved cursor trail animation. It now looks uniform regardless of its moving direction. The movement appears smoother, especially when the cursor moves horizontally.
https://github.com/user-attachments/assets/9c089fb9-666a-4057-80ed-ab1036ce5231
https://github.com/user-attachments/assets/618fbf65-487a-423a-9ad3-afda22c4de2d
https://github.com/user-attachments/assets/4ec4c3c7-3aeb-4285-bcc5-c539f041b352
https://github.com/user-attachments/assets/a06cc8c8-2bcf-4f8e-b975-c918e4da6441
2. The trail now fades in and out when moving between windows with different cursor visibility. One caveat: the trail will not be visible when moving from a window where the cursor is hidden to another window where the cursor is …
> Enhance Cursor Trail: Improved Animation, Fades, and New Distance Threshold Option

- tools/tui/loop/terminal-state.go
Explicitly turn off in-band resize notifications if they were requested as part of the loop. Kitty implicitly resets this mode when `XTRESTORE` (`CSI ? r`) is seen, however some terminals implementing mode 2048 (eg foot and Ghostty) follow the xterm behavior of only restoring the state of explicitly passed modes. Some of the kittens have become very useful outside of just Kitty (`show-key`, for example) - but when mode 2048 is left enabled in this way, escape codes are dumped to the screen. 
Add an explicit reset of mode 2048 to support the behavior of other terminal emulators.
> tui: explicitly turn off in-band resize mode

- kitty/child-monitor.c
Fixes issue  https://github.com/kovidgoyal/kitty/pull/7970#issuecomment-2466687264
I haven't looked into the details, but calling `set_maximum_wait(0)` makes it skip handling key input until the next render. Giving it a minimal value of 1ms seems to mitigate the issue effectively.
> Fix cursor trail update blocks key input when repaint_delay is 0

- kitty/data-types.h
- kitty/launcher/main.c
- kitty/launcher/single-instance.c
- kitty/screen.c
My "./dev.sh build" failed with
Compiling kitty/screen.c ...
gcc -MMD -DNDEBUG -DPRIMARY_VERSION=4000 -DSECONDARY_VERSION=37 -DXT_VERSION="0.37.0" -I/home/johannes/git/kitty/dependencies/linux-amd64/include -Wextra -Wfloat-conversion -Wno-missing-field-initializers -Wall -Wstrict-prototypes -std=c11 -pedantic-errors -Werror -O3 -fwrapv -fstack-protector-strong -pipe -fvisibility=hidden -fno-plt -fPIC -D_FORTIFY_SOURCE=2 -flto -fcf-protection=full -march=native -mtune=native -pthread -I/home/johannes/git/kitty/dependencies/linux-amd64/include/libpng16 -I/home/johannes/git/kitty/dependencies/linux-amd64/include -I/home/johannes/git/kitty/dependencies/linux-amd64/include -I/home/johannes/git/kitty/dependencies/linux-amd64/include -I/home/johannes/git/kitty/dependencies/linux-amd64/include/fre …
> Fix Python.h being included after system headers

- kitty/notifications.py
- kitty/window.py
Currently notifications emitted with `notify_on_cmd_finish` and unfocused left withing notification bar forever and user have to clear them by hand. This patch automatically clears notification when emitted window gained its focus back assuming that user is aware about action and not needs for notification any more.
> Cleanup command finish notifications

- kitty/cursor_trail.c
The cursor trail will occasionally either not display when the cursor jumps, or more commonly it will initially not display, and then appear shortly after to create a glitchy-looking effect.
I found this is reproducible in vim/neovim depending on how you hold down the keys. If you do not immediately release a keypress, eg you hold '$' to go to the end of a line the trail will not appear. If you hold the key for a short while and then release, the animation will start when you release (although you are only catching the end of the animation). Under the right conditions, this can also be replicated by running a script that simply prints control codes to move the cursor (I can give more details if needed).
This may be difficult to reproduce yourself, because it is dependent on the system …
> fix cursor trail not displaying in certain cases

- docs/graphics-protocol.rst
Ghostty 1.0 was just released. It implements the Kitty Graphics Protocol. I used a link to the specific code that implements the prototocol. Alternatively, could use the [feature page](https://ghostty.org/docs/features)  or [home page](https://ghostty.org). I added it first in the list to preserve alphabetical order. I am not affiliated with the Ghostty project.
> Add Ghosttty to list of terminals implementing the graphics protocol

- shell-integration/zsh/kitty-integration
Remove usage of the `-P` option from the print inside the `_ksi_precmd` and `_ksi_preexec` functions. Instead, the result of `builtin print -Pn "%m"` is stored in the local variable `hostname`. This mitigates accidental expansion of variables in the command to be executed.
Fixes #8193.
> ssh kitten: Fix zsh shell integration expanding variables in title

- docs/quickstart.rst
Missed in c8e83780c3bfb12bfd7e180ccf8ea3505a58dbbb
> Fix repology link in quickstart doc

- kitty/launch.py
This PR adds more environment variables (that would cause problems if copied to another shell session) to the black list.
Some variables (`READLINE_*` and `COMP_*`) are variables temporarily set to indicate a special context, some variables contain session-specific IDs (which are used for sorting command history items or communicating with associated child/parent processes), and some variables are used to show the confirmation prompt in the terminal.
> clone-in-kitty: Exclude more environment variables from clone target

- kitty/window.py
Been having issues with some programs like neovim where it puts the output of `report_color_scheme_preference` to the input prompt when suspending the editor, and at inconsistent times when quitting the editor. I'm guessing this was just missed from https://github.com/kovidgoyal/kitty/commit/6fbeb939de85c578260e3196b2f8f6e90925e3d3, but this change resolves the issue for me in a local build.
---
https://github.com/user-attachments/assets/35fbcc96-4cd3-4f7c-9cec-6836efd89b0b
> fix: Report OSC 30101 bg change as via escape code

- kitty/history.c
Off-by-one error in f412ec617ce23a72ee69c47a7db2a6b35a0a69bd. Kitty is failing to find the previous prompt when trying to page the last command output (via `ctrl+shift+g`) when the executed command is long enough that it wraps and the output is long enough to put the prompt in the history buffer. The result is either:
- Paged cmd output is empty; or
- Paged output contains cmd outputs from up to the first prompt that has a non-wrapping command; or
- The last wrapped line of the command is included in the paged output when paging via mouse (`ctrl+shift+rclick`)
> fix: Properly find wrapped lines in history buffer

- docs/graphics-protocol.rst
It's implemented as a patch, the link points to the patch landing page.
> Add st to the list of terminals implementing graphics protocol

- docs/overview.rst
- kitty/boss.py
- kitty/launch.py
- kitty/main.py
- kitty/session.py
You can now specify `os_window_name` in addition to `os_window_class` in
startup sessions.  It works for the initial session as well as new sessions
started with `new_os_window`.
Updated documentation in overview.rst to add `os_window_name` in the
Startup Session examples.
Although not related to this feature. The documentation in launch.py
was updated to note that the `launch --type` `tab` and `os-window` options
aren't supported when launch is invoked from a startup script.  There's
already a note to that effect in the "Startup Sessions" section in
overview.rst but if you're looking at the launch syntax page like I was,
you wouldn't realize the limitation. This was throwing me for a loop while
wotking on this PR.
Resolves: #8387
> Add support for os_window_name in startup sessions.

- glfw/wl_window.c
Before this commit specifying --edge=none for the panel kitten would anchor kitty like so:
```
+-----------------------------+
|                             |
|+----------+                 |
||          |                 |
|+----------+                 |
|                             |
+-----------------------------+
```
The docs state: "`none` anchors the panel to the top left corner by default".
After this commit the behavior is consistent with the documentation.
> Wayland: Updated anchor for edge=none to be consistent with documentation

- kittens/panel/main.py
Before this PR, both vertical and horizontal panels were using `--lines` for controlling size. After this PR, the behavior is consistent with the documentation which states that `--columns` is used for vertical panels and `--lines` is used for horizontal panels. The logic for `--edge=none` was also corrected although this has no real effect until it is supported on X11.
> Fix initial window size logic for --edge=none and vertical panels

- setup.py
When on a go development version, `setup.py` crashes due to trying to parse `vel` as a go version (which it is not), this change checks to see if the item at index 2 from the `go version` output is the literal string `devel`, and if it is then sets the go version to the string at index 3 instead.
`go version` output:
```
firepup650@FIREPUPS-LAPTOP:~/sources/kitty $ go version
go version devel go1.25-0694718389 Mon Mar 17 18:31:30 2025 -0700 linux/amd64
```
Before:
```
firepup650@FIREPUPS-LAPTOP:~/sources/kitty $ ./dev.sh build
[32/32] Generating wayland-wlr-layer-shell-unstable-v1-client-protocol.c ... done
[131/131] Compiling kitty/gl-wrapper.c ... done
[5/5] Linking launcher ... done
File "/home/firepup650/sources/kitty/setup.py", line 2222, in …
```
> Handle the edge case of someone running a development go build

- docs/graphics-protocol.rst
Warp version [v0.2025.03.26.08.10](https://docs.warp.dev/getting-started/changelog#id-2025.03.26-v0.2025.03.26.08.10) was just released. It implements the Kitty Image Protocol. I used a link to the changelog entry.
I added it to the list, preserving alphabetical order. I am [affiliated with Warp](https://www.warp.dev/about) (Support Engineer).
> Add Warp to list of terminals supporting Kitty graphics protocol

- kitty/fast_data_types.pyi
- kitty/screen.c
- kitty_tests/screen.py
Forgot I had some of these stashed, just some small fixes to paging logic. Tests pass locally.
Let me know if you deem the last commit unnecessary. It's only really applicable in this section of the code, but it better expresses the intent of selecting a specific line in the visible screen (like with the related select-by-mouse code) instead of wrestling with `scroll_to_prompt`.
> fix: Paging edge cases for very small scrollback lines

- .github/workflows/ci.yml
- kitty/options/definition.py
I noticed that
<https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_fg_override_threshold>
said
```
:code:` ratio`
```
instead of being formatted as code. I assume that's because of a space after \`.
Fixed 2 cases where I found the issue.
Added a simple code block check to CI.
> Fix bad code block formatting in docs

- tools/cli/fish.go
- tools/cli/help.go
This patch aims to address two sources of build non-determinism in the kitty package:
1. It sorts fish completions to avoid nondeterministic ordering, which could lead to inconsistent builds.
2. It modifies the man page generation process to respect SOURCE_DATE_EPOCH instead of using time.Now() for timestamps, helping ensure consistent dates in the documentation.
These changes are intended to help with the issue of unreproducible builds for kitty, as mentioned in [Nixpkgs Issue #383872](https://github.com/NixOS/nixpkgs/issues/383872). If any further adjustments are needed or if there are better approaches, I'm happy to make changes based on feedback.
> Improve reproducibility in kitty package by sorting completions and adjusting man page timestamps

- kitty/glfw.c
Previously, mouse unhiding time was not reset on mouse hides, which can lead to sooner than expected unhides.
> Fix mouse cursor unhiding logic to reset on mouse being hidden

- kitty/launcher/main.c
`--instance-group` option was being ignored and only the prefix was used.
> Fix instance-group using only prefix

- kitty/utils.py
It may be present but not readable. This may occur when executing in a sandbox that does not permit access.
> Fix exception when /etc/paths{,.d} is not readable on macOS

- docs/integrations.rst
I made a small tool called k-nine (kitty-plotnine) to do quick-and-dirty plotting within kitty-compatible terminals with bash one-liners. 
See this [reddit post](https://www.reddit.com/r/KittyTerminal/comments/1k7u34z/knine_a_tool_for_plotting_in_the_shell_with_bash/). It was suggested that I add this tool to the kitty documentation so I am creating a pull request to do so. 
Thanks,
readwithai
> Add k-nine plotting tool to the integrations documentation

- docs/graphics-protocol.rst
Those ticks are not neccessary.
|Before|After|
|-|-|
|![Screenshot From 2025-04-29 00-10-37](https://github.com/user-attachments/assets/ef1ae106-3817-4f3d-b302-66a5a66b5693)|![Screenshot From 2025-04-29 00-10-24](https://github.com/user-attachments/assets/feef98c2-9865-4d36-907d-92686c2c5496)|
It will work the same way this thing does:
|![image](https://github.com/user-attachments/assets/dc1aca2b-7bdb-4bd9-94e1-1c864aba4721)|![image](https://github.com/user-attachments/assets/c2df26f6-1354-450a-b20b-88d6b95f877d)|
|-|-|
> Update graphics-protocol.rst: typo fix

- shell.nix
I added three missing packages to the shell environment provided by the *Nix* shell (two of them are only needed on Linux). Also, I manually copy the needed font to *./fonts* using *shellHook*.
The provided *Nix Shell* now allows for successful builds (tested on x86_64-linux and x86_64-darwin).
> fix: add missing pkgs and manually add font for nix shell

- docs/kittens/panel.rst
As of the latest niri release, more specifically https://github.com/YaLTeR/niri/commit/3e31c134a602dd876f2b446071e5802fa4a0c3ec, focus no longer gets stuck on an unmapped layer surface.
> docs: panel: update niri compatibility information

- docs/kittens/panel.rst
The latest sway release now properly reclaims space from an unmapped layer surface.
https://github.com/swaywm/sway/commit/1b47277962fa04624a0b6835e81089110d258e7c
> docs: panel: update sway compatibility information

- docs/kittens/panel.rst
As of labwc [0.9.0](https://github.com/labwc/labwc/releases/tag/0.9.0) the panel kitten now works as expected.
Relevant changes:
https://github.com/labwc/labwc/pull/2745
https://github.com/labwc/labwc/pull/1154
https://github.com/labwc/labwc/pull/2867
> docs: panel: update labwc compatibility information

- kittens/choose_files/scan.go
```
Error: Panicked: runtime error: invalid memory address or nil pointer
dereference
Panicked with error: runtime error: invalid memory address or nil
pointer dereference
Stacktrace (most recent call first):
github.com/kovidgoyal/kitty/kittens/choose_files.(*FileSystemScanner).worker
kitty/kittens/choose_files/scan.go:351
```
> Fix `kitten choose-files` panic

- kitty/main.py
- kitty/simple_cli_definitions.py
adds a special value `listjson` for panel `--output-name` for a json encoded output instead.
> add special value listjson in panel output-name option

- kitty/launcher/main.c
After redirecting stdout and stderr to the log file, they become block buffered. This results in a (temporarily) incomplete log and becomes particularly annoying when kitty crashes/hangs and has to be killed, as the error messages are not flushed then and thus lost.
> Make detached-log line buffered

- kittens/show_key/main.py
Fix a small typo in the exit message I spotted after making my own typo trying to run `show_key`!
> fix(show_key): fix typo in python exit message

- kitty/options/definition.py
- kitty/window.py
Add a "copy_or_noop" option which copies the text, and if there is no
selected text passes through the key. This allows applications to
implement native text selection but also have cmd+c still function as a
copy key since they can now receive it.
Make this the default on macos. This should have very little impact on
users because when no text is selected, the application can
(potentially) handle the key.
> options: add copy_or_noop, make default

- docs/graphics-protocol.rst
blackcat is designed to be a compatible, drop-in, cat with Kitty image support + dos/cp437 mapping + dos ansi rendering.
> Add 'blackcat' a modern compatible cat with image support

- shell-integration/bash/kitty.bash
If the user's bash profile contains 'set -u' (to protect against typos in variable names; think "rm -Rf $TMp/*"), starting a new kitty terminal resulted in a spurious `bash: sourced: unbound variable` message.
> Don't complain about unset 'sourced'

- docs/text-sizing-protocol.rst
- kitty_tests/parser.py
> Text sizing protocol docs: specify UTF-8 decoding, use unambiguous Unicode terminology

- shell-integration/bash/kitty.bash
If the user's bash profile contains 'set -u' / 'set -o nounset' (to protect against typos in variable names; think "rm -Rf $TMp/*"), starting a new kitty terminal resulted in a `bash: sourced: unbound variable` message.
Also, the error disabled kitty's shell integration.
This PR fixes/supersedes bba4ce22, which was based on an incorrect assumption and was submitted by mistake.
> Fix bash integration when 'set -o nounset' is in effect

- kittens/panel/main.py
- kitty/cli.py
- kitty/launch.py
- kitty/rc/resize_os_window.py
This commit addresses a few issues with the implementation of '--incremental':
- Unspecified settings are reset to their default value, which defeats the purpose of the option.
- It is assumed that the names of options in 'LayerCLIOptions' map one to one with the names of fields in 'LayerShellConfig' but this isn't true. For example: The 'margin_top' cli option sets the 'requested_top_margin' layer shell config.
- When some options are set to a certain value, they force other options to be some value. The current implementation doesn't account for this.
- The documentation is contradictory.
> resize-os-window: fix '--incremental' option of 'os-panel' action

- kittens/quick_access_terminal/main.py
First off, love the terminal! Simple and elegant. 🚀 
I noticed while setting up the Kitten `quick-access-terminal` that the kitty overrides weren't working. Searching through the codebase I quickly realized that each of them needed to have `kitty_override` preceding that actual override key <-> value pairing. I've updated the documentation in a minimal way to highlight the example syntax for this configuration.
> Update documentation for kitty_override kitten quick_access_terminal

- kittens/hints/main.py
For `hints --type regex` the captured part of the default regex is greedy so if your vim has the following text:
```
+---------------------------------------------------+
|foo                                                |
|     I want to capture this line!                  |
|bar                                                |
+---------------------------------------------------+
```
and you then select the second line with `kitten hints --type regex --program @`, the capture texted will be:
`I want to capture this line!                  ` (notice the trailing whitespace)
I believe the intent is for the kitten to capture:
`I want to capture this line!`
Making the capture part of the regex non-greedy results in the desired behavior.
> hints: make default regex ignore trailing whitespace

- tools/unicode_names/query.go
In the `unicode-input` kitten, if a word in your query matches no codepoints, codepoints matching other words in your query will still be shown if the result of `find_matching_codepoints` for the word with no matches is considered first. The order in which the words are considered is not defined since `find_matching_codepoints` is parallelized for each word.
Here you can see that even though `foobar` doesn't match any codepoints, sometimes results matching `face` and `fac` are still shown:
https://github.com/user-attachments/assets/3cd37819-235b-46c1-8ff4-558d063d2edc
> unicode-input: fix race condition causing incorrect results
