kitty/char_grid.py, kitty/config.py, kitty/kitty.conf
Double click now behaves more like in other terminals.
I copied the list of chars from the one konsole is using.
=> make double click selection smarter and configurable

kitty/config.py, kitty/kitty.conf, kitty/mouse.c, kitty/state.c, kitty/state.h
Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
=> Make it possible to modify rectangle selection modifiers

kitty/glfw.c
fixes issue mentioned in #280 where having more than 2 windows confuses the focus-history.
This is a rather stupid implementation of a ring buffer, and is by no means a good solution for this bug, but I implemented it locally and figured I'd leave the decision up to you, if you want to deal with this your own way or not.
=> fix mac os_window focus issue

kitty/mouse.c
This ads right mouse click extend selection in similar manner as it works in Xterm.
https://github.com/kovidgoyal/kitty/issues/358
Right mouse click respects type of first type of click (single, double, triple) and extends accordingly.
Previous functionality with drag, ctrl+alt drag, shift+click should work as before.
Please check if this can fit in Kitty.
=> Extend selection with right click

setup.py
Let's use the 'TerminalEmulator' category according to the spec:
https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html
=> Have more detailed desktop file category

README.asciidoc
Instead of https://github.com/kovidgoyal/kitty/pull/411
=> Mention tic as dependency

kittens/unicode_input/main.py
Fixes the exception itself in #442
=> Fixed crash on tab-completing without any search results.

kitty/glfw.c
I `want_semi_transparent`, but I want it at the level of `0.95` 🙂
=> Allow background opacity for values in range [0.91, 0.99]

.travis.yml
Help catch issues like #471 in the future.
=> travis: Force unsigned char on one build

README.asciidoc
Kitty has been moved to the Arch community repository
=> Updated Readme - Arch package

README.asciidoc, kitty/layout.py
This pr added a new layout called "fat". It's similar to "tall" but is more suitable for monitors in portrait mode.
Here is what the layout looks like:
```
+-------------+
+             +
+             +
+------+------+
+      |      +
+      |      +
+------+------+
```
=> Add fat layout

docs/changelog.rst, docs/kittens/unicode-input.rst, docs/remote-control.rst, glfw/cocoa_window.m, glfw/xkb_glfw.c, kitty/cmds.py, kitty/freetype.c, kitty/glfw.c, kitty/line.c, kitty/remote_control.py, kitty/screen.c, kitty/shaders.c, kitty/terminfo.py, kitty/utils.py, setup.py
I found every word dont and replaced it with don't. Is there any reason for leaving the apostrophe out?
=> dont -> don't

kitty/mouse.c
Thanks to 0e248b3faa1551555320a7522e8297229ad72788, I can now make #837 a pull request.
=> Allow for faster scrolling in alternate screen mode

glfw/xkb_glfw.c
Compose sequences can be defined without an associated symbol. To test for
completeness, we now also rely on XKB’s reported compose state.
Fixes #880.
=> Support compose sequences with no symbol

docs/index.rst
=> Add link for the Void Linux package

kitty/window.py
Complementary to 15f534a8f9d44d9873b07d8309db498aca7c6cd1
=> Don't guard against alternate_screen in as_text

kitty/layout.py
=> Fixed call to Tall.neighbors_for_window

kittens/hints/main.py
=> hints: optionally add trailing space

docs/kittens/custom.rst
=> update docs for kitten STDIN

kitty/cocoa_window.m
This is my first ever with Objective-C, any feedback welcome. I had to do some silly runtime stuff to to inject the `applicationDockMenu` method, but it works.
Discussed in #1242.
=> macOS: Add "New OS Window" to dock menu

kitty/cmds.py
Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
=> Add match-tab for send-text

.travis.yml
https://docs.travis-ci.com/user/reference/xenial/
=> Switch travis to Xenial

kitty/constants.py
Fixes https://github.com/kovidgoyal/kitty/issues/1406.
=> kitty_exe: use ordered list

docs/index.rst, kitty/config_data.py
As discussed in https://github.com/kovidgoyal/kitty/pull/1323#issuecomment-466608568.
=> Add two more macOS keyboard shortcuts for switching tabs

kitty/mouse.c
See commit message for more details.
=> Do not focus window when mouse button is released

kittens/unicode_input/main.py
useful for zones with icons
binds some increment/decrement on up/down keypress, also a proposal for a bit less useful tab binding.
=> implement fast browsing of the unicode input

kitty/cmds.py
introduced by https://github.com/kovidgoyal/kitty/commit/603716733634614d4ab4a4d39e0e4c8488ae8c93
=> Fix windows_for_payload

launcher.c, setup.py
Since the launcher is also used on macOS, rename it to something more generic.
=> Rename linux-launcher -> launcher

docs/index.rst
I am not an english expert and english is not my native language but I think this should be "little" instead of "less".
=> docs: "relatively little effort" instead of "relatively less effort"

kittens/hints/main.py, kitty/fonts/render.py, kitty/layout.py, kitty/tabs.py
Python allows chaining comparisons. Using this feature makes the code more readable IMO.
=> Simplify chained comparisions

glfw/wl_init.c, glfw/wl_monitor.c, glfw/wl_platform.h, glfw/wl_window.c
This only changes some formatting, whitespace, etc.. There are no
changes to the functionality.
Let me know if you don't like some of those changes.
=> Reduce the difference of glfw/wl_* to upstream

glfw/null_monitor.c, glfw/null_window.c
This only changes some formatting, whitespace, etc.. There are no
changes to the functionality.
Let me know if you don't like some of those changes.
=> Reduce the difference of glfw/null_* to upstream

glfw/cocoa_init.m, glfw/cocoa_monitor.m, glfw/cocoa_platform.h, glfw/cocoa_window.m
This only changes some formatting, whitespace, etc.. There are no
changes to the functionality.
Let me know if you don't like some of those changes.
=> Reduce the difference of glfw/cocoa_* to upstream

setup.py
The macOS specific `package()` code changes the directory. This didn't cause any problems before 9135387cfa141e9ec27271bc41d5b6c43da90197 since `compile_commands.json` was written to the filesystem before `package()` was called. This is not the case anymore, which results in `compile_commands.json` being written into the `kitty.app` bundle. I fixed the problem by using a context manager to change the direcctory back after `kitty.app` was created.
=> Fix incremental compilation

setup.py
=> Clean asan-launcher and kitty-profile

docs/changelog.rst
I think it is not clear what this entry actually means without the additional explanation.
=> Update a changelog entry to be more descriptive

docs/index.rst
=> Update docs on kitty completion for bash v3.2, etc

kitty/utils.py
I'm not sure, how you feel about adding more editors.
=> Add kakoune to the list of editors

glfw/cocoa_init.m, glfw/cocoa_joystick.m, glfw/cocoa_monitor.m, glfw/cocoa_time.c, glfw/cocoa_window.m, glfw/context.c, glfw/egl_context.c, glfw/glx_context.c, glfw/init.c, glfw/input.c, glfw/linux_joystick.c, glfw/monitor.c, glfw/nsgl_context.m, glfw/null_init.c, glfw/null_joystick.c, glfw/null_monitor.c, glfw/null_window.c, glfw/osmesa_context.c, glfw/posix_thread.c, glfw/posix_time.c, glfw/vulkan.c, glfw/wgl_context.c, glfw/window.c, glfw/wl_init.c, glfw/wl_monitor.c, glfw/wl_window.c, glfw/x11_init.c, glfw/x11_monitor.c, glfw/x11_window.c
Reduces the difference to upstream.
From https://github.com/glfw/glfw/commit/56aad76b164be741af21688ea3832093c2069cef.
=> Add C dialect reminders to each glfw source file

glfw/monitor.c
From https://github.com/glfw/glfw/commit/751c6f9a2792bfc0c09cd381293db21c5a15a9ed.
=> Fix assertion for glfwSetGamma value

kitty/cocoa_window.m
I think this is slightly more readable.
=> Format the @autoreleasepool blocks in kitty/cocoa_window.m like in GLFW

glfw/cocoa_window.m, kitty/cocoa_window.m, kitty/core_text.m
Inspired by https://github.com/glfw/glfw/commit/9a9568212c2dfd17fe46845eaa68ec0731de6173.
=> Cocoa: Move slightly towards modern Objective-C

glfw/glfw3.h
From https://github.com/glfw/glfw/commit/3cf7645b96c593d74f089069ac2e1c67938efd7f.
=> GLFW: Documentation work

docs/faq.rst
This is very useful on mac :) especially.
issue: https://github.com/kovidgoyal/kitty/issues/1846
=> Adding documentation for how to map shortcuts

Makefile
Maybe this can be checked automatically by the CI in the future.
=> Remove trailing whitespace

Makefile
This indentation is not actually needed, right?
=> Remove unnecessary indentation

docs/faq.rst
Thanks to amarshall's help:
https://github.com/kovidgoyal/kitty/issues/765#issuecomment-487381289
=> Update FAQ with FreeBSD termcap info

glfw/x11_window.c
Fixes https://github.com/kovidgoyal/kitty/issues/2008.
=> Fix broken paste on X11

glfw/cocoa_window.m
From https://github.com/glfw/glfw/commit/c3ed70a4b77a2a4a08ef9a7cac7ac64a1835118d.
=> Cocoa: Add NSApplicationDelegate protocol

glfw/glfw3.h
From upstream: https://github.com/glfw/glfw/commit/773f4495f005004ea17fbc4a96b6b1ce758e79d6.
=> Reduce difference to GLFW upstream

glfw/glfw3.h
From upstream: https://github.com/glfw/glfw/commit/51bb76c7c3de934b2dd3affcdc297a32e4817835.
=> GLFW: Improve (?) reference documentation for callbacks

glfw/glfw3.h
From upstream: https://github.com/glfw/glfw/commit/d5ab3e919a4f163f4010f7112a9cf1bdcd80f805.
=> GLFW: Cleanup

glfw/glfw3.h, kitty/glfw-wrapper.h
I think these two "sentences" should be connected.
=> Minor grammar correction

kitty/fonts/box_drawing.py
See discussion in https://github.com/kovidgoyal/kitty/commit/576b03c047c4f538bca3f5b1b3501e7a930f355d.
I don't understand the algorithm enough to check if this change is really correct, please check.
=> Fix line drawing algorithm

kitty/boss.py, kitty/config_data.py, kitty/state.c, kitty/tabs.py
This PR allows moving windows away into new tabs and is related to #1310. Merging windows into other tabs could build upon this PR.
Please check my assigned hotkey and maybe propose a different one. So far i thought about e(x)tract (Ctrl+Shift+x). Maybe we can come up with something better, that also supports the other direction of merging windows into existing tabs.
=> move windows into separate tabs

glfw/cocoa_platform.h
From upstream: https://github.com/glfw/glfw/commit/94cb0347abdc4e8ebf8dcf133894a764d395b84c.
=> Cocoa: Add comments for Cocoa symbol macros

glfw/nsgl_context.m
From upstream: https://github.com/glfw/glfw/commit/bd452016be99e10d7fa8282cd75b1c53e0d5a8cc.
=> Cocoa: Cleanup

glfw/cocoa_window.m
From upstream: https://github.com/glfw/glfw/commit/2c519709be0dacc7af2908982a7ab80b889a8126.
=> Cocoa: Fix full screen window iconification

glfw/wl_init.c
From upstream: https://github.com/glfw/glfw/commit/a80788c17f3376177b45d52f983d4d98f1175af2.
=> Wayland: Don’t update cursor position in the frame

glfw/cocoa_init.m
From upstream: https://github.com/glfw/glfw/commit/b3544ca43e2fd328aa084f118789c7eeda5869a8.
=> Cocoa: Update outdated comment

glfw/cocoa_window.m
From upstream: https://github.com/glfw/glfw/commit/506a6aafdee2bb043da5cef6e28377466dda2f09.
=> Formatting

glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/4837b78ffe48aa9fab7a9657347b77cba104979a.
=> X11: Fix maximization of hidden windows

glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/9db156421f038e5a269a63d59e509f4fb1e2392b.
=> X11: Fix updating GLFW_FLOATING on a hidden window

glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/4e70c95aa3bcb666320e17f2097f33d18a7fc225.
=> X11: Cleanup

glfw/cocoa_monitor.m, glfw/cocoa_platform.h
From upstream: https://github.com/glfw/glfw/commit/b4a8eb9b197caebcec1304cd3d55cd56e3869376.
=> Cocoa: Only create per-monitor display link once

glfw/x11_platform.h, glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/fe57e3c2921a1901390534e1e51053df70b5644b.
=> X11: Fix no window position events during resize

kittens/icat/main.py
Not really much to say. It's missing, I wanted to test it, here we are.
=> Add --z-index to icat kitten

kitty/screen.c
See https://github.com/kovidgoyal/kitty/issues/1711#issuecomment-574423471
=> Multiline triple-click selections: Don't ignore leading spaces in first line

glfw/x11_platform.h, glfw/x11_window.c
From upstream: glfw/glfw@fe57e3c and glfw/glfw@9372ba9.
This is #2251 again with a fix for the bug reported in #2255.
@rien333 please test that the fix works properly.
=> X11: Fix no window position events during resize, Attempt 2

docs/changelog.rst
=> Add :pull:`2248` to changelog.rst

kitty/config_data.py, kitty/fonts.c, kitty/fonts/render.py, kitty/state.c, kitty/state.h
Following #2337 I am making this PR to make the cursor beam thickness configurable. This is my first contribution to Kitty and I had some difficulties understanding how accessing the configuration datas is done so I hope what I did is idiomatic. If it isn't please point me in the right direction and I'll fix it!
=> Make cursor beam thickness configurable

docs/changelog.rst, kitty/config_data.py, kitty/fonts.c, kitty/fonts/render.py, kitty/state.c, kitty/state.h
I just figured it'd make sense to also be able to configure the underline cursor's thickness. Sorry for making a second PR.
=> Make underline cursor thickness configurable

glfw/wl_window.c
=> Fix typo in comment

kitty/child-monitor.c
Found with Cppcheck.
Do you know what could have happed in practice?
=> Fix boolean value assigned to pointer

INSTALL.md
They were rendered as code before.
=> Make links clickable in INSTALL.md

docs/kittens/custom.rst
This file used 3 spaces some places and 4 spaces other places. Other
files like diff.rst and hints.rst use 4 spaces.
=> Fix indentation in kittens/custom.rst to 4 spaces

kitty/child-monitor.c, kitty/cli.py, kitty/fast_data_types.pyi, kitty/gl.c, kitty/main.py, kitty/state.c, kitty/state.h
=> Rename --debug-gl to --debug-rendering and hide "No render frame received" by default

kitty/desktop.c
Having an array of library names and iterating over it looks nicer than having several variables and calling `dlopen()` multiple times manually.
It should also make it easier to use custom library names instead by using the preprocessor, which I plan to do in the near future.
This will be useful for nix since they currently patch this code to change the library name to include the full path.
What was the reason for using `static` before?
=> Use loop instead of calling dlopen() multiple times

kitty/monotonic.h
The rest of the file is also indented with spaces.
=> Convert two tabs to spaces

kitty/data-types.c
There is already a check if `m` is `NULL`, so there is no need for a second `NULL` check after that.
=> Simplify code

glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/ef5220d6b10174d0f7cce965475e34527afcfbcf.
=> X11: Clarify code flow for Clang static analysis

glfw/x11_init.c
From upstream: https://github.com/glfw/glfw/commit/5f9dfe3d83af4d6b95c2e4f19adadc334eb314ae.
=> X11: Clarify function name and comment

glfw/cocoa_platform.h, glfw/cocoa_window.m
From upstream: https://github.com/glfw/glfw/commit/91eebe922de06a3ed4ba6622686c436c7941aa63.
=> Use CALayer instead of NSView for EGLNativeWindowType

glfw/cocoa_monitor.m
From upstream: https://github.com/glfw/glfw/commit/4ec7daf3e92440efab8dac7c1f4c60707d990ed0.
=> Cocoa: Replace display link with IOKit query

glfw/input.c
From upstream: https://github.com/glfw/glfw/commit/c32dc3a0856e339d8de582582fcbedec430e14b4 and https://github.com/glfw/glfw/commit/02874d9c148cf549abc403e07856d7531f4fcce6.
=> GLFW: Fix half-axis to gamepad button value mapping

glfw/wl_window.c
From upstream: https://github.com/glfw/glfw/commit/44af6bb9360df274b514f958f9a6a52a93c7fe32.
=> Wayland: Implement raw mouse motion control

glfw/wl_init.c, glfw/wl_platform.h, glfw/wl_window.c
From upstream: https://github.com/glfw/glfw/commit/92b3fd02e58c5422c60f4f52499189e727969564.
=> wayland: save serial from all input sources

glfw/glfw3.h
From upstream: https://github.com/glfw/glfw/commit/105cf32e0b05e207d4cd5efa462887569ca2116a.
=> Fix desktop GL header not always being suppressed

glfw/egl_context.c
From upstream: https://github.com/glfw/glfw/commit/a84a30ab6399eedd4606da226fe4f02eab3c2d2e.
=> Win32: Fix VS /W4 compile warnings

glfw/glfw3.h
From upstream: https://github.com/glfw/glfw/commit/7486e12f88b2a9039b805356bcbe259c0fca5c2d.
=> Add statement to docs for glfwTerminate

glfw/cocoa_window.m, glfw/glfw3.h, glfw/init.c, glfw/wl_monitor.c, glfw/wl_window.c, kitty/glfw-wrapper.h
From upstream: https://github.com/glfw/glfw/commit/9a87c2a4b49808d3666c7b093b77e8512fa23908.
=> Add feature available/implemented errors

glfw/null_init.c, glfw/null_monitor.c, glfw/null_platform.h, glfw/null_window.c
From upstream: https://github.com/glfw/glfw/commit/e0c77f71f90e3bb8495c5c88fb0fb054d71cf7fc.
=> Null: Make platform more conformant

glfw/glfw3.h
From upstream: https://github.com/glfw/glfw/commit/81f475bccbc0e784e8327005f2e66e3546fe8da0.
=> Fix GLU header inclusion being disabled

glfw/cocoa_platform.h, glfw/cocoa_window.m, glfw/egl_context.c, glfw/egl_context.h, glfw/internal.h, glfw/null_platform.h, glfw/wl_platform.h, glfw/wl_window.c, glfw/x11_platform.h, glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/d7f7b0e1b59d1fd53c68b4a6beb025af5d9786e6.
=> EGL: Replace native handle macros with functions

glfw/cocoa_window.m, glfw/egl_context.c, glfw/egl_context.h, glfw/internal.h, glfw/wl_window.c, glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/aec9fae8f34079561d408c8599e7ac08a7013041.
=> EGL: Add support for EGL_EXT_platform_base

glfw/glfw3.h, kitty/glfw-wrapper.h
From upstream: https://github.com/glfw/glfw/commit/4e3b43383a1e738dfcf47205671246f2008a8d94.
=> Re-word docs for GLFW_OPENGL_DEBUG_CONTEXT attrib

kittens/hints/main.py
=> Expand ~ in the path argument for linenum in hints

bypy/linux/__main__.py
See 527ff0238a9b607857d98eddade18450bdc4ad73.
=> Replace EnvironmentError with OSError

glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/ceb20c7f97994106db17cc66bd8abad331bc355e.
=> X11: Fix race in window hovered query

glfw/x11_window.c
From upstream: https://github.com/glfw/glfw/commit/49dbcfcb8c5a0f16fc914a114c8d5cfc1a5f97c8.
=> X11: Fix cursor hover query retry behavior

glfw/null_monitor.c
From upstream: https://github.com/glfw/glfw/commit/6c031af2452669be3d05b44857ad2daf0491cad9.
=> GLFW: Null: Fix typos in workarea retrieval

glfw/cocoa_window.m, glfw/glfw3.h, glfw/internal.h, glfw/null_window.c, glfw/window.c, glfw/wl_window.c, glfw/x11_init.c, glfw/x11_platform.h, glfw/x11_window.c, kitty/glfw-wrapper.h
From upstream: https://github.com/glfw/glfw/commit/d285a9fdeb5e7f4688ebbd8f8fa8f101b01b5bea.
=> GLFW: Add support for mouse input transparency

docs/integrations.rst, docs/kittens/custom.rst
Add link to [kitty-weechat-hints](https://github.com/GermainZ/kitty-weechat-hints).
=> Add link to weechat-hints kitten

glfw/null_monitor.c, glfw/null_window.c
From upstream: https://github.com/glfw/glfw/commit/cd0dc76c7c979fdec0b7b3721e3a91de7a730d0d.
=> GLFW: Null: Fix out parameters not being set

glfw/wl_init.c
From upstream: https://github.com/glfw/glfw/commit/0ef149c8f2451fbc8e866834675a075cfc295b6c.
=> GLFW: Wayland: Assume 96 DPI if physical size is <= 0

kitty/config_data.py, kitty/mouse.c, kitty/state.c, kitty/state.h
#3020
this PR duplicates #3040 and adds additional option of changing pointer shape when dragging.
#3040 covers most of my usecase so this PR is a nice to have, but nonessential.
=> Pointer shape when dragging

kitty/config_data.py, kitty/mouse.c, kitty/state.c, kitty/state.h
=> default_pointer_shape option

glfw/cocoa_window.m
=> Fix memory leak in unlikely failure condition

kitty/core_text.m
=> Fix memory leak

docs/graphics-protocol.rst, docs/integrations.rst
Signed-off-by: Henner Zeller <h.zeller@acm.org>
=> Add timg (http://timg.sh/) to graphics protocol users program list.

glfw/xkb_glfw.c
=> Handle multiple real modifiers mapping to the same virtual modifier

setup.py
FreeBSD make does not work to build documentation.
=> Freebsd: use gmake to build docs

docs/graphics-protocol.rst
=> graphics-protocol.rst: s/and/an/

docs/changelog.rst
Iosevka with kitty support is already out, just waiting for kitty to be released too :tada:
=> Fix Iosevka version in the docs

glfw/cocoa_monitor.m
It basically applies this fix: https://github.com/glfw/glfw/pull/1833
=> Fix "Cocoa: Failed to find service port...".

docs/glossary.rst, docs/kittens/remote_file.rst, kitty/options/definition.py
Conveys a more accurate understanding of kitty's default behavior, thanks to Kovid's comments.
=> Updated description for the "editor" config var

kitty/config.py, kitty/options/definition.py, kitty/options/parse.py, kitty/options/types.py, kitty/options/utils.py, kitty_tests/options.py
=> add `clear_all_mouse_shortcuts` option to clear mouse_maps

kittens/unicode_input/main.py
Scroll in unicode input, when number of cells exceeds screen size. Well tested, near zero performance penalties. 
Scrolls by the entire screen, can be adjusted in line 265 to any other amount including one line:
scroll_amount = self.num_rows
Reference: https://github.com/kovidgoyal/kitty/issues/4064
=> Scroll in unicode input

kitty/boss.py, kitty/rc/select_window.py
Since no other os window can operate when select-window is launched and expects the user to select it, the corresponding os window will be focused directly.
Also add a new `--reactivate-prev-tab` to restore the previously active tab of the matched tab after the selection is done, and restore the os window that was active before the selection.
This allows the following scenario:
Initiate the selection of tab-2 of os-window-2 in os-window-1 (active os-window), and after the selection, restore tab-1 of os-window-2 as the active tab and bring os-window-1 (last active os-window) back into focus to continue the operation.
=> Allow select-window to reactivate previously activated tab

kitty/fast_data_types.pyi, kitty/mouse.c, kitty/screen.c, kitty/screen.h, kitty/state.c, kitty/state.h, kitty/window.py
Allows selecting command output by mouse click.
I have not added a default binding to `definition.py`.
=> Add command output mouse selection

docs/kittens/themes.rst
Changes
- Add link to metadata file
- Add link to working with pull requests
- Elaborate on the minutiae of steps involved
Tested locally by building docs and verifying links in browser.
=> Improve theming doc's contriubting section

kitty/conf/types.py
There are some options that are not added to the default configuration.
=> Formatting config options that are not added to default

kitty/rc/detach_tab.py, kitty/rc/detach_window.py
Fix the issue that detach remote control command cannot match the target.
=> Fix remote control detach-tab detach-window

kittens/tui/images.py, kitty/boss.py, kitty/tabs.py, kitty/utils.py
Find executable file paths with the unified PATH search function.
=> Use the unified PATH search function

kitty/shell_integration.py, shell-integration/zsh/.zshenv
This fixes a few minor issues in zsh shell integration. If this is something you are interested in, I can have a pass over `kitty.zsh`. That one can have more substantial improvements.
=> Minor robustness improvements to zsh shell integration

shell-integration/zsh/.zshenv, shell-integration/zsh/kitty-integration, shell-integration/zsh/kitty.zsh
Context: https://github.com/kovidgoyal/kitty/pull/4386#issuecomment-1000363165
=> Unfunction kitty-integration in zsh

kitty/shaders.c
Some changes on visual window selection UI rendering.
=> DRYer: Use gl_size to convert coordinates

shell-integration/zsh/kitty-integration
Might fix #4428.
Tested *extremely* lightly. The linked issued doesn't have decent instructions how the problem can be reproduced, so I didn't even try to.
=> Replace add-zle-hook-widget with a series of hacks in zsh integration

shell-integration/bash/kitty.bash
the array iteration wasn't implemented correctly for KITTY_SHELL_INTEGRATION variable. the i variable in for loop wasn't iterating through all the elements of that array
=> Bash: for loop array iteration fix

shell-integration/zsh/kitty-integration
This bug is extremely unlikely to cause issues.
=> Fix a minor bug in zsh integration

glfw/cocoa_window.m
Resolves issue described here:
https://github.com/kovidgoyal/kitty/issues/4472
All credit goes to @page-down
=> Fixes traditional fullscreen hide for Mac OS >= 10.15

glfw/cocoa_window.m
There is another situation when dealing with macOS input method modifier keys.
It is possible for the input method to call insertText and then continue to send the event to the program without intercepting it.
I have tested it and it works fine to insert text in this case too.
There is also a problem with this PR, if the input method inserts text immediately after the initial press of the modifier key when there is no markedText, then it will not work. A separate flag is needed to replace `handled` from `[inpctx handleEvent:event]` (which is meaningless).
But I haven't come across this kind of input method so far.
Please review if there is anything that needs to be adjusted.
=> macOS: Fix text insertion by modifier keys when using IME

kitty/rc/new_window.py
Previously `--dont-take-focus` has been added to launch.
https://github.com/kovidgoyal/kitty/discussions/4125#discussioncomment-1486817
Also added to new_window now.
=> Also add alias --dont-take-focus to new_window

docs/conf.py, docs/graphics-protocol.rst, glfw/glfw.py, kittens/diff/collect.py, kitty/conf/utils.py, kitty/config.py, kitty/fonts/render.py, kitty/options/utils.py, kitty/rc/disable_ligatures.py, kitty/window.py, logo/make.py, publish.py, setup.py, update-on-ox
Following `Drop support for python 3.6`
https://github.com/kovidgoyal/kitty/commit/f0e8ab8f31bd873869f04972cc8bbc0df6c7df8e
=> Refactor: More f-string

setup.py
This line is getting really close to the limit of 160 characters.
In my personal fork of kitty, I added one more option here, which causes pyflakes to complain.
=> Shorten a long line

glfw/cocoa_init.m
For global shortcut to switch the next input source in the macOS system preferences, final confirmation is only given when all modifier keys are released.
https://github.com/kovidgoyal/kitty/issues/4621
=> macOS: Fix select next input source not working

docs/changelog.rst, docs/launch.rst, kitty/launch.py
Add @first-line-on-screen and @first-line-on-screen .
https://github.com/kovidgoyal/kitty/issues/4462
This issue has been around for a while.
Is it OK for this?
=> Add arguments to get the first and last line of text for launch command

.github/workflows/ci.py, Brewfile, docs/build.rst
Fixes `Error: Invalid Brewfile ...`.
Tested with the latest homebrew bundle.
https://github.com/Homebrew/homebrew-bundle
=> Update Brewfile format

glfw/cocoa_init.m
issue: https://github.com/kovidgoyal/kitty/issues/4657
A global shortcut that will be enabled by default should work in the following cases
- Empty `AppleSymbolicHotKeys`.
- The global shortcut id exists and is enabled, but the value is missing.
- This key combination is configured on multiple other global shortcut key ids, but is disabled.
`Shift+Cmd+backtick` should work in kitty when `Cmd+backtick` is configured as a global shortcut for other functions.
When `Cmd+backtick` is disabled, it should work in kitty.
When the global function is set to empty key `none` and enabled. The default shortcut key should work in kitty.
There are several cases of plist
- Empty, not exists.
- Some ids are enabled, but no values.
- Some ids are disabled, but no values.
- The value exists.
- The same key …
=> macOS: Add missing global shortcuts that will be enabled by default

glfw/wl_init.c
=> Scale touchpad input by display scale on wayland

kitty/fonts.c
=> Also check ### to confirm spacer strategy

kitty_tests/shell_integration.py
Clean up the commented debug code left behind.
=> Tests: Clean up previous PR

kitty/shell_integration.py
`ZDOTDIR` may be configured in /etc/zshenv.
Check only if the `ZDOTDIR` does not exist and all zsh startup files are not present.
Does not affect the performance for normal users.
Tested with
```zsh
[[ -o globalrcs ]] || return
[[ -v ZDOTDIR ]] || ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
```
zsh auto integration never worked for me, until this patch. I don't have any zsh files in `$HOME`.
---
kitty/child.py
```python
class Child:
def fork(self) -> Optional[int]:
if is_macos and exe == shell_path:
argv[0] = (f'-{exe.split("/")[-1]}')
```
Is it possible to narrow down the scope of the shells that need to modify `argv[0]`?
For example, limit it to `bash` or any other shell that is known to be necessary.
=> Try to get ZDOTDIR from /etc/zshenv when all zsh startup files are not present

kitty/utils.py
It looks like `self.fd` was missed when refactoring.
I have tested diff kitten and it is working again.
https://github.com/kovidgoyal/kitty/commit/c9cc8328750d784c1ae66f0642621c3eee1acb5f
Fixes [#4763](https://github.com/kovidgoyal/kitty/issues/4763)
=> Fix ScreenSizeGetter

glfw/wl_client_side_decorations.c, glfw/wl_init.c, glfw/wl_platform.h, glfw/wl_window.c
See https://github.com/swaywm/sway/pull/6844#issuecomment-1054071084
=> Wayland fix configure

docs/keyboard-protocol.rst
https://gitlab.com/craigbarnes/dte/-/issues/138
=> Mention dte text editor in list of apps in docs/keyboard-protocol.rst

shell-integration/ssh/bootstrap.sh
I see that Perl seems to be installed on more systems.
Now change the remaining two places to prefer Python as well.
Sorry for the noise.
=> Use Python in preference to Perl

glfw/wl_client_side_decorations.c, glfw/wl_init.c, glfw/wl_platform.h, glfw/wl_window.c
=> Wayland fixes

kitty/boss.py
Also list the current active window in the candidates and gray it out.
Consistent with the implementation of visual window selection for other layouts.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.visual_window_select_characters
```shell
kitty -o visual_window_select_characters=fjdksl123 -o enabled_layouts=stack,grid
```
=> Use the configured chars when visually selecting windows on stack layout

kitty/options/definition.py
See discussion at https://github.com/kovidgoyal/kitty/issues/4908
=> Clarify documentation of `macos_option_as_alt`

docs/shell-integration.rst, shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Remove duplicated `launch --allow-remote-control`.
=> Docs: Remove duplicate options

kitty/file_transmission.py, kitty/window.py
Fixes #5005
I'm not a fan of these bots.
Even with manual review, they are unlikely to have in-depth understanding of the project and will produce false positives.
=> Fix f-strings

setup.py
Fixup of bec620a8d30c36453e471b140b07483c7f875bf4.
=> Add kitty/fontconfig.c to SPECIAL_SOURCES

kitty/rc/new_window.py
Since `use_shell=False` is hardcoded in tabs.py, Tab, `new_special_window`, when kitty is started with arguments and the remote control command new-window is used, it will default to running the program specified by the arguments at startup instead of the default shell.
```shell
kitty --config=NONE --listen-on=unix:/tmp/mykitty -o allow_remote_control=yes vim
kitty @ --to unix:/tmp/mykitty new-window
```
Launch is used in this PR to implement the new-window rc function.
Maybe you have a better idea.
I also wonder if we should deprecate `new-window` in the documentation and instead recommend using `launch`.
This rc command is left for backward compatibility.
=> Fix the rc command new-window does not open the shell by default

glfw/cocoa_init.m
Do not handle the Eisu and Kana keys from the JIS keyboard layout.
https://github.com/kovidgoyal/kitty/issues/5232
=> macOS: Fix JIS Eisu and Kana keys not working

docs/changelog.rst, kitty/boss.py, kitty/rc/launch.py
Fixes #5276
I hope all cases have been covered, please review, thanks.
=> macOS: Fix unable to open new tab/window when there is no OS window

kitty/rc/scroll_window.py
Allow float numbers to be used when scrolling by page.
Previously discussed in:
https://github.com/kovidgoyal/kitty/issues/5294#issuecomment-1191291569
=> Remote control: Allow half-scrolling when scrolling window by page

kitty/options/definition.py, kitty/tab_bar.py, kitty/tabs.py
this option add current working directory to the tab by using active windows child directory.
=> add cwd to TabBarData

docs/changelog.rst, kitty/utils.py, shell-integration/bash/kitty.bash, shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish, shell-integration/zsh/kitty-integration
GitHub discussion related to the editor path issue:
https://github.com/kovidgoyal/kitty/discussions/5298#discussioncomment-3223600
=> Fix ~ in editor and exe_search_path, and other minor changes

kitty/fonts.c
Works for me
Closes https://github.com/kovidgoyal/kitty/issues/5308
=> Fix modify_font underline_position 1

docs/layouts.rst, kitty/layout/tall.py
Can specify 1 bias to toggle between that and 50%.
Can specify multiple biases to rotate through them with each call to the
layout_action.
Left a comment regarding working around either a possible bug or a
design decision.
=> Add layout_action to change bias on tall layout

kitty/rc/close_tab.py, kitty/rc/close_window.py, kitty/rc/scroll_window.py, kitty/rc/signal_child.py
Add --no-response to:
- close-tab
- close-window
- scroll-window
- signal-child
Related GitHub discussion:
https://github.com/kovidgoyal/kitty/discussions/5406
=> Remote control: Add --no-response to some commands

docs/build.rst
=> change linux-package build instructions to use make target

docs/changelog.rst, kitty/options/definition.py, kitty/options/parse.py, kitty/options/to-c-generated.h, kitty/options/types.py, kitty/shaders.c, kitty/state.h
This PR is based on the following reply.
https://github.com/kovidgoyal/kitty/issues/5596#issuecomment-1280394806
=> Add an option to control background image tinting for window gaps

shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish
Previous discussion:
https://github.com/kovidgoyal/kitty/pull/5712
=> Shell integration: Report cwd on the fish prompt event

docs/overview.rst
=> docs: fix overview.rst

kitty/iqsort.h
=> Fix typo in iqsort.h

docs/overview.rst
=> Fix typo in overview.rst

kitty/entry_points.py
Provide the currently supported fish completion script when requesting version 2.
This was missed in the previous PR.
=> Completion: Handle kitty +complete setup fish2

docs/changelog.rst, kittens/hints/main.py, kitty/boss.py
Use a new prefix `#` to specify the name of the buffer to copy to.
=> hints kitten: Allow copying matches to named buffers

kittens/hints/main.py
Previously, when matching linenum, it is not possible to perform a copy action using the `--program` option as described in the documentation.
=> hints kitten: Perform copy action with --program when matching linenum

docs/faq.rst
- Added the 2d winky terminal icon
- Added the 3d reinterpretation of the original
Have not worked with rst yet. How does one preview the build?
=> Added new icons to the FAQ page

docs/faq.rst
Follow up to #6109 to use optimized icon previews
=> Updated faq with optimized alt icon preview urls

docs/basic.rst
I'm constantly googling this because it isn't in the list, and it's basic enough that I think it should be.
=> docs/basic.rst: Add resize window shortcut

kitty/options/definition.py
=> Warn of possible graphics issues with text_fg_override_threshold

shell.nix
Some small fixes to build on NixOS.
=> fix: Correct Nix shell for building correctly

docs/integrations.rst
Hi @kovidgoyal, I'd like to add [kitty-scrollback.nvim](https://github.com/mikesmithgh/kitty-scrollback.nvim) to the integrations with other tools section of the docs.
=> Document integration with tool kitty-scrollback.nvim

kitty/boss.py
=> fix typo and add a couple examples

glfw/wl_client_side_decorations.c, kitty/freetype_render_ui_text.c, kitty/history.c, kitty/mouse.c
=> Fix build with gcc14

docs/layouts.rst, kitty/options/definition.py
While reading the kitty docs I have found a small typo and a few things that could have been adjusted. This PR addresses those things :smiley:.
=> docs: minor adjustements

kitty/fonts/box_drawing.py
This changes the algorithm used to draw the Unicode shade characters to avoid gaps or parity mismatches between adjacent characters at the expense of making the spacing appear slightly less even in some cases. 
Example 1 (current on left):
Example 2:
This could also be made optional via a config option.
=> Seamless rendering of shade characters

kitty/mouse.c
See issue below for details.
I am not sure whether this is the most appropriate fix, but it works on my machine.
Fixes kovidgoyal#7439.
=> fix: horizontal scrolling direction

docs/binary.rst
/home/$USER works most of the time but might be wrong
=> use `readlink -f ~` to get user home

kitty/keys.c
On some machines such as M series Macs the Fn key generates a keyboard event on its own. Add it to the list of modifiers so that, among other things, pressing it does not cause the scrollback buffer to scroll to the bottom.
=> Treat Fn as modifier key

kitty/fonts.c, kitty/fonts/box_drawing.py
Add two nerd font divider glyphs.
=> feat: add reder for nerdfont glyphs,\ue0d6, \ue0d7

kittens/diff/main.py, kittens/diff/ui.go
fix #7523
Feature: diff kitten: add action to move to next/previous file
=> [diff kitten] move next/prev file

docs/overview.rst
s/firt/first
Thank you very much for creating and maintaining Kitty, it's where I spend 8 hours a day each day and I really like using it.
=> Fix typo in docs

kitty/options/definition.py
Some small spelling errors as picked up by my Typos LSP.
=> Fix config spelling errors

kitty/trail_fragment.glsl
=> fix bug that trail not visible when vertical move

kitty/trail_fragment.glsl
the order of cursor_edge_y was wrong
=> fix bug that character under cursor trail not visible

docs/faq.rst
Following up from https://github.com/kovidgoyal/kitty/discussions/8196#discussioncomment-11739991.
=> Recommend using vim themes over terminal themes

docs/graphics-protocol.rst
Thanks for building the protocol! Very cool.
=> Add vat to list of applications that use the protocol

docs/desktop-notifications.rst
=> fix spelling

docs/launch.rst
The provided mywatcher.py script did not work because of improper indentation
=> Fix sample mywatcher.py code block

setup.py
See proposal in https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3/diffs
=> Add support for  xdg-terminal-exec

docs/faq.rst
Please add another icon if you like it
=> Another kitty icon

kitty/line.h
Fixes test case failures reported in #8548 on s390x machines
=> Fix endianness bug reported in issue #8548
